### ISSUE TITLE
MVVMTK0042 code fix does not respect original formatting/whitespace

### ISSUE THREAD

**Issue by bretthysuik** [CommunityToolkit/dotnet#1006]
### Describe the bug

MVVMTK0042 code fix does not respect the original formatting/whitespace of the code.

### Steps to reproduce

Before MVVMTK0042 code fix:

```c#
public partial class Class1 : ObservableObject
{
    [ObservableProperty] private string _name = String.Empty;
    [ObservableProperty] private int _age;
}
```

After MVVMTK0042 code fix:

```c#
public partial class Class1 : ObservableObject
{
    [ObservableProperty]
    public partial string Name { get; set; } = String.Empty;

    [ObservableProperty]
    public partial int Age { get; set; }
}
```

Original formatting/whitespace is not respected. This is particularly annoying when running the code fix on a solution or project which results in a ton of unwanted formatting/whitespace changes.

### Expected behavior

MVVMTK0042 code fix does not modify the original formatting/whitespace.

```c#
public partial class Class1 : ObservableObject
{
    [ObservableProperty] public partial string Name { get; set; } = String.Empty;
    [ObservableProperty] public partial int Age { get; set; }
}
```

### IDE and version

VS 2022 Preview, Rider, VS 2022

### IDE version

Visual Studio v17.13.0 Preview 1.0; Rider v2024.3

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [x] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.4.0-preview2

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
This is expected and intentional. We're relying on Roslyn doing auto-formatting, and leaving a blank line is the standard for properties.
