### ISSUE TITLE
MVVMTK0042 code fix does not work for fields with additional attributes (e.g. NotifyPropertyChangedFor)

### ISSUE THREAD

**Issue by bretthysuik** [CommunityToolkit/dotnet#1007]
### Describe the bug

MVVMTK0042 code fix does not work for fields with additional attributes (e.g. `NotifyPropertyChangedFor`)

### Steps to reproduce

Before MVVMTK0042 code fix:

```c#
public partial class Class1 : ObservableObject
{
    [ObservableProperty, NotifyPropertyChangedFor(nameof(Age))] private string _name = String.Empty;
    [ObservableProperty] private int _age;
}
```

After MVVMTK0042 code fix is applied to the project:

```c#
public partial class Class1 : ObservableObject
{
    [ObservableProperty, NotifyPropertyChangedFor(nameof(Age))] private string _name = String.Empty;
    [ObservableProperty]
    public partial int Age { get; set; }
}
```

`_name` is not automatically converted to a `public partial` property along with `_age`.

### Expected behavior

Fields with attributes in addition to `[ObservableProperty]` are automatically converted when the MVVMTK0042 code fix runs.

```c#
public partial class Class1 : ObservableObject
{
    [ObservableProperty, NotifyPropertyChangedFor(nameof(Age))] public partial string Name { get; set; } = String.Empty;
    [ObservableProperty] public partial int Age { get; set; }
}
```

### IDE and version

VS 2022 Preview

### IDE version

v17.13.0 Preview 1.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [x] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.4.0-preview2

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
This is expected, I only added support for one attribute per list, as I thought using multiple attributes would be more niche. But I suppose it's common enough that it's worth doing the additional work to support it. I'm doing this in a follow up, thank you for opening the issue! 🙂
