### ISSUE TITLE
VS Community 2022, Version 17.12.2, .net Version 4.8.09032 - MVVM, "This Generator is not generating Files"

### ISSUE THREAD

**Issue by colgansoftware** [CommunityToolkit/dotnet#1014]
### Describe the bug

I am attempting to work through .NET Maui and in the process of reviewing I receive this message on all SourceGenerators in the dependencies area for Android.  I see nothing in IOS, maccatalyst, or windows.
![Image](https://github.com/user-attachments/assets/4d375d2f-7c52-456b-bd3a-71bd1ef8faf5)

I did a search of this community as well as googling the terms in many structures above and find nothing indicating a fix or what I am doing incorrectly.  Any assistance would be appreciated.

### Steps to reproduce

.net version 8.0.0, Visual Studio Community Edition, version 17.12.2, Microsoft .NET Framework version 4.8.09032

Simply created a new .net Maui app project in visual studio using the create new project template; 
Created a viewmodel named baseViewModel, and added the following code in the class:

using CommunityToolkit.Mvvm.ComponentModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HairTrigger_V1.Mvvm.ViewModels
{
    public partial class BaseViewModel : ObservableObject
    {
        [ObservableProperty]
        public bool isBusy;
    }
}

### Expected behavior

I expect to see the appropriate reflection of the InotifyPropertyChanged implementation.

### IDE and version

VS 2022

### IDE version

17.12.2

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [x] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.2.1

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by colgansoftware** [comment]
This is the message I receive:
![Image](https://github.com/user-attachments/assets/f4b8f9cd-99f3-4a45-8e6a-7272853bf62e)

**Comment by Sergio0694** [comment]
You're looking at the wrong generator. You'll want to look at "ObservablePropertyGenerator".
