### ISSUE TITLE
Tons of "warning MVVMTK0045" on update

### ISSUE THREAD

**Issue by LucaCris** [CommunityToolkit/dotnet#1027]
### Describe the bug

Every working member, like:

    [ObservableProperty]
    bool readOnly;

Now require to be transformed in partial property...

### Regression

8.3.2

### Steps to reproduce

Update nuget and rebuild solution.

### Expected behavior

Zero warnings.

### IDE and version

VS 2022

### IDE version

17.12.3

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [x] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.4.0

### Help us help you

No, just wanted to report this

**Comment by ghost1372** [comment]
This is because of Native AOT

**Comment by Sergio0694** [comment]
This is by design, and the warning only shows up when using UWP/WinUI with AOT support enabled 🙂
Without addressing those warnings, the app will not be in a supported state and will most likely crash.
For instance, the Microsoft Store used to crash instantly at startup before addressing those warnings (that's why I added them).

**Comment by LucaCris** [comment]
> This is by design, and the warning only shows up when using UWP/WinUI with AOT support enabled 🙂 Without addressing those warnings, the app will not be in a supported state and will most likely crash. For instance, the Microsoft Store used to crash instantly at startup before addressing those warnings (that's why I added them).

So which is the official syntax for [ObservableProperty]? The doc is still on the old, known method...

**Comment by Sergio0694** [comment]
You should be using partial properties now:

```csharp
[ObservableProperty]
public bool ReadOnly { get; private set; }
```

**Comment by LucaCris** [comment]
Partial properties in Net8 are not supported. And without "partial" (as you just wrote) the error MVVMTK0052 is shown.

**Comment by Sergio0694** [comment]
Yes, you'll need to set `LangVersion=preview` in your .csproj, and build with VS 17.12 or above. The fundamental issue is that using fields results in code that is not trim/AOT safe in UWP/WinUI scenarios. Those warnings just make that clear. But it's not like there's some new issue: that has fundamentally always been broken. You basically have two options:
- If you don't care about trim/AOT support, suppress those warnings
- If you do care, update to .NET 9 and fix the warnings by using partial properties
