### ISSUE TITLE
Question: MVVMTK0005 base class annotation

### ISSUE THREAD

**Issue by get-flat** [CommunityToolkit/dotnet#109]
Is it possible to have a base class i.e. BaseViewModel annotated with [ObservableObject] and MyViewModel which inherits from the base class annotated **only** with [ObservableRecipient] (MVVMTK0005)

```csharp
[ObservableObject]
public partial class BaseViewModel
{
}

[ObservableRecipient]
public partial class MyViewModel : BaseViewModel
{
}
```

Kind of related question. The first thing I did for the ObservableRecipient example
```csharp
public partial class MyViewModel : ObservableRecipient
{
}
```
was
```csharp
[ObservableRecipient]
public partial class MyViewModel
{
}
```
Thanks to very descriptive MVVMTK0005 It seems that right now you have to annotate with both [ObservableObject] and [ObservableRecipient]. Is there any chance it could be simplified.

**Comment by Sergio0694** [comment]
Hey @get-flat, thank you for opening the issue and including a repro!
That was indeed a bug, I've fixed it in #110 and it will be available in the next release 😄

> "It seems that right now you have to annotate with both [ObservableObject] and [ObservableRecipient]. Is there any chance it could be simplified."

That is not currently planned to keep things more modular. We might revisit this in the future though 🙂
