### ISSUE TITLE
Code Generators degrade VS performance, add excessive load to Roslyn Analyzers and high CPU utilization

### ISSUE THREAD

**Issue by pisc-software** [CommunityToolkit/dotnet#11]
## Describe the bug

Visual Studio C# Code Editors get very sluggish, Roslyn Analyzer with high CPU usage. No actual work can really get done in the editors.

- [X] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:
Not observed on 7.0.2, after update to 7.1 this is showing. Reverting back to 7.0.2 is fixing this. Seems to be the Source Generators are loading up CPU to >50% up to 90% with the Roslyn Code Analyzers load.

## Steps to Reproduce

1. Update from 7.0.2 to 7.1 on a large project (unit is a 4 Core i7 with 4GB RAM on Windows 2012 Server development system).
2. Start to code.
3. Regular background utilization of >50% from Roslyn Code Analyzer, editing is sluggish, and not really possible.
4. Revert back to 7.0.2
5. Performance is back as used, VS is responsive again.

## Expected behavior

Update to 7.1 should not degrade VS performance in editing, building.

NuGet Package(s): 7.1

Package Version(s):

Visual Studio version:

- [X] 2019 (16.11.3)

**Comment by pisc-software** [comment]
> Hi @pisc-software, I'm going to assume this is about the MVVM Toolkit given it's the only project with source generators. There currently is a known performance issue on large projects due to the generators not being incremental, which is something I plan to do in the final release of the source generators in an upcoming version of the MVVM Toolkit (currently they're in preview). Are you using the new source generator feature extensively? I was hoping that if no code was being generated, the impact on IDE typing experience wouldn't really be noticeable disappointed_relieved
> 
> cc. @333fred is it expected that even when no work is being done, just having a bunch of generators with a syntax receiver will still result in noticeable IDE slowdown on large solutions? For context, [this](https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/fef65a5f3c3e812ec76377a751951fb11b33f8e2/Microsoft.Toolkit.Mvvm.SourceGenerators/ComponentModel/TransitiveMembersGenerator.SyntaxReceiver.cs#L19) is an example of what syntax receivers we have currently, there's 6 generators in total currently using some variation of this one, or equivalent. Thanks! smile

Sorry for the delay in answer, busy in finishing a project.

Are you using the new source generator feature extensively? 
Not really, but we are using the MVVM extensively in the project, so the analyzers create quite a number of files.
Right now we stay at 7.0.2, as the 7.1 features are not needed. Also on a beefier machine with lots of cores and RAM the 7.1.2 release is making the editor sluggish to react and Roslyn functions need a longer time to complete.

Is there a way to deactivate the code analyzers and still use 7.1.2?

**Comment by pisc-software** [comment]
> @Sergio0694 I guess if there's a tweak we could make to the existing code to make them not run if not-used, we should get it in 7.1.1, eh? Did you have a chance to try reaching out to Chris yet?
> 
> @pisc-software can you confirm too if your new code is just using the base classes and not trying to use the new source generator features?

We are not using any generator features, just the base classes and interfaces. However the Analyzers create new code as I we did see, especially on the IRecipient<> implementations - which we use in the project.

**Comment by otium99** [comment]
@Sergio0694 What version will this be fixed? I am using 7.1.2 and I have constantly massive CPU consumption and sluggishness when typing in VS. I was redirected from here: https://developercommunity.visualstudio.com/t/MVVM-source-generators-pre-incremental/10097930 and here https://developercommunity.visualstudio.com/t/visual-studio-2022-high-memory-usage-mor/1616483
