### ISSUE TITLE
Discussion: Should the MVVM SourceGenerator generate partial methods for ObservableProperty fields

### ISSUE THREAD

**Issue by sonnemaf** [CommunityToolkit/dotnet#117]
I wonder if it is useful when fields with the ObservableProperty attribute should also call a `On...Changing` and a `On...Changed` partial method. This would allow more extensibility. Look at this example code. The Customer has a name property. The source generator could generate two partial methods (OnNameChanging and OnNameChanged) which are called in the Setter of the property. When the methods are not implemented they call will automatically be removed by the compiler.

```CS
partial class Customer : ObservableObject {

    [ObservableProperty]
    private string _name;

}
```

The MVVM Source generator should generates this

```CS
partial class Customer : ObservableObject {

    [ObservableProperty]
    private string _name;

    [System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "7.1.0.0")]
    [System.Diagnostics.DebuggerNonUserCode]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public string Name {
        get {
            return _name;
        }
        set {
            if (!System.Collections.Generic.EqualityComparer<string>.Default.Equals(_name, value)) {
                OnNameChanging(value);
                OnPropertyChanging(nameof(Name));
                _name = value;
                OnNameChanged(value);
                OnPropertyChanged(nameof(Name));
            }
        }
    }

    partial void OnNameChanging(string value);
    partial void OnNameChanged(string value);
}
```

The developer can now decide to put code in the partial method. For example some code to start some business logic.

```CS
partial class Customer  {

    partial void OnNameChanged(string value) {
        // Start some business logic
    }

}
```

The Roslyn compiler will merge the two partial class files into one. Because the OnNameChanging was not implemented it is removed.

```CS
class Customer : ObservableObject {

    [ObservableProperty]
    private string _name;

    [System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "7.1.0.0")]
    [System.Diagnostics.DebuggerNonUserCode]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    public string Name {
        get {
            return _name;
        }
        set {
            if (!System.Collections.Generic.EqualityComparer<string>.Default.Equals(_name, value)) {
                OnPropertyChanging(nameof(Name));
                _name = value;
                OnNameChanged(value);
                OnPropertyChanged(nameof(Name));
            }
        }
    }

    void OnNameChanged(string value) {
        // Start some business logic
    }
}
```

Maybe the parameter for the `On...Changing` method should be a `ref` parameter so it can be modified inside the implemented partial method. 

What do you think?

**Comment by wbokkers** [comment]
Maybe make these calls optional? 
```
[ObservablePropery, GenerateOnChanging=true, GenerateOnChanged=true]
```
Do you ever need the OnNameChanged method? Currently you can subscribe to the PropertyChanged event and check for the property name. (admittedly that's a bit ugly)

**Comment by sonnemaf** [comment]
> Maybe make these calls optional?
> 
> ```shell
> [ObservableProperty, GenerateOnChanging=true, GenerateOnChanged=true]
> ```
> 
> Do you ever need the OnNameChanged method? Currently you can subscribe to the PropertyChanged event and check for the property name. (admittedly that's a bit ugly)

Partial methods with no access-modifier and a `void` return value are by itself optional. If you don't implement them the call will be removed by the compiler. I don't see the need for two extra attributes unless you find them uggly because the pollute the IntelliSense list. 

Alternative: add optional parameters/properties for the ObservableProperty attribute?

```CS
[ObservableProperty(GenerateOnChanging: true, GenerateOnChanged:true)]
private string _name;
```

**Comment by wbokkers** [comment]
Yes, I meant to use the optional parameter syntax. I obviously don't use this often.

**Comment by Sergio0694** [comment]
Thank you for opening the issue @sonnemaf!
I'm not opposed to the idea, and I like the fact that if users don't define the methods, they'll just be elided completely, so there's no unnecessary overhead nor IL size being added. I guess my one concern is: where is the line between adding too much complexity to `[ObservableProperty]` and just telling developers to define a property manually at that point? I can see though that this would offer much more flexibility, which I think is nice. @michael-hawker @Arlodotexe thoughts?
This should be an easy change to make, so I'd be happy to prototype it if we agree we all like the idea 🙂

**Comment by michael-hawker** [comment]
This is a pretty common convention, so I like this idea. 🙂

**Comment by Arlodotexe** [comment]
Seconded, this seems pretty useful. I'm on board.

Re `[ObservableProperty]` complexity -- if it's removed by the compiler when not used, I see no problem with making this the default and foregoing the feature flag to enable/disable it.

**Comment by Kation** [comment]
> > Maybe make these calls optional?
> > [ObservableProperty, GenerateOnChanging=true, GenerateOnChanged=true]
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do you ever need the OnNameChanged method? Currently you can subscribe to the PropertyChanged event and check for the property name. (admittedly that's a bit ugly)
> 
> Partial methods with no access-modifier and a `void` return value are by itself optional. If you don't implement them the call will be removed by the compiler. I don't see the need for two extra attributes unless you find them uggly because the pollute the IntelliSense list.
> 
> Alternative: add optional parameters/properties for the ObservableProperty attribute?
> 
> [ObservableProperty(GenerateOnChanging: true, GenerateOnChanged:true)]
> private string _name;

I think generate partial method should be optional.

It's useful to implement custom accessibility changing/changed method when having subclass.
