### ISSUE TITLE
MVVM Toolkit not correctly unloading using Appdomain.Unload() with Version 7.1

### ISSUE THREAD

**Issue by c-fricke** [CommunityToolkit/dotnet#12]
Hello!

After updating the version of the Toolkit from 7.0 to 7.1 we cannot unload the Appdomain correctly anymore.
Some background: in our Application we start another Appdomain containing the View that uses the MVVM Toolkit. After closing the View we also unload the Appdomain (via AppDomain.Unload(domain)) to properly unload everything. After updating the Toolkit from 7.0 to 7.1 this unload process runs forever (>10 minutes) and slows/blocks any further code being run in our Application. Going back to Version 7.0 fixes the issue. If you need furthe rInformation regarding this issue please reach out to me, I will help in any way I can.

Best Regards 
Chris

**Comment by Sergio0694** [comment]
This was closed by e2b336184f51fcd755f3151222ff948176ee954c, will be available in a future release 😊
