### ISSUE TITLE
Add `broadcast` parameter to ObservablePropertyAttribute

### ISSUE THREAD

**Issue by powerdude** [CommunityToolkit/dotnet#125]
It would be great if this parameter, and maybe others, could be added to the attribute so that the corresponding `SetProperty` is used.

**Comment by Sergio0694** [comment]
Hey @powerdude, thank you for opening this issue 🙂
This request makes sense to me, though I'm not a fan of the proposed design. The issue I have with it is that this new property would only ever make sense when used in a type inheriting from `ObservableRecipient`, or that is having its functionality injected by using `[ObservableRecipient]`. I have two possible ideas on how to go about fixing this:

1) Just making `broadcast = true` the default value if the overload is available. This would also mirror what we're doing when a validation attribute is used on a field with `[ObservableProperty]`: we're always executing the validation for it in that case.
2) Adding a new `[BroadcastChange]` attribute (or some name like that), which would act as an opt-in for broadcast.

cc. @michael-hawker @Arlodotexe thoughts?

**Comment by powerdude** [comment]
hi @Sergio0694,thanks for the feedback.  I'm curious as why the `Broadcast` method is in `ObservableRecipient` and not in `ObservableObject`.  I would think `ObservableObject` should be able to send out property changes as a "publisher" and an `ObservableRecipient` would be necessary to "subscribe" to those.  It seems limiting to say a publisher can't publish unless they are also a potential subscriber to something else.  

Am i off base with the purpose here?

**Comment by michael-hawker** [comment]
I'm not sure if I follow the root issue here about what this ask is? Is there another discussion elsewhere this is a follow-on from I can use to catch-up?

**Comment by powerdude** [comment]
the root issue is that if you want to be able to broadcast a property change event, you have to do it yourself by implementing the property and calling the correct `SetProperty` method.  The ask is to be able to use the `ObservableProperty` attribute to be able to do this.

**Comment by Sergio0694** [comment]
> "I'm curious as why the `Broadcast` method is in `ObservableRecipient` and not in `ObservableObject`"

@powerdude Because that method needs an `IMessenger` instance, and it would've caused `ObservableObject` to depend on that. This way instead, the functionality that is tied with `IMessenger` is just relegated to `ObservableRecipient`.

> "I'm not sure if I follow the root issue here about what this ask is?"

@michael-hawker The ask is basically to have a way to get the generated setter for observable properties in a class that inherits from `[ObservableRecipient]` or that uses `[ObservableRecipient]` to use `SetProperty(ref field, value, broadcast: true)` (instead of the normal `SetProperty(ref field, value)` overload from `ObservableObject`. My question is where this shouldn't just be automatic if that overload is availabe, or whether we should instead add a separate attribute to opt-in into this.

**Comment by michael-hawker** [comment]
Thanks @Sergio0694 I get it now. So with `ObservableRecipient` we have the built-in property sharing broadcast system, got it. So this is about hooking into that with source generators.

I feel like broadcasting everything by default seems like it would lead to odd behaviors that would be hard to debug, so I like the opt-in approach.

Is it possible to have a second attribute like `BroadcastChange`? I guess it'd just look and see if the inherited class is ObservableRecipient (or has that attribute as well), if not throw an analyzer warning and do nothing? And if so, it'd just generate with the alternate available overload, right?

**Comment by powerdude** [comment]
for my sake, what is the harm of `ObservableObject` needing `IMessenger`, and hence, being able to broadcast property changes?

**Comment by Sergio0694** [comment]
> "Is it possible to have a second attribute like `BroadcastChange`?"

@michael-hawker Yup that was my thinking as well, that's totally doable 😊
I think it would also avoid issues where you have both overloads from `ObservableRecipient` and `Validator`.

> "what is the harm of `ObservableObject` needing `IMessenger`, and hence, being able to broadcast property changes?"

It reduces modularity. `ObservableObject` is only meant to be an `INotifyPropertyChanged` and `Changing` implementation, nothing more, nothing less. If you also added `IMessenger` there, you'd have an extra field that's unnecessary for folks that don't use the messenger, it'd add other unnecessary overloads for the constructors, etc.

**Comment by timdinhdotcom** [comment]
Also, could we have ability to specify public getter but private setter?
