### ISSUE TITLE
Command defined as `ICommand` fails when another property uses `AlsoNotifyCanExecuteFor`

### ISSUE THREAD

**Issue by powerdude** [CommunityToolkit/dotnet#126]
It doesn't seem like the source generator checks or converts the command before writing `MyCommand.NotifyCanExecuteChanged()` to the property's code.  this should probably be outputted as `(MyCommand as IRelayCommand)?.NotifyCanExecuteChanged()` as a safe solution;

**Comment by Sergio0694** [comment]
Hello there. This is not supported by design, as the attribute is only meant to be used together with async relay commands.
Doing something like this would also introduce less predictable behavior, as that line could just be silently be skipped 🙂

**Comment by powerdude** [comment]
Hi @Sergio0694,

I understand, but I'd like to learn a little bit more about the reasoning here.  So, if I write code like the following:

```
[ObservableProperty] 
[AlsoNotifyCanExeecuteFor(nameof(MyCommand))]
private bool canRun;

public ICommand MyCommand => new AsyncRelayCommand(...);
```

the belief is that I shouldn't be able to do this even if this is legitimate, compilable code.  The UI using this doesn't need it be exposed as `IAsyncRelayCommand`.  It would seem like a reasonable request for the internals to check either before emitting the code or while running the code that `MyCommand` is of the correct type.
