### ISSUE TITLE
Add diagnostic for [AlsoNotifyChangeFor] on invalid targets

### ISSUE THREAD

**Issue by Sergio0694** [CommunityToolkit/dotnet#143]
Repro:

```csharp
public partial class MyViewModel : ObservableObject
{
    [ObservableProperty]
    [AlsoNotifyChangeFor("FooBarBaz")]
    public int number;
}
```

Same issue with `null`, not handled properly either (seems to just be ignored).

**Comment by Arlodotexe** [comment]
@Sergio0694 Looks like there's a mistake in your repro description here, possibly a copy/paste that didn't get changed?
