### ISSUE TITLE
Generated code needs to be with the same nullability context as defined by the user

### ISSUE THREAD

**Issue by egvijayanand** [CommunityToolkit/dotnet#155]
Using v8.0.0-preview2 NuGet package.

Have defined property of type `List<string?>` and decorated it with `[ObservableProperty]` attribute.

<img width="178" alt="MvvmToolkit-User-Code" src="https://user-images.githubusercontent.com/81947404/158390444-916488ac-ead4-470c-850f-20653c478496.png">

But the generated code is not nullable enabled, because of which getting warnings in other places.

<img width="578" alt="MvvmToolkit-Generated-Code" src="https://user-images.githubusercontent.com/81947404/158390599-125c347f-3227-4aec-87f9-61985d7db87e.png">

Nullability context needs to be taken care in the source generator.

**Comment by Sergio0694** [comment]
Thank you for the bug report! We are tracking nullability already (eg. if you define a `string?` field, you'll see the generated property respects that), but I guess we're not doing that correctly for nullability within type arguments. We should fix that 🙂

**Comment by egvijayanand** [comment]
Yes, the issue is with Generic types. Primitive nullable types work as expected.

**Comment by egvijayanand** [comment]
When is the next preview release planned?

**Comment by Sergio0694** [comment]
There is no fixed release date, but we're trying to get it published in a week or two. We mostly just need to complete #181 and #169, and then it should be good to go 🙂
