### ISSUE TITLE
ICommand issue after preview 2 upgrade

### ISSUE THREAD

**Issue by Tide** [CommunityToolkit/dotnet#167]
### Describe the bug

After upgrading from preview 1 to 2 I have an issue with a button now.  After clicking the button it does ot come back to CanExecute = true.  It just stays disabled.

I copied the code from this post as it was a similar issue and my code does to work like the authors in this post:
[https://github.com/CommunityToolkit/dotnet/issues/150#issuecomment-1066767749](https://github.com/CommunityToolkit/dotnet/issues/150#issuecomment-1066767749)

Here is what I get:
![Recording 2022-03-19 at 13 19 04](https://user-images.githubusercontent.com/237330/159131646-3c6ecd08-e5a0-41d9-ba45-7cd832780a00.gif)

### Regression

preview 1

### Steps to reproduce

```text
1. Create a new WinUI3 solution.
2. Add an ICommand and a button
3. Click the button
```

### Expected behavior

Button will allow you to click it again after the command is finished.

### IDE and version

VS 2022

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [x] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

preview 2

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment]
I have to say I'm a bit confused as to why you opened this issue given it's just a duplicate, and you had even found the right issue beforehand (where you could also see this has been resolved already) 🤔
