### ISSUE TITLE
Guard: Has "Whitespace" and "WhiteSpace"

### ISSUE THREAD

**Issue by jamesmontemagno** [CommunityToolkit/dotnet#172]
### Describe the bug

I noticed there are 2 methods for anything named "WhiteSpace" and "Whitespace"

### Steps to reproduce

```text
Checkout Guard.
```

### Expected behavior

Should be 1 spelling for Whitespace, whatever .net does

### IDE and version

VS 2022

### Nuget packages

- [ ] CommunityToolkit.Common
- [X] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [ ] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0-preview2

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
Hey James! Yup this is a known issue, in fact you can see the wrong one ("Whitespace") has already been marked `[Obsolete]` to be removed in a new major update. We should definitely do so in 8.0, I just forgot about it 😄
Thanks!

**Comment by jamesmontemagno** [comment]
Lovely! Yeah, seems like Preview 3 would be a good time to do it ;)
