### ISSUE TITLE
IncludeCancelCommand breaks generator

### ISSUE THREAD

**Issue by taori** [CommunityToolkit/dotnet#200]
### Describe the bug

```csharp
public partial class PromptWindowModel : ObservableValidator
{
    [ObservableProperty]
    private bool _isOpen;
    
    [ObservableProperty]
    private string _title;
    
    [ObservableProperty]
    [Required]
    [MinLength(2)]
    private string _promptText;

    [ICommand)] // generation works with this
    //[ICommand(IncludeCancelCommand = true)] // no command generated with this
    public Task UpdateSomethingAsync()
    {
        return Task.CompletedTask;
    }
}
```

### Steps to reproduce

```text
- Create WPF application
- Use 8.0.0-preview2 nuget reference
- paste code from description
- swap ICommand-attributes
```

### Expected behavior

I would expect both attributes to work. However after changing it to the second attribute source generator will break and no longer compile command code for that class.

### IDE and version

VS 2022

### IDE version

17.1.3

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0-preview2

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
This is by design and not an issue. That build error is actually specifically produced by the generator to inform you 🙂
If you look at the errors windo, you'll see this:

> "error MVVMTK0013: The method PromptWindowModel.UpdateSomethingAsync() cannot be annotated with the [ICommand] attribute specifying to include a cancel command, as it does not map to an asynchronous command type taking a cancellation token"

You can see where this diagnostics is generated, here:

https://github.com/CommunityToolkit/dotnet/blob/5bbab53888055057e61b1bd3fc99f31415e9ac11/CommunityToolkit.Mvvm.SourceGenerators/Input/ICommandGenerator.Execute.cs#L553-L565

**Comment by taori** [comment]
Hm so i guess it is an error with generators in general because i get no generator error, just no generation at all. Thanks! I will forward the issue then

**Comment by Sergio0694** [comment]
Mmh that is weird. Do you get a message saying a generator has failed to execute, by any chance? Also, could you try on the latest VS2022 Preview, and with a daily package for the MVVM Toolkit? You can get it from our preview feed: https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-MainLatest/nuget/v3/index.json.

Thanks!

**Comment by taori** [comment]
I have low disk space occasionally (Damn android SDK) so i usually don't install additional VS versions actually. But i can try the preview package feed. Oddly enough i did get an error once which i could not get rid off other than restarting VS but ever since then i just get no errors but it won't generate code either once i run into a scenario where diagnostics are thrown

**Comment by taori** [comment]
> Mmh that is weird. Do you get a message saying a generator has failed to execute, by any chance? Also, could you try on the latest VS2022 Preview, and with a daily package for the MVVM Toolkit? You can get it from our preview feed: https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-MainLatest/nuget/v3/index.json.
> 
> Thanks!

Generation works with Build.110, however i am not getting generator errors displayed when omitting the CancellationToken on the method. Good enough for me. I suppose if it works for you that is because preview has a better anlyzer experience

**Comment by Sergio0694** [comment]
Mmh no that's weird, the diagnostic should definitely still be emitted.
Just to be clear, you can repro that with this?

```csharp
public partial class PromptWindowModel : ObservableValidator
{
    [ICommand(IncludeCancelCommand = true)]
    public Task UpdateSomethingAsync()
    {
        return Task.CompletedTask;
    }
}
```

**Comment by taori** [comment]
![grafik](https://user-images.githubusercontent.com/5545184/161976919-45edecd3-e904-4de7-93fd-0f4bd7570093.png)

Yes. No errors. With neither build.110 nor preview2. Restarting VS made no difference either
