### ISSUE TITLE
MVVMTK0015 - AlsoNotifyChangeFor doesn't work for properties in base classes

### ISSUE THREAD

**Issue by rdadkins** [CommunityToolkit/dotnet#201]
### Describe the bug

Using `AlsoNotifyChangeFor` doesn't work when the target property exists in a base class.

Using 8.0.0-build.111.
This previously worked in 8.0.0-preview1

Example:
```csharp
public abstract partial class BaseViewModel : ObservableObject
{
    public string Content { get; set; }
}

public partial class ConcreteViewModel : BaseViewModel
{
    [ObservableProperty]
    [AlsoNotifyChangeFor(nameof(Content))]
    private string _other;
}
```

Error:
```
[MVVMTK0015] The target(s) of [AlsoNotifyChangeFor] must be a (different) accessible property, but "Content" has no (other) matches in type ConcreteViewModel
```

### Steps to reproduce

```text
See example above
```

### Expected behavior

I expected `CellContent` to be an eligible candidate for `AlsoNotifyChangeFor` as the target property is in the base class.

### IDE and version

Rider

### IDE version

2021.3.4

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0-build.111

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
Whoops! This was caused by #141, as it's not checking inherited types too.
Thank you for the report, we should definitely get this fixed ASAP 😄
