### ISSUE TITLE
win7 support

### ISSUE THREAD

**Issue by softboy99** [CommunityToolkit/dotnet#205]
### Overview

there're still many PC running windows7,Please adding win7 support

### API breakdown

/

### Usage example

/

### Breaking change?

No

### Alternatives

/

### Help us help you

No, just wanted to propose this

**Comment by teo-tsirpanis** [comment]
Hello, the Community Toolkit is just a library and I don't think it has anything platform-specific that precludes it from working on Windows 7.

Did you try running it there and failed?

**Comment by Sergio0694** [comment]
Closing this, as the .NET Community Toolkit doesn't have any specific OS dependencies at all.
As a side note, you should really not be using Windows 7 anyway as it's just no longer supported and not safe to use 🙃
