### ISSUE TITLE
OnChanged + OnChanging method generators

### ISSUE THREAD

**Issue by mkalinski93** [CommunityToolkit/dotnet#209]
Hello,

I am trying to figure out how these methods are generated

![image](https://user-images.githubusercontent.com/64005967/162566955-bd36f068-9773-4dd7-bf00-139de9a05149.png)

**Comment by Sergio0694** [comment]
Mmh I got a notification about a new comment but I don't see it here. @mkalinski93 did you leave another comment that is gone now? I wonder if it got lost with the transfer 🤔

**Comment by mkalinski93** [comment]
Hey Sergio,

No I did not replied to it yet.

In your generated file (MvvmSample.Core.ViewModels.Widgets.ValidationFormWidgetViewModel.cs) I saw the OnFirstNameChanging(value) and OnFirstNameChanged(value) methods.
There are some frameworks out there where you can intercept the "changing" mechanism.

for example: [DevExpress MVVM Run Custom Code When Property Value Changed](https://docs.devexpress.com/WPF/17350/mvvm-framework/viewmodels/bindablebase#run-custom-code-when-property-value-changed-1)
It literally allows you to create custom code around the "changing" behavior.

So I am curious to find out why the OnFirstNameChanging and OnFirstNameChanged methods were generated and if you intend to implement this feature?

**Comment by Sergio0694** [comment]
It seems to essentially be an equivalent feature, the difference is that here the method is automatically invoked by the generated code in a more efficient manner, as you don't have to create a delegate to pass as an argument. You just implement the `OnPropertyChanged` and `OnPropertyChanging` methods (either of them, or both, or none), and if so the generated code will invoke them automatically when needed. I've detailed this in my blog post as well, you can find it [here](https://devblogs.microsoft.com/ifdef-windows/announcing-net-community-toolkit-v8-0-0-preview-3/). Note that the generated methods are partial and empty, so if you don't implement them yourself they'll just go away. Hope this clears things up! 🙂

**Comment by mkalinski93** [comment]
That sounds great! Thank you for your detailed answer :)
