### ISSUE TITLE
Sample App->Helpers->MVVM Toolkit: Documentation shows "High Performance Package" doc, not MVVM doc

### ISSUE THREAD

**Issue by PaulaScholz** [CommunityToolkit/dotnet#21]
## Describe the bug

In the Sample App ver 7.1.0, the MVVM Toolkit documentation contents is the "High Performance package" documentation. The MVVM Toolkit documentation is not displayed.

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:  

## Steps to Reproduce

In the Sample App, select Helpers and then MVVM Toolkit.  Observe that the documentation displayed is not for the MVVM Toolkit, but is for the High Performance package.

- [ ] Can this be reproduced in the Sample App? (Either in a sample as-is or with new XAML pasted in the editor.) If so, please provide custom XAML or steps to reproduce. If not, let us know why it can't be reproduced (e.g. more complex setup, environment, dependencies, etc...)

Yes.

1. Given the following environment: The Sample App from the Windows Store on Windows 11
2. Select the Helpers choice on the top toolbar.
3. On the Developers row, click the MVVM Toolkit choice
5. Observe that the documentation displayed is not for the MVVM Toolkit, but instead is for the High Performance Package

## Expected behavior

I expected the MVVM Toolkit documentation.

## Environment

NuGet Package(s): 

Package Version(s):

Windows 10 Build Number:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Insider Build ({build_number})
-[X] WINDOWS 11

App min and target version:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Insider Build ({build_number})

Device form factor:

- [[X](url) ] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio version:

- [ ] 2017 (15.{minor_version})
- [ ] 2019 (16.{minor_version})
- [ ] 2022 (17.{minor_version})

## Additional context

<!-- Add any other context about the problem here. --
<img width="930" alt="SampleApp-Helpers-MVVM_Toolkit_docWrong" src="https://user-images.githubusercontent.com/45177251/138613822-70ec45e2-2ee5-4398-838e-a345e290a765.png">
>
<img width="930" alt="SampleApp-Version" src="https://user-images.githubusercontent.com/45177251/138613831-9723eccc-81b5-449f-b2bb-f99bfe4ccff2.png">

**Comment by Sergio0694** [comment]
Closing this, as libraries from the .NET Community Toolkit are now no longer in the sample app. Thanks! 😄
