### ISSUE TITLE
[Feature] AndAlsoExecute(NameOf(Method)) on PropertyChanged.

### ISSUE THREAD

**Issue by fatscally** [CommunityToolkit/dotnet#216]
In this situation I have a DatePicker control on a XAML form bound to a property in the viewmodel: 
`[ObservableProperty]`  
`public DateTime bookingDate;`

I am hoping to introduce another annotation that will allow me to call a function after the property is updated.
`[AndAlsoExecute(NameOf(GetBookings)]`

I created a Q. about it over on StackOverflow:
https://stackoverflow.com/questions/71857854/how-to-call-a-method-after-a-property-update/71858036#71858036

As a work around I am adding this to the viewmodel.

```
protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            `base.OnPropertyChanged(e);

            if (e.PropertyName == nameof(BookingDate))
            {
                DisplayBookings();
            }
        }
```

**Comment by michael-hawker** [comment]
You could use the new partial generated methods for this scenario, see [preview blog here](https://devblogs.microsoft.com/ifdef-windows/announcing-net-community-toolkit-v8-0-0-preview-3/#partial-property-changed-methods):

```cs
[ObservableProperty]
private DateTime _bookingDate;

partial void OnBookingDateChanged(DateTime bookingDate)
{
    DisplayBookings();
}
```

**Comment by fatscally** [comment]
I was using something similar but yours is a level tidier.

```
        protected override void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            base.OnPropertyChanged(e);

            if (e.PropertyName == nameof(BookingDate))
            {
                DisplayBookings();
            }
        }
```

**Comment by Sergio0694** [comment]
Closing this, as the approach suggested by @michael-hawker is the correct one for this scenario 🙂
