### ISSUE TITLE
[Feature] AsyncRelayCommand.Execute should catch and raise an Exception if possible

### ISSUE THREAD

**Issue by juwens** [CommunityToolkit/dotnet#22]
It easily happens that you use the AsyncRelayCommand somewhere as ICommand, if i call the ICommand.Execute i get no Exception, even if the async Method throws an Exception.

I know it's nearly impossible (only via AsyncEx.Run), to synchronous call an async method wait for it and raise the Exception in sync context.

### Alternative:

AsyncRelayCommand should have a public static Event where i can register an EventHandler for these kind of Exceptions.

So Execute would look like this:

```
public async void Execute()
{
    try
    {
        await ExecuteAsync()
    }
    catch(Exception e)
    {
        ExceptionInSyncExecute?.Invoke(this, new UnhandledExceptionEventArgs(e));
    }
}
```

**Comment by timdinhdotcom** [comment]
We are using IAsyncCommand from Xamarin Community Toolkit, which has a parameter for `onException` action. It basically call the action whenever an exception occurred, which is very handy.

We are hoping to use `CommunityToolkit.Mvvm.Input.ICommandAttribute` instead to reduce our coding effort. Would be nice if it also support onException action too.

Suggest usage would be 
```
[ICommand(onException = SomeAction)]
private async Task MyCommand() {
    // code
}
```

**Comment by Sergio0694** [comment]
Closing this, as exceptions can now be configured to be rethrown, via the new option added in the PR linked above.
