### ISSUE TITLE
Visual Studio Designer report "invalid markup" when View-Model class derived from ObservableObject

### ISSUE THREAD

**Issue by zvilius** [CommunityToolkit/dotnet#221]
### Describe the bug

Developing a WPF desktop app for .NET Framework 4.8, I find that when I derive my View-Model class from ObservableObject, the Visual Studio 2022 Designer says "invalid markup".

The reported error is:
Error	XDG0047	The specified value cannot be assigned. The following type was expected: "Object".	foo	C:\XXX\foo\MainWindow.xaml	11	

Line 11 in MainWindow.xaml is:
`<c:ViewModel x:Key="vm" />`

The ViewModel class is declared as:
```
    internal class ViewModel : ObservableObject
    {
        public SomeStruct SomeProperty {
            get => this.some_property;
            private set => SetProperty(ref this.some_property, value);
        }
    .. etc ..

```

### Steps to reproduce

```text
.NET Framework 4.8
Visual Studio 2022
WPF App for .NET Framework

See other details above.
```

### Expected behavior

Visual Studio Designer should be able to preview my UI.

### IDE and version

VS 2022

### IDE version

Microsoft Visual Studio Professional 2022 (64-bit) - Current Version 17.1.4

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

7.1.2

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
This seems to be an issue relates to the designer and not tied to the MVVM Toolkit per se, so resolving this as external.
