### ISSUE TITLE
The Source generator couldn't find the correct path

### ISSUE THREAD

**Issue by pictos** [CommunityToolkit/dotnet#225]
### Describe the bug

When I try to debug my project that uses the MVVM Source Generator the project fails with 

```
2>CSC : error CS0016: Could not write to output file 'C:\Git\behavior_impl\samples\CommunityToolkit.Maui.Sample\obj\GeneratedFiles\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\CommunityToolkit.Maui.Sample.ViewModels.Converters.IsNotNullConverterViewModel.cs' -- 'Could not find a part of the path 'C:\Git\behavior_impl\samples\CommunityToolkit.Maui.Sample\obj\GeneratedFiles\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\CommunityToolkit.Maui.Sample.ViewModels.Converters.IsNotNullConverterViewModel.cs'.'
```

In fact the project builds when I use the command line. So I'm not sure if this is an issue here, or in the Roslyn or in Visual Studio.

### Steps to reproduce

1. Fork this [branch](https://github.com/CommunityToolkit/Maui/tree/pj/behavior-impl);
2. Run the sample app using the `Windows` as target
3. See the `Output` Window.

### Expected behavior

The project builds and launchs

### IDE and version

VS 2022 Preview

### IDE version

Version 17.2.0 Preview 4.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0-preview3

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment]
Mmh that's weird, especially given you're saying building from the command line works 🤔

@sharwell would you have any ideas here?
Just wondering if this might be related to Roslyn/VS as suggested, rather than the NCT?

**Comment by pictos** [comment]
@Sergio0694 looks like it's something related to the `file path`, after following [this doc](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd#enable-long-paths-in-windows-10-version-1607-and-later) I couldn't reproduce the issue.

Maybe the toolkit should use an acronym to reduce the size of `CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator`?

**Comment by Nirmal4G** [comment]
I think I've suggested something like this before. I can't remember where. Change the `hintName` to more unique but less characters and no path like format.

Essentially the idea is to turn this `C:\Git\behavior_impl\samples\CommunityToolkit.Maui.Sample\obj\GeneratedFiles\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\CommunityToolkit.Maui.Sample.ViewModels.Converters.IsNotNullConverterViewModel.cs` to this `C:\Git\behavior_impl\samples\CommunityToolkit.Maui.Sample\obj\ViewModels\Converters\IsNotNullConverterViewModel.g.cs` or `C:\Git\behavior_impl\samples\CommunityToolkit.Maui.Sample\obj\ViewModels.Converters.IsNotNullConverterViewModel.g.cs`

This way we can get (_almost_) flat file structure. We know that XAML `.g.cs` generator does it. Why can't we follow the same? Infact, Roslyn should get all the generated code and merge them into a single file based on the source type (_if the generator extends it_) or the target type (_if the generator creates it_) it operates on.

**Comment by sharwell** [comment]
There are two ways to handle this:
1. Turn on long path support in Windows and/or the build
2. Turn _off_ the Roslyn feature that saves generated source files to disk

**Comment by Sergio0694** [comment]
> "Turn off the Roslyn feature that saves generated source files to disk"

Given that is off by default I assume this issue should be considered external and not related to the MVVM Toolkit itself, right?

**Comment by pictos** [comment]
> > "Turn off the Roslyn feature that saves generated source files to disk"
> 
> Given that is off by default I assume this issue should be considered external and not related to the MVVM Toolkit itself, right?


I'm ok with that, @Sergio0694

**Comment by Nirmal4G** [comment]
@sharwell Generating files on disk would be helpful in debugging both the generator with the consuming project or is there support to debug generated files in memory?
