### ISSUE TITLE
Option to opt-out of auto-validating properties with validation attributes and perform validation when requested

### ISSUE THREAD

**Issue by cesarchefinho** [CommunityToolkit/dotnet#229]
### Describe the bug

use [AlsoBroadcastChange(false)]

to generate code bellow

get => property;
set =>  SetValue (ref property, value, false);

instead of 

get => property;
set =>  SetValue (ref property, value, true);

### Steps to reproduce

```text
use source generators in ViewModel to a form that validation is controlled by Command that call ValidateAll()
```

### Expected behavior

create property dat dont validate on setter

### IDE and version

VS 2022

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8 preview 3

### Help us help you

No, just wanted to report this

**Comment by michael-hawker** [comment]
I'm confused about the scenario here, if you want to not broadcast, wouldn't you just not add the `[AlsoBroadcastChange]` attribute?

I would assume that there'd be `[AlsoBroadcastChangeFor]` like `[AlsoNotifyChangeFor]` that takes a different property to broadcast (though if that was set to broadcast and was targeted with an `AlsoNotifyChangeFor` then it'd be the same?).

I like the idea of triggering validation on other properties though, but then wouldn't `AlsoNotifyChangeFor` handle that scenario too?

Trying to piece it all together. Would be handy to have a doc that lists all the attributes, what they do, and how their various modes can work (and work in combination)... 😉

**Comment by cesarchefinho** [comment]
> I'm confused about the scenario here, if you want to not broadcast, wouldn't you just not add the [AlsoBroadcastChange] attribute?

No. It is not the same, because AlsoBroadcastChange generate the code 

get => property;
set => SetValue (ref property, value); // (this is the same as SetValue (ref property, value, **true**);)

and I want the code bellow

get => property;
set => SetValue (ref property, value, **false**);

**Comment by Sergio0694** [comment]
@cesarchefinho 

> "AlsoBroadcastChange generate the code
>
> ```csharp
>get => property;
>set => SetValue (ref property, value); // (this is the same as SetValue (ref property, value, true);)
> ```

That's now the code that `[AlsoBroadcastChange]` generates 🙂

**Comment by cesarchefinho** [comment]
> @cesarchefinho
> 
> > "AlsoBroadcastChange generate the code
> > ```cs
> > get => property;
> > set => SetValue (ref property, value); // (this is the same as SetValue (ref property, value, true);)
> > ```
> 
> That's not the code that `[AlsoBroadcastChange]` generates 🙂
![AlsoBroadcast](https://user-images.githubusercontent.com/55895254/168606750-f6bd3d30-293d-4320-8c98-b6312fc1d23f.png)

**Comment by Sergio0694** [comment]
That's just to make the docs simpler, the point is this attribute will cause the property change to be broadcast. If you _don't_ want to have the change be broadcast, then... Don't use `[AlsoBroadcastChange]`? I'm confused as to what the issue is here 🤔

**Comment by cesarchefinho** [comment]
I believe that It's not true. The docs apparently are correct because It causes validation. Correct me if I am wrong

I want that it change the property but not cause valuation, and broadcast that property changes, only not validate it

I want to manually call validate property when I want

**Comment by Sergio0694** [comment]
Yes, I understand that, I'm saying that the `[AlsoBroadcastChange]` attribute has nothing to do with this.
The validation is done because right now that's enable by default whenever you have an observable property that has some validation attributes, and there's no way (currently) to opt-out from that. That is completely unrelated from whether or not you annotate the property as broadcasting changes or not. This is why I'm saying the ask here seems to just be to have control over when the validation is performed, and not anything to do with broadcasting on its own, as that's unrelated 🙂

**Comment by michael-hawker** [comment]
The details in the issue itself need some cleaning up, but have changed the title of this issue to mask the request.

**Comment by cesarchefinho** [comment]
> Yes, I understand that, I'm saying that the `[AlsoBroadcastChange]` attribute has nothing to do with this. The validation is done because right now that's enable by default whenever you have an observable property that has some validation attributes, and there's no way (currently) to opt-out from that. That is completely unrelated from whether or not you annotate the property as broadcasting changes or not. This is why I'm saying the ask here seems to just be to have control over when the validation is performed, and not anything to do with broadcasting on its own, as that's unrelated 🙂

This is not true.

If I don't user attribute observableproperty attribute and code the property with

get => property;
set => SetValue (ref property, value,  false);

The validation won't occur and the changes are brodcasted.

I only want that mvvm source generators attribute can make the same thing.

Maybe with [AlsoNotValidateProperty] attribute that sergio0694 proposed.
