### ISSUE TITLE
How add sorted item in ObservableGroupedCollection

### ISSUE THREAD

**Issue by Hot-Gun** [CommunityToolkit/dotnet#23]
Hello!
I have an example from the WindowsCommunityToolkit ObservableGroup (https://github.com/windows-toolkit/WindowsCommunityToolkit/tree/master/Microsoft.Toolkit.Uwp.SampleApp/SamplePages/ObservableGroup).
Everything works. But all new groups and items are always added to the end. How can I add a new item (and a new group with a new item) in alphabetical order?
I tried: _contactsSource.Add(new ObservableGroup<string, Person>(groupName, new[] { newContact }));
And tried: ObservableGroupedCollectionExtensions.AddItem(_contactsSource, groupName, newContact);
But it did not help.

![sort](https://user-images.githubusercontent.com/79420377/108636757-2a207f80-74a9-11eb-981b-fb251f1d0c0b.png)

**Comment by Sergio0694** [comment]
Closing this, as #168 did add new APIs to insert items in the right (sorted) position 🙂
