### ISSUE TITLE
ObservableValidatorValidateAllPropertiesGenerator fails with partial classes

### ISSUE THREAD

**Issue by canton7** [CommunityToolkit/dotnet#235]
### Describe the bug

ObservableValidatorValidateAllPropertiesGenerator falls into the classic trap of trying to generate a hint name without taking the necessary steps to make sure that it is unique within the project.

Here, it fails with partial classes. If you create a partial class with 2 or more parts inheriting from `ObservableValidator`, the SG crashes with:

> CSC : warning CS8785: Generator 'ObservableValidatorValidateAllPropertiesGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName 'Namespace.ClassName.cs' of the added source file must be unique within a generator.

### Regression

No.

### Steps to reproduce

```cs
public partial class Test : ObservableValidator
{
}

public partial class Test
{
}
```

Run a build. Observe the error

> CSC : warning CS8785: Generator 'ObservableValidatorValidateAllPropertiesGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The hintName '.Test.cs' of the added source file must be unique within a generator.

### Expected behavior

The SG does not crash.

### IDE and version

VS 2022

### IDE version

17.1.5

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

7.1.2

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
Hey there! 👋
You're using 7.1.2, which is the old version considered as preview, and admittedly quite buggy with respect with source generators. That version doesn't even use incremental generators, and it will just be marked as deprecated once 8.0.0 is released. Please try out with `CommunityToolkit.Mvvm 8.0.0-Preview`, I'm pretty sure that issue is fixed there already 🙂

**Comment by canton7** [comment]
Sure! Where do I find that preview? It's not on nuget.

**Comment by Sergio0694** [comment]
Mmh actually I can repro this on `main`. This is weird, I was sure I had fixed this same issue already, maybe it was in one of the other generators and I missed this one. Thank you for the report and the minimal repro! 😄

> "Sure! Where do I find that preview? It's not on nuget."

It should be on NuGet, you need to enable prerelease packages though.
Also note, it's using a separate package name: it's `CommunityToolkit.Mvvm`, not `Microsoft.Toolkit.Mvvm`.

**Comment by Sergio0694** [comment]
Ah, I see now, I did fix this, but only in the messenger generator: https://github.com/CommunityToolkit/dotnet/pull/120.
I'll just move that code to an extension and use it here too, thankfully the fix is quite easy and also efficient 😄

**Comment by canton7** [comment]
Is there any way to tell the SG not to get involved with arbitrary partial classes that inherit from `ObservableObject`/`ObservableValidator`, even if they don't contain any MVVM toolkit-specific attributes? 

That would let me work around this issue for now.

**Comment by Sergio0694** [comment]
Nope, that's not possible. Though if you need to get unblocked, you should be able to just add our preview feed (https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-MainLatest/nuget/v3/index.json), and then just use the preview package from that PR with the fix (should be `CommunityToolkit.Mvvm.8.0.0-build.146.g3e33a8eec1`). Let me know if that works for you!
