### ISSUE TITLE
Mvvm bindingvextensions

### ISSUE THREAD

**Issue by cesarchefinho** [CommunityToolkit/dotnet#244]
### Overview

Extensions to MVVM and to XAML Binding mechanism to Bind View model to control properties

Works on uwp, uno and winui3

Works with all custom attributes on fields and [ObservabeProperty] including other than valudators

Bind string index property of fielmodel this[collumnname] to description and display error messages

Works with inherited view models using [ObservabeProperty] and othercustom  attributes in base classes

See all in 

https://github.com/cesarchefinho/MVVMBindingExtensions

I propose that these extensions to be included in mvvm toolkit

### API breakdown

See https://github.com/cesarchefinho/MVVMBindingExtensions

### Usage example

See https://github.com/cesarchefinho/MVVMBindingExtensions

### Breaking change?

No

### Alternatives

Write a lot of boring xaml markup code and waste a lot of time

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment]
Hey there! This proposal is not a good fit for the MVVM Toolkit (or the .NET Community Toolkit in general) as it's platform-specific. All APIs in this project are meant to work on all .NET without a dependency on any specific framework or runtime. As such, this is not something that could realistically be added to the MVVM Toolkit.
