### ISSUE TITLE
Support .NET 4.8 please?

### ISSUE THREAD

**Issue by taori** [CommunityToolkit/dotnet#252]
### Overview

I am trying to add CommunityToolkit.MVVM to
https://github.com/taori/RestClientVS/

However because it is a VSIX project it is run with net4.8.

After adding the references the project does not build anymore because 2 other projects are updated (BCL for example). Would you consider adding net4.8?

### API breakdown

No breakdown.

### Usage example

No API change

### Breaking change?

I'm not sure

### Alternatives

I suppose binding redirects would work too?

### Help us help you

Yes, but only if others can assist

**Comment by taori** [comment]
After further investigation i found out that whatever is going wrong here is definitely a quirk within the context of binding redirects within vsix projects. Therefore adding support for 4.8 just so vsix has less issues would be a too niche reason. Sorry for wasting your time

**Comment by Sergio0694** [comment]
Absolutely not a problem! Hope you'll manage to find a way to get that to work! 🙂
