### ISSUE TITLE
Adding ObservableProperty to a ViewModel cause class definitions error

### ISSUE THREAD

**Issue by Licantrop0** [CommunityToolkit/dotnet#27]
## Description
I created a simple WinUI 3.0 app using `Blank App, Packaged (WinUI 3 in Desktop)` template.
I added Microsoft.Toolkit.Mvvm and tried to use ObservableProperty source generators.

With these lines in my `MainViewModel.cs` file:
```
[ObservableProperty]
private string title = "My title";
```
I get this error:

`1>C:\Users\lucaspol\source\MyAppsMezzo\Microsoft.Toolkit.Mvvm.SourceGenerators\Microsoft.Toolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator\MyAppsMezzo.ViewModels.MainViewModel.cs(7,18,7,31): error CS0101: The namespace 'MyAppsMezzo.ViewModels' already contains a definition for 'MainViewModel'`

If I remove the previous lines, I don't get any error.

@Sergio0694 please take a look.

## Steps to Reproduce
attaching sample project: [MyAppsMezzo.zip](https://github.com/CommunityToolkit/WindowsCommunityToolkit/files/7521088/MyAppsMezzo.zip)

## Environment

NuGet Package(s): 
[see attached sample project]

Windows 11 Build Number: 22489.1000

App min and target version:
**Min**: May 2020 Update (19041)
**Target**: 10.0.22000.0

Device form factor:
- [x] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio version:
- [x] 2022 (17.1.0)

**Comment by Sergio0694** [comment]
You just forgot to add `partial` to your class, that is required to be able to define it in multiple places 😊
See the docs here: [partial classes and methods](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods).

We'll make sure to call this out once we update our docs to include the new source generators, for sure!

**Comment by Licantrop0** [comment]
Thank you @Sergio0694 !
It works now, it was not very clear at first that I had to add the partial modifiers when using the source generators.
