### ISSUE TITLE
Array Merge extension

### ISSUE THREAD

**Issue by adamradocz** [CommunityToolkit/dotnet#270]
### Overview

A quick and fast way to merge two arrays together.

### API breakdown

```csharp
public static class ArrayExtensions
{
    /// <summary>
    /// Returns a concatenated array of the two arrays.
    /// </summary>
    /// <typeparam name="T">The element type of the array.</typeparam>
    /// <param name="first">The source array.</param>
    /// <param name="second">The array that has to be merged with the source.</param>
    /// <returns></returns>
    public static T[] Merge<T>(this T[] first, T[] second)
    {
        var concatenatedArray = new T[first.Length + second.Length];
        Array.Copy(first, 0, concatenatedArray, 0, first.Length);
        Array.Copy(second, 0, concatenatedArray, first.Length, second.Length);
        return concatenatedArray;
    }
}
```

### Usage example

```csharp
    [Fact]
    public void Merge_TwoByteArray_ReceiveOneMergerdArray()
    {
        // Arrange
        var first = new byte[] { 0, 1 };
        var second = new byte[] { 2, 3, 4 };
        var expectedArray = new byte[] { 0, 1, 2, 3, 4 };

        // Act
        var mergedArray = first.Merge(second);

        // Assert
        Assert.Equal(expectedArray, mergedArray);
    }
```

### Breaking change?

No

### Alternatives

```csharp
int[] arr1 = { 1, 2, 3 };
int[] arr2 = { 4, 5, 6 };
var mergedArray = arr1.Concat(arr2).ToArray();
```

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by Sergio0694** [comment]
I don't think this API is needed. You can do the same with `Concat(array).ToArray()`, and the `Concat` enumerable already has the same optimization internally, where if both input sequences have a count (which is the case here), it'll allocate an array of the right length and then just do a copy operation of the two input chunks like the implementation you're suggesting. The only difference would be the extra enumerator allocation, but I don't think that's worth an extra API given that if you're working with arrays and combining them like in this case, then you likely have bigger problems with respect to memory allocations anyway 🙂

**Comment by adamradocz** [comment]
Fair enough.
