### ISSUE TITLE
MVVM Source Generator breaks for top-level classes

### ISSUE THREAD

**Issue by heshuimu** [CommunityToolkit/dotnet#271]
### Describe the bug

In Unity, it's not uncommon that classes are not placed into a namespace. When I do so, the source generator will still append a dot in front of the class name. 

```cs
public partial class MyViewModel : ObservableObject
{
	[ObservableProperty]
	private float test;
}
```

> Microsoft.Toolkit.Mvvm.SourceGenerators/Microsoft.Toolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator/.MyViewModel.cs(5,10): error CS1001: Identifier expected

> Microsoft.Toolkit.Mvvm.SourceGenerators/Microsoft.Toolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator/.MyViewModel.cs(15,20): error CS0103: The name 'test' does not exist in the current context

> Microsoft.Toolkit.Mvvm.SourceGenerators/Microsoft.Toolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator/.MyViewModel.cs(18,96): error CS0103: The name 'test' does not exist in the current context

> Microsoft.Toolkit.Mvvm.SourceGenerators/Microsoft.Toolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator/.MyViewModel.cs(20,21): error CS0103: The name 'OnPropertyChanging' does not exist in the current context

> Microsoft.Toolkit.Mvvm.SourceGenerators/Microsoft.Toolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator/.MyViewModel.cs(21,21): error CS0103: The name 'test' does not exist in the current context

> Microsoft.Toolkit.Mvvm.SourceGenerators/Microsoft.Toolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator/.MyViewModel.cs(22,21): error CS0103: The name 'OnPropertyChanged' does not exist in the current context

Things work fine if I put the class into a namespace:
```cs
namespace A
{
	public partial class MyViewModel : ObservableObject
	{
		[ObservableProperty]
		private float test;
	}
}

```

### Steps to reproduce

```text
Create a top-level class:


public partial class MyViewModel : ObservableObject
{
	[ObservableProperty]
	private float test;
}
```

### Expected behavior

Build succeed with errors

### Screenshots

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/7824592/170566522-f4056424-26fb-452e-b3ec-82c369007edc.png">

### IDE and version

Other

### IDE version

Visual Studio Code 1.67.2 + Unity 2021.3

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

7.1.2

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment]
Found it: for reference, the fix is just [this one], I'll port that to the MVVM Toolkit as well.
