### ISSUE TITLE
MVVM Toolkit - ICommand source generator - Nullable reference types

### ISSUE THREAD

**Issue by mikechristiansenvae** [CommunityToolkit/dotnet#280]
### Describe the bug

The `ICommandAttribute` source generator does not understand nullable reference types.  This causes it to generate an `IRelayCommand` that does not accept null values, even if the method's parameter is a nullable reference type.

For example, this method:

```
[ICommand]
private void SetValue(string? value)
{
}
```

Should generate:

```
public IRelayCommand<string?> SetValueCommand { get; }
```

It actually generates:

```
public IRelayCommand<string> SetValueCommand { get; }
```

### Steps to reproduce

```text
public string? Value { get; private set; }

[ICommand]
private void SetValue(string? value) => this.CurrentValue = value;
```

### Expected behavior

I expected the generated command to be a `IRelayCommand<string?>`.  Instead, it's `IRelayCommand<string>`

Additionally, since its a nullable type, I expect the implementation of `IRelayCommand` to accept `null` values.

### IDE and version

Rider

### IDE version

Rider 2022.1.1 (#RD-221.5591.20)

### Nuget packages

- [X] CommunityToolkit.Common
- [X] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

7.1.2

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
7.1.2 is outdated and marked as preview. Pretty sure this has been fixed, could you try with `CommunityToolkit 8.0.0-Preview3` and see if that fixes the issue? Thanks! 🙂

**Comment by mikechristiansenvae** [comment]
@Sergio0694 - I cannot use any newer version than `7.1.2` due to issue #246.  

I just tried `8.0.0-preview3` and got the errors seen in issue #246 - so I couldn't even compile.

**Comment by Sergio0694** [comment]
The fix for that is not in a new Preview yet, but you can use a preview package from our nightly feed 😄

Use this feed:

https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-MainLatest/nuget/v3/index.json
