### ISSUE TITLE
AlsoNotifyChangeFor not found in 8.0.0. Preview (works OK in 7.1.0)

### ISSUE THREAD

**Issue by ExactImage** [CommunityToolkit/dotnet#297]
### Describe the bug

The [**AlsoNotifyChangeFor**] attribute seems broken on 8.0.0-preview 4 but works on 7.1.2 and 8.0.0-preview 3

I didn't see this on the breaking change list.

```
        [ObservableProperty]
        [AlsoNotifyChangeFor(nameof(IsNetworkDeployedText))]
        bool isNetworkDeployed;
        public string IsNetworkDeployedText => IsNetworkDeployed ? "Yes" : "No";
```

### Regression

8.0.0 preview 3

### Steps to reproduce

```text
Create a new dotnet 6 WPF app, create a class with the above variables.   Add nuget packages for 8.0.0 preview 3 (see it works) and then update to 8.0.0-preview4 and see it break;
```

### Expected behavior

Since I didn't see this on breaking changes I expected it to work as per 7.1.2 and 8.0.0 preview 3.

### Screenshots

8.0.0 preview 3
![image](https://user-images.githubusercontent.com/70608963/172458683-bc56cc9a-ed36-497a-b92f-0529bb1cfe2a.png)

8.0.0 preview 4
![image](https://user-images.githubusercontent.com/70608963/172458814-86fd9782-1f22-4f78-aedd-0ecd37178312.png)

### IDE and version

VS 2022 Preview

### IDE version

17.2.2 and 17.3.0 Preview 1.1

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0 preview 4

### Help us help you

No, just wanted to report this

**Comment by ExactImage** [comment]
Oops.... well I read that line and didn't associate it with this since it wasn't specific about renaming [AlsoNotifyChangeFor] to [NotifyCanExcecuteChangedFor].   To me, the 'can excecute' in NotififyCanExcecuteChangeFor was likely to be something slightly different.

However, thanks for the quick response!

**Comment by bryancass** [comment]
Note that change was   [AlsoNotifyChangeFor] ---> [NotifyPropertyChangedFor]

Not [NotifyCanExecuteChangeFor].
