### ISSUE TITLE
RelayCommand attribute: Static methods

### ISSUE THREAD

**Issue by mikechristiansenvae** [CommunityToolkit/dotnet#303]
### Describe the bug

If the `RelayCommand` attribute is applied to a static method, an instance method is generated instead of a static method.

### Steps to reproduce

```csharp
[RelayCommand]
public static async Task ShowDialogAsync()
{
    var dialogService = App.GetRequiredService<DialogService>();
    await dialogService.ShowDialog(new NewSiteDialog());
}
```

Generates the below code - note that it is not static:

```csharp
/// <summary>The backing field for <see cref="ShowDialogCommand"/>.</summary>
[global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.RelayCommandGenerator", "8.0.0.0")]
private global::CommunityToolkit.Mvvm.Input.AsyncRelayCommand? showDialogCommand;
/// <summary>Gets an <see cref="global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand"/> instance wrapping <see cref="ShowDialogAsync"/>.</summary>
[global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.RelayCommandGenerator", "8.0.0.0")]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public global::CommunityToolkit.Mvvm.Input.IAsyncRelayCommand ShowDialogCommand => showDialogCommand ??= new global::CommunityToolkit.Mvvm.Input.AsyncRelayCommand(new global::System.Func<global::System.Threading.Tasks.Task>(ShowDialogAsync));
```

### Expected behavior

I'd expect the resulting generated command to be a static property

### IDE and version

Rider

### IDE version

Rider 2022.1.2; RD-221.5787.36

### Nuget packages

- [ ] CommunityToolkit.Common
- [X] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0-preview4

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
This is by design - commands are meant to be instances on objects, so that they can be targeted by bindings.

**Comment by mikechristiansenvae** [comment]
@Sergio0694 - [You can bind to static properties from XAML](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/getting-started/whats-new?redirectedfrom=MSDN&view=netframeworkdesktop-4.8#static_properties).

**Comment by mikechristiansenvae** [comment]
Additionally, you could do this:

```
<Button Command="{x:Static MemberType={x:Type MyType}, MemberName=MyCommand}" />
```
