### ISSUE TITLE
MVVM AlsoNotifyCanExecuteFor(nameof(MethodCommand))

### ISSUE THREAD

**Issue by maikoly1** [CommunityToolkit/dotnet#305]
### Describe the bug

Quick help to understand the reason why the above is not firing. Tried putting break point inside the method but it seems the code inside is to invoked.

### Steps to reproduce

```text
N/A
```

### Expected behavior

The attribute AlsoNotifyCanExecuteFor to fire the command and Notify the Properties.

### IDE and version

VS 2022

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0-preview1

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
I'm not sure I understand what the issue is exactly. Can you share a minimal repro that illustrates the problem? The attribute should be working fine a far as I know 🤔

**Comment by maikoly1** [comment]
Thank you for your Quick Reply.

[ObservableProperty]
[AlsoNotifyCanExecuteFor(nameof(ChangeCommand))]
 decimal c;

[ICommand]
 void Change()
 {
           //Code
 }

On change the prop should invoke the ChangeCommand but in my case it doesn't. 😯

**Comment by Sergio0694** [comment]
Mmmh that's weird. Just to be sure this has not been fixed already, can you try with 8.0.0-Preview4? The version you're using is quite old now 🙂

**Comment by maikoly1** [comment]
> Mmmh that's weird. Just to be sure this has not been fixed already, can you try with 8.0.0-Preview4? The version you're using is quite old now 🙂

I already tried that with 8.0.0-preview3. Still no change.

**Comment by Sergio0694** [comment]
I cannot reproduce the issue here. I used this code, from your message:

```csharp
public partial class ModelWithDecimalPropertyNotifyingCommandCanExecute : ObservableObject
{
    [ObservableProperty]
    [NotifyCanExecuteChangedFor(nameof(ChangeCommand))]
    decimal c;

    [RelayCommand]
    void Change()
    {
    }
}
```

This results in the expected code to be generated:

```csharp
// <auto-generated/>
#pragma warning disable
#nullable enable
namespace CommunityToolkit.Mvvm.UnitTests
{
    partial class Test_ObservablePropertyAttribute
    {
        partial class ModelWithDecimalPropertyNotifyingCommandCanExecute
        {
            /// <inheritdoc cref="c"/>
            [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.0.0.0")]
            [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
            public decimal C
            {
                get => c;
                set
                {
                    if (!global::System.Collections.Generic.EqualityComparer<decimal>.Default.Equals(c, value))
                    {
                        OnCChanging(value);
                        OnPropertyChanging(global::CommunityToolkit.Mvvm.ComponentModel.__Internals.__KnownINotifyPropertyChangingArgs.C);
                        c = value;
                        OnCChanged(value);
                        OnPropertyChanged(global::CommunityToolkit.Mvvm.ComponentModel.__Internals.__KnownINotifyPropertyChangedArgs.C);
                        ChangeCommand.NotifyCanExecuteChanged();
                    }
                }
            }

            /// <summary>Executes the logic for when <see cref="C"/> is changing.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.0.0.0")]
            partial void OnCChanging(decimal value);
            /// <summary>Executes the logic for when <see cref="C"/> just changed.</summary>
            [global::System.CodeDom.Compiler.GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.0.0.0")]
            partial void OnCChanged(decimal value);
        }
    }
}
```

And in fact, this works just fine:

```csharp
ModelWithDecimalPropertyNotifyingCommandCanExecute model = new();

List<(object Sender, PropertyChangedEventArgs Args)> propertyChangedArgs = new();
List<(object Sender, EventArgs Args)> canExecuteArgs = new();

model.C = 3.14m;

Assert.AreEqual(propertyChangedArgs.Count, 1);
Assert.AreEqual(propertyChangedArgs[0].Sender, model);
Assert.AreSame(propertyChangedArgs[0].Args.PropertyName, nameof(model.C));

Assert.AreEqual(canExecuteArgs.Count, 1);
Assert.AreEqual(canExecuteArgs[0].Sender, model.ChangeCommand);
Assert.AreSame(canExecuteArgs[0].Args, EventArgs.Empty);
```

There are no issues with the MVVM Toolkit here that I can see.
Are you sure your code is actually expressing what you want to do?
For instance, you're notifying a command but there's no "CanExecute" method, so that's pretty much doing nothing anyway.

**Comment by Sergio0694** [comment]
What method were you expecting it to invoke?

**Comment by maikoly1** [comment]
[RelayCommand]
        void Change()
        {
            Console.WriteLine("Am Invoked");
           // This never gets called
        }

**Comment by Sergio0694** [comment]
That's not how this is supposed to work at all. Like the name suggests, `NotifyCanExecuteChangedFor(nameof(ChangeCommand))` only notifies that the command might have changed its `CanExecute` property, ie. it causes its `CanExecuteChanged` event to be raised. That's it. There's no code here that should cause that command to be invoked, that's completely separate 🙂

**Comment by maikoly1** [comment]
So By changing the property value of  c should I expect the code inside change command invoked or it only registers it for `CanExecute` ?. Thank you for your response btw.

**Comment by Sergio0694** [comment]
> "So By changing the property value of c should I expect the code inside change command invoked or it only registers it for"

As I said, `NotifyCanExecuteChangedFor` simply invokes `NotifyCanExecuteChanged` on that command, which caues it to raise its `CanExecuteChanged` event. That's it. Nothing more, nothing less. No code is explicitly being executed, just the event raised.

If you want to execute that code when the property changes, you might not need a command at all. Just do:

```csharp
[ObservableProperty]
decimal c;

partial void OnCChanged(decimal value)
{
    // Code here
}
```

This will automatically be invoked whenever the value of `c` changes.

**Comment by maikoly1** [comment]
Thank you! 👍 Now I Understand. And thanks again for your quick response.
