### ISSUE TITLE
[ObservableProperty] broken with 8.0.0-preview4

### ISSUE THREAD

**Issue by Insire** [CommunityToolkit/dotnet#306]
### Describe the bug

[ObservableProperty] does not generate the expected property anymore. [see](https://github.com/Insire/CommunityToolkit.Mvvm.Bugs/blob/main/WpfLibrary1/ViewModel.cs)
Error
```Severity	Code	Description	Project	File	Line	Suppression State
Error	MVVMTK0024	The field WpfLibrary1.ViewModel._property cannot be used to generate an observable property, as its name or type would cause conflicts with other generated members	WpfLibrary1	E:\Code\WpfApp1\WpfLibrary1\ViewModel.cs	8	
```

### Regression

8.0.0-preview3

### Steps to reproduce

[see](https://github.com/Insire/CommunityToolkit.Mvvm.Bugs/blob/main/WpfLibrary1/ViewModel.cs)

### Expected behavior

Property should be generated.

### Screenshots

![grafik](https://user-images.githubusercontent.com/11455827/173032915-02dbdd25-ffb6-48d3-b242-e8a59fe5565a.png)

### IDE and version

VS 2022

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0-preview4

### Help us help you

No, just wanted to report this

**Comment by maikoly1** [comment]
Hello,
the Generated name 'Property' of the variable object conflicts with a name in the ToolKit project. my suggestion is to use another name;

**Comment by maikoly1** [comment]
> Hello, the Generated name 'Property' of the variable object conflicts with a name in the ToolKit project. my suggestion is to use another name;

'Property' name seems reserved for the project.

**Comment by Sergio0694** [comment]
Yup, this is by design.
See explanation here: https://github.com/CommunityToolkit/dotnet/issues/245#issuecomment-1121277898.

**Comment by Insire** [comment]
Can we then atleast have a more elaborate error message or fix the link so that we get a more comprehensive description on why this is supposed to be the way it is?

**Comment by Sergio0694** [comment]
> "a more comprehensive description on why this is supposed to be the way it is"

Isn't the current message already doing that? It says:

> [Message] "The field {0}.{1} cannot be used to generate an observable property, as its name or type would cause conflicts with other generated members"
> [Description] "The fields annotated with [ObservableProperty] cannot result in a property name or have a type that would cause conflicts with other generated members."

Which is exactly what's happening here, no? 🤔

**Comment by Insire** [comment]
> Which is exactly what's happening here, no?

In my provided example, the error message is not accurate. The property doesn't conflict with other generated members, but it tries to generate a partial method which conflicts with a method that already exists on the base class.

Since this is a very special edge case, i'd like to see a specific error message mentioning the member that is the problem, instead of only having a generic one.
