### ISSUE TITLE
RelayCommand does not work on inherited methods

### ISSUE THREAD

**Issue by yosefmah** [CommunityToolkit/dotnet#307]
### Describe the bug

Attempting to annotate [RelayCommand] on inherited method results in the following error on compile:

Error MVVMTK0023 The method WpfApp1.InheritedViewModel.WpfApp1.InheritedViewModel.TestMethod() cannot be annotated with [RelayCommand], has it has multiple overloads (command methods must be unique within their containing type)

I'm not sure if this is an intended change, but it worked fine in preview3.  

### Regression

8.0.0-preview3

### Steps to reproduce

```text
1. Add method with [RelayCommand]
2. Create inherited class with the method 
3. Annotate method in inherited class with [RelayCommand]
```

### Expected behavior

I would expect the solution to compile with RelayCommand for both the base and inherited classes 

### IDE and version

VS 2022

### IDE version

17.2.3

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0-preview4

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
Could you provide an actual minimal repro?
I'm not entirely sure I understand what exact code you used 🙂

**Comment by yosefmah** [comment]
Sure @Sergio0694 , I've added this here:

https://github.com/yosefmah/relaycommand-inherited/tree/master/WpfApp1

**Comment by powerdude** [comment]
@yosefmah you don't need the attribute on both the `virtual` and overridden method. Choose one.

**Comment by yosefmah** [comment]
Thanks cliff.  Yes, it works fine with attribute only on the base class.  Apologies, it worked before in the previous preview so thought it might be a bug.

**Comment by powerdude** [comment]
I think it was an accident that it worked before.  The code has been updated to try to avoid scenarios where the generator could create duplicate symbols and also look for items defined in a class hierarchy.  Technically, it would be fine, and obviously was fine, to have a property defined in a base class and a derived class, but it could lead to other issues depending on the class reference you have.  

The previous scenario would still work because both of commands would call the virtual/overridden method, but wouldn't work in other scenarios.  So for example:

```csharp

public class Foo
{
   public int Prop {get;set;}
}

public class Bar : Foo
{
 public int Prop {get; set;}
}

var b = new Bar();
Foo f = b;

b.Prop = 3;

if (f.Prop != b.Prop)
{
    Console.Writeline( "you did something wrong");
}
```
would cause fall into the if-statement.

**Comment by Sergio0694** [comment]
Thank you @powerdude for helping triage this.
Yeah this was indeed working fine before as well, but just by accident, and not in an ideal way as just mentioned.
If you have a method being overridden, there's no need to create a new command. You can just keep reusing the same one from the base type, and it'll just automatically call the overridden instance of whatever method has been passed to it 🙂
