### ISSUE TITLE
[ICommand] attribute missing in 8.0.0-Preview4

### ISSUE THREAD

**Issue by acxsasx** [CommunityToolkit/dotnet#311]
### Describe the bug

Upgrading from preview3 to preview4 and the ICommand goes missing.

### Regression

Preview 3

### Steps to reproduce

```text
Use ICommand
        [ICommand]
        void OnSomeCommand()
        {

        }
Upgrade Nuget from preview 3 to preview 4
```

### Expected behavior

ICommand to still be available.

### IDE and version

VS 2022 Preview

### IDE version

Version 17.3.0 Preview 1.1

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0-preview4

### Help us help you

No, just wanted to report this

**Comment by binarycow** [comment]
It's been renamed to `[RelayCommand]` / `[RelayCommandAttribute]`.

[See the release notes](https://github.com/CommunityToolkit/dotnet/releases/tag/v8.0.0-preview4).
