### ISSUE TITLE
Issue with Preview 4

### ISSUE THREAD

**Issue by dmccolloughOneGas** [CommunityToolkit/dotnet#323]
I was looking at the repo below from James Montemagno as a reference to use the CommunityToolkit.MVVM with .Net Maui.

Upon reviewing his repo. I noticed that there was an update available. He references Preview 1, while using Preview 1 his sample code compiles fine.

If I upgrade it to preview 4, his code will not compile.

Errors I'm getting are "The type or namespace name ICommandAttribute could not be found"
"The type or namespace name ICommand could not be found"
"The type of namespace name AlsoNotifyChangeForAttribute could not be found"

Is there a fix for preview 4?

https://github.com/jamesmontemagno/MVVMSourceGenerators

**Comment by Sergio0694** [comment]
Duplicae of #311, the types have just been renamed (check out changelog).

**Comment by gakera** [comment]
> Duplicate of #311, the types have just been renamed (check out changelog).

@Sergio0694 
I can't see any info about AlsoNotifyChangeForAttribute in the duplicate, that seems to only apply for Commands. I have an `[ObservableProperty]` (just a string) for which I would like to (succinctly) define another property that also should be notified as changed when the original property changes. Is it not possible in the toolkit as is?

**Comment by Sergio0694** [comment]
@gakera It's definitely possible, [see docs here](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/observableproperty#notifying-dependent-properties). That linked issue doesn't mention this attribute specifically (ie. `[AlsoNotifyChangeFor]`) just because it was about the attribute names being changed in general, and not about that specific one. But the same applied to all attributes that got renamed in that release 🙂

**Comment by gakera** [comment]
> @gakera It's definitely possible, [see docs here](https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/observableproperty#notifying-dependent-properties). That linked issue doesn't mention this attribute specifically (ie. `[AlsoNotifyChangeFor]`) just because it was about the attribute names being changed in general, and not about that specific one. But the same applied to all attributes that got renamed in that release 🙂

Thanks! The "Also" seems to have been dropped from the name, but the attribute from the docs: 

```
[ObservableProperty]
[NotifyPropertyChangedFor(nameof(FullName))]
private string? name;
```
