### ISSUE TITLE
Not available from Visual Studio 2017

### ISSUE THREAD

**Issue by kenty7591** [CommunityToolkit/dotnet#325]
### Describe the bug

When I build with Visual Studio 2017,
an error message will be generated.

`Invalid static method invocation syntax: "[MSBuild]::VersionLessThan($(CurrentCompilerVersion), 4.0)". Method '[MSBuild]::VersionLessThan' not found. Static method invocation should be of the form: $([FullTypeName]::Method()), e.g. $([System.IO.Path]::Combine(`a`, `b`)).`

### Steps to reproduce

```text
On Windows 11 with Visual Studio 2017
1. Create new Wpf Project
2. Add CommunityToolkit.Mvvm, 8.0.0-preview4 via "Manage nuget packages"
3. Build the project.
```

### Expected behavior

MSBuild 15, which is used by Visual Studio 2017, does not support VersionLessThan.

### IDE and version

Other

### IDE version

VS 2017 15.9

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0-preview4

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
We're not supporting Visual Studio 2017, so you'll have to update to at least VS2019 to use this 🙂

**Comment by Sergio0694** [comment]
That said, we might accept a PR replacing that line with one compatible with VS2017, if it was functionally identical.

**Comment by kenty7591** [comment]
Thank you for your response. 
The supported version is understood.

I am not free to update Visual Studio at my workplace:sob:
