### ISSUE TITLE
Ioc can load configuration from config file

### ISSUE THREAD

**Issue by soroshsabz** [CommunityToolkit/dotnet#328]
### Overview

ITNOA

I think it is very useful to add ability to load configuration from file in Ioc, Some of values of this features

1. We can change configuration without needing recompile application.
2. In this scenario we can create multiple config set in multiple files and load them in specific situation without needing to recompile application.
3. We can change app behavior in runtime (or in deployment) without needing to reinstall app.

### API breakdown

```csharp
namespace Microsoft.Extensions.DependencyInjection
{
    /// <summary>
    /// Extension methods for adding services to an <see cref="IServiceCollection" />.
    /// </summary>
    public static class ServiceCollectionServiceExtensions
    {
         public static IServiceCollection AddFromConfig(this IServiceCollection services, IConfigurationSection config) {}
    }
```

### Usage example

```csharp
Ioc.Default.ConfigureServices(
      new ServiceCollection()
      .AddFromConfig(config.GetSection("Ioc"))
      .BuildServiceProvider());
```

### Breaking change?

No

### Alternatives

We must write something like [below](https://github.com/CommunityToolkit/MVVM-Samples/blob/master/samples/MvvmSampleUwp/App.xaml.cs)

```csharp
            // Register services
            Ioc.Default.ConfigureServices(
                new ServiceCollection()
                .AddSingleton<IDialogService, DialogService>() //Services
                .AddSingleton<IFilesService, FilesService>()
                .AddSingleton<ISettingsService, SettingsService>()
                .AddSingleton(RestService.For<IRedditService>("https://www.reddit.com/"))
                .AddSingleton(RestService.For<IContactsService>("https://randomuser.me/"))
                .AddTransient<PostWidgetViewModel>() //ViewModels
                .AddTransient<SubredditWidgetViewModel>()
                .AddTransient<ContactsListWidgetViewModel>()
                .AddTransient<AsyncRelayCommandPageViewModel>()
                .AddTransient<IocPageViewModel>()
                .AddTransient<MessengerPageViewModel>()
                .AddTransient<ObservableObjectPageViewModel>()
                .AddTransient<ObservableValidatorPageViewModel>()
                .AddTransient<ValidationFormWidgetViewModel>()
                .AddTransient<RelayCommandPageViewModel>()
                .AddTransient<CollectionsPageViewModel>()
                .AddTransient<SamplePageViewModel>()
                .BuildServiceProvider());
        }
```

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment]
The proposed API is an extension for `IServiceCollection`, which is from `Microsoft.Extensions.DependencyInjection`. That's a completely different package than the MVVM Toolkit, which doesn't even have a dependency on that. As such, this proposal is just out of scope and non actionable. You might want to open this proposal in https://github.com/dotnet/runtime, as that's where those APIs are defined 🙂
