### ISSUE TITLE
Add support for async/await handler on Register handler in Messenger

### ISSUE THREAD

**Issue by soroshsabz** [CommunityToolkit/dotnet#332]
### Overview

ITNOA

I think it is good to can call asynchronous method on handler of `Register` method of `Messenger` and `await` on that without problem.

### API breakdown

No API added.

### Usage example

```csharp
WeakReferenceMessenger.Default.Register<ContinueCallbackAnsweringRequestMessage>(this, async (r, message) =>
{
    await FooAsync();
    await BarAsync();
    message.reply(foo);
});
```

### Breaking change?

No

### Alternatives

I do not found any alternative :(

### Help us help you

Yes, but only if others can assist

**Comment by soroshsabz** [comment]
related to #331

**Comment by Sergio0694** [comment]
This is already supported, you're just registering the callback incorrectly. You can do this:

```csharp
WeakReferenceMessenger.Default.Register<ContinueCallbackAnsweringRequestMessage>(this, (r, m) =>
{
    async Task<Foo> ReceiveAsync()
    {
        await FooAsync();
        await BarAsync();

        return foo;
    }
    
    m.Reply(ReceiveAsync());
});
```

I should note, you should change this to avoid creating closures, for better performance ([see docs](https://docs.microsoft.com/en-us/windows/communitytoolkit/mvvm/messenger)):

```csharp
WeakReferenceMessenger.Default.Register<MyViewModel, ContinueCallbackAnsweringRequestMessage>(this, static (r, m) =>
{
    async Task<Foo> ReceiveAsync(MyViewModel r)
    {
        await r.FooAsync();
        await r.BarAsync();

        return r.GetSomeFoo();
    }
    
    m.Reply(ReceiveAsync(r));
});
```

We might consider adding some helper extensions to support this scenario in an easier way in the future I guess 🤔

**Comment by soroshsabz** [comment]
@Sergio0694 very thank you for response

the minor note is I think your code is not compile, because `CS0136	A local or parameter named 'r' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter`

**Comment by soroshsabz** [comment]
After I changing my code from your suggestion, I got `InvalidOperationException` on `Task<CancellatinToken>` , this behavior is like race conditioning, Did you know or see any problem on my implementation? (My code is [here](https://github.com/BSVN/linphone-windows10/tree/feature/2-add-call-back))

Am I use `Unwrap` correctly?

thanks

**Comment by soroshsabz** [comment]
I found my problem, thanks :)

**Comment by CodingOctocat** [comment]
@Sergio0694 hi, I implemented a simple asynchronous message, but it doesn't really seem to `await`.
> https://github.com/CommunityToolkit/dotnet/issues/18#issuecomment-2781165881

```cs
Messenger.Register<AsyncTaskRequestMessage<int, bool>, string>(this, "DelayAsync",
    (r, m) => {
        Debug.WriteLine("begin");
        m.Reply(Task.Delay(m.Request))
        Debug.WriteLine("end");
    });

await Messenger.Send(new AsyncTaskRequestMessage<int, bool>(3000), "DelayAsync");
Debug.WriteLine("done.");

// Actual output:
> begin
> done.
> wait 3s...
> end

// Expected output:
> begin
> wait 3s...
> end
> done.
```
