### ISSUE TITLE
Cannot clone xaml elements that bind to a RelayCommand

### ISSUE THREAD

**Issue by bedaronco** [CommunityToolkit/dotnet#339]
### Describe the bug

XamlReader.Load throws the following exception on elements that bind to RelayCommands because RelayCommand does not have a default constructor:

`MissingMethodException: No default constructor found for type 'CommunityToolkit.Mvvm.Input.RelayCommand'. You can use the Arguments or FactoryMethod directives to construct this type.
`

A common way to clone xaml elements is to use XamlWriter.Save and then XamlReader.Load to make a new element from the xaml string.  There should be a way to use this clone approach when binding to RelayCommand.

### Reproducible in sample app?

- [ ] This bug can be reproduced in the sample app.

### Steps to reproduce

```text
1. Create a UI with a button and bind the command to a RelayCommand
2. Create a method and call the following code using the button as the parameter to XamlWrite.Save
     string button = XamlWriter.Save(element);
     StringReader reader = new(button);
     XmlTextReader textReader = new(reader);
     var newElement = (FrameworkElement)XamlReader.Load(textReader);
3. XamlReader.Load will thow an exception due to no default constructor
```

### Expected behavior

Should be able to use XamlWriter.Save and XamlReader.Load to clone xaml elements.

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Visual Studio Version

2022

### Visual Studio Build Number

Version 17.0.5

### Device form factor

Desktop

### Help us help you

No.

**Comment by Sergio0694** [comment]
This looks like a very niche scenario that's outside of the scope of the MVVM Toolkit, which is platform agnostic. The command simply doesn't have a reason for having a parameterless constructor, as it would result in an unusable instance anyway, and only having that to potentially support this XAML/text round-tripping would be an abstraction leak 🙂
