### ISSUE TITLE
Compiler won't build due to multiple definitions with same parameter types [WPF]

### ISSUE THREAD

**Issue by ParkerMitchellGW** [CommunityToolkit/dotnet#345]
### Describe the bug

Hello, I recently updated VS Community 2022 to Version 17.2.6, and I cannot seem to build any WPF applications which use the source generators in the Community Toolkit for MVVM. However, if I create a standard .NET application (without WPF), I can build projects just fine. The errors stated in WPF projects state that any class that use the attributes [INotifyPropertyChanged] or [ObservableObject], or even inherit from ObservableObject have multiple definitions of several members with the same parameter types, as seen below.

![Compiler Errors](https://user-images.githubusercontent.com/91492232/178812221-c6ab4d0a-d7e9-4630-81be-4940673075a0.png)

Minimal Repro here (Just a standard WPF application from VS2022 with 1 empty class):
https://github.com/ParkerMitchellGW/MinReproDuplicateAttribute

### Steps to reproduce

```text
Example Repro Steps:
1. Given the following environment: WPF Windows application targetting .NET 6.0, with VS Community 2022 v17.2.6.
2. Create a new class.
3. Attempt to add the [INotifyPropertyChanged] attribute to that class.
4. Build the project to see errors in the Error List
```

### Expected behavior

The project should build successfully.

### Screenshots

![image](https://user-images.githubusercontent.com/91492232/178813507-87325acf-8d25-43f3-bf66-8daf9dfb7b93.png)

The class causing these errors:
![image](https://user-images.githubusercontent.com/91492232/178813544-c5b8d06e-542d-445c-8bc9-15814fa0c38b.png)

### IDE and version

VS 2022

### IDE version

17.2.6

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0-preview4

### Additional context

This problem started after updating VS Community 2022. 

I had also installed the Win11 SDK from visual studio, but I don't know how that could have affected this.

### Help us help you

No, just wanted to report this

**Comment by ParkerMitchellGW** [comment]
I just realized this may be a duplicate of #343, my apologies

**Comment by Sergio0694** [comment]
No worries! And yup this is indeed a duplicate, closing this one 🙂
