### ISSUE TITLE
Consider forwarding `MemberNotNull` and `MemberNotNullWhen` for observable properties

### ISSUE THREAD

**Issue by 333fred** [CommunityToolkit/dotnet#365]
### Overview

Today, `MemberNotNull` and `MemberNotNullWhen` attributes are not forwarded from backing fields to observable properties. This would be useful for observable properties that indicate that other properties are valid to access.

### API breakdown

No new APIs need to be added.

### Usage example

```cs
[ObservableProperty, MemberNotNullWhen(true, nameof(Value))]
private bool isValid;

[ObservableProperty]
private string? value;
```

Would generate two properties, `IsValid` and `Value`, and `IsValid` would have the `MemberNotNullWhen` attribute applied to it.

### Breaking change?

No

### Alternatives

None.

### Help us help you

No, just wanted to propose this

**Comment by Sergio0694** [comment]
This will be supported through #413:

```csharp
[ObservableProperty]
[property: MemberNotNullWhen(true, nameof(Value))]
private bool isValid;

[ObservableProperty]
private string? value;
```

Closing as duplicate since this one is superseded by explicit forwarding 🙂
