### ISSUE TITLE
The namespace 'System.Diagnostics.CodeAnalysis' already contains a definition for 'NotNullIfNotNullAttribute'

### ISSUE THREAD

**Issue by fredericoregateiro** [CommunityToolkit/dotnet#366]
### Describe the bug

Build  a wpf project with: `<TargetFrameworks>net48;net6.0-windows</TargetFrameworks>`
[WpfAppCommunityToolkit.zip](https://github.com/CommunityToolkit/dotnet/files/9273989/WpfAppCommunityToolkit.zip)

### Steps to reproduce

```text
Create a wpf project with: `<TargetFrameworks>net48;net6.0-windows</TargetFrameworks>`

Add CommunityToolkit.Mvvm nuget

Build the project

The errors:
Error	CS0579	Duplicate 'AttributeUsage' attribute
Error	CS0101	The namespace 'System.Diagnostics.CodeAnalysis' already contains a definition for 'NotNullAttribute'	WpfAppCommunityToolkit (net48)
Error	CS0101	The namespace 'System.Diagnostics.CodeAnalysis' already contains a definition for 'NotNullIfNotNullAttribute'	WpfAppCommunityToolkit (net48)
Error	CS0111	Type 'NotNullIfNotNullAttribute' already defines a member called 'NotNullIfNotNullAttribute' with the same parameter types	WpfAppCommunityToolkit (net48)
```

### Expected behavior

Build the project with no errors

### IDE and version

VS 2022

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment]
Weird, wonder if this is a duplicate of #343?
Are you on VS 17.2.6? Can you try the workaround suggested there?

**Comment by fredericoregateiro** [comment]
@Sergio0694 yes i'm on vs 17.2.6

I try this workaround [https://github.com/CommunityToolkit/dotnet/issues/343#issuecomment-1184663095](https://github.com/CommunityToolkit/dotnet/issues/343#issuecomment-1184663095) and it worked.

I'm working in a solution with a WPF and AvaloniaUI projects and the errors where only from the WPF project and more specific the net48 target.

Thanks
