### ISSUE TITLE
RelayCommand does not compile when implementing interface for view model

### ISSUE THREAD

**Issue by bluechiperic** [CommunityToolkit/dotnet#373]
My ViewModel implements an interface where I have a RelayCommand attribute decorating a method

Visual Studio however will not recognize that the RelayCommand attribute is going to generate the appropriate IAsyncRelayCommand to match my Interface.

For example, the following code yields a build error that my view model does not implement the ILocationViewModel interface.

```csharp
public interface ILocationViewModel
{
    IAsyncRelayCommand GetDeviceLocationCommand();
}

[ObservableObject]
public partial class LocationViewModel : ILocationViewModel
{
    [RelayCommand]
    private async Task GetDeviceLocationAsync()
}
```

Interestingly enough, I do not seem to have the same problem when it comes to the ObservableProperty attribute.

**Comment by michael-hawker** [comment]
@bluechiperic can you clarify your code a bit. You're showing a method in the interface, but the generator will be generating a property.

Can you open up the analyzers underneath the project and see that the command generated? As it should be named `GetDeviceLocationCommand` based on your code above.

**Comment by bluechiperic** [comment]
Ah, I see, yes, I needed a property instead of a command in the interface.  Thanks!
