### ISSUE TITLE
 [ObservableProperty] on a model don't update the UI #4718 

### ISSUE THREAD

**Issue by meilleur102** [CommunityToolkit/dotnet#383]
### Describe the bug

Hi!
I have a weird problem with the ObservableProperty.
When I create a property in the ViewModel, if I create a string, int, bool etc...or an ObservableCollection the Ui update without any problem.
When I create a properties of the Model itself it's not working.

For example

//I Try with the INotifyPropertyChanged on the top of each ViewModel or make the ViewModelBase an ObservableObject, that change nothing.
[INotifyPropertyChanged]
public class MainViewModel : ViewModelBase
{
     public MainViewModel(){}

    public void Method()
    {
      // If I bind the Text to this it's working
       Name = GetName();
     // This is not working
       Form.Name = GetName();
    }

[ObservableProperty] private string Name;
[ObservableProperty] private FormModel Form;

}

public class FormModel
{
    public string Name {get;set;}
}

I Change of course the DataContext of the StackPanel and even the intellisence can see the property.
I try with one way, two way UpdateSourceTrigger=PropertyChanged. Nothing work.

### Regression

IDK

### Steps to reproduce

```text
1.Create a model
2.In the viewModel, create a [ObservableProperty] of the model
3.Create a textBox in the view
4.Update the Name property.
```

### Expected behavior

Expect the UI to get the update

### IDE and version

Rider

### IDE version

2022.2

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.00

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment]
This is by design, `FormModel.Name` is not an observable property 🙂

**Comment by meilleur102** [comment]
> This is by design, `FormModel.Name` is not an observable property 🙂

So If I have a model with like 30 properties I need to make a copie of each in the viewModel and parse it into the model after? Or theres a quicker way to do it? 
In my model I have zero buisness logic (I put everything in services), so for me the model is really just to parse the properties.

**Comment by Enxyphered** [comment]
Why can't we have a separate ExposePropertyAtrribute that takes the property name as input and the sourcegenerator exposes the property in the viewmodel ? 
This could be marked as a feature request instead.
