### ISSUE TITLE
TypeExtensions.ToTypeString does not support generic types definitions

### ISSUE THREAD

**Issue by OleksiiD** [CommunityToolkit/dotnet#390]
### Describe the bug

TypeExtensions.ToTypeString throws the ArgumentOutOfRangeException exception for generic type definitions.

```csharp
TypeExtensions.ToTypeString(typeof(IDictionary<,>))
```

The easiest solution would be to add the following code in the FormatDisplayString method:

```csharp
if (type.IsGenericTypeParameter)
{
    return type.Name;
}
```

### Reproducible in sample app?

- [X] This bug can be reproduced in the sample app.

### Steps to reproduce

- Create .net6 app
- Add CommunityToolkit.Diagnostics 8.0.0 NuGet package
- Add the following line of code
```csharp
TypeExtensions.ToTypeString(typeof(IDictionary<,>))
```
- Run project

### Expected behavior

No exception.

### Nuget packages

CommunityToolkit.Diagnostics 8.0.0

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by michael-hawker** [comment]
@OleksiiD I've transferred your issue to the proper repository here for the .NET Community Toolkit. To help us better understand, what led you to originally file it in the Windows Community Toolkit repository? Thanks!
