### ISSUE TITLE
CommunityToolkit.MVVM compile error using MS AppCenter

### ISSUE THREAD

**Issue by marcoseraphin** [CommunityToolkit/dotnet#409]
### Describe the bug

I use the CommunityToolkit.MVVM in my Xamarin Forms project. (seems to be independent of Xamarin, just a C# Project)
Locally everything works fine, I define a private OberservablePropery:

[ObservableProperty]
private string searchText;

Per partial class, a file with the public property etc. is then automatically created for me. 
I can use this, bind it, etc.

When I compile this project with the MS App Center, the auto-generated files are NOT created and logically get a compile error like this.

==> SubmittedDocumentListPageModel.cs(102,13): error CS0103: The name 'SearchText' does not exist in the current context

### Regression

not sure, but I think that with version < 8.x there are no compile errors

### Steps to reproduce

```text
Use a simple C# / Xamarin project with the CommunityToolkit.MVVM NuGet included with a ObservableProperty property in code and try to compile it with MS AppCenter.
```

### Expected behavior

The project should compile without errors in the MS AppCenter using the CommunityToolkit.MVVM NuGet package 

### IDE and version

VS 2022 Preview

### IDE version

17.4

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0

### Help us help you

No, just wanted to report this

**Comment by marcoseraphin** [comment]
I made a test with a small MVVM.Toolkit sample projected I created some month ago.

It uses MVVM.Toolkit version 7.1.2 => this still works with AppCenter
Update to version 8.0.0 => getting errors in AppCenter !!!!!

So I think and remember that the Generator logic was changed/updated and with this update the AppCenter is not able to deal with…..interesting.

Either it will be fixed or I have to downgrade back to 7.1.2.

**Comment by Sergio0694** [comment]
This is interesting. I'm pretty sure it's a bug in AppCenter, not the Toolkit. I don't see how the code here could be causing this. Could you share a link to exactly what AppCenter package you're using, so we can take a quick look? Also, can you only repro this on Xamarin, or do you get the same error if eg. you made a WPF, or UWP app, and added AppCenter too? 🤔

**Comment by marcoseraphin** [comment]
Hi Sergio,

as I wrote the same sample project (Xamarin Forms App) => https://github.com/marcoseraphin/MVVMToolkitSample 
works in AppCenter if I referenced the CommunityToolkit.MVVM version 7.1.2 in my app project.

But after updating to version 8.0.0 I getting errors like this 

(CoreCompile target) -> 
  /Users/runner/work/1/s/MVVMToolkitSample/MainViewModel.cs(19,39): error CS0103: The name 'FirstName' does not exist in the current context [/Users/runner/work/1/s/MVVMToolkitSample/MVVMToolkitSample.csproj]
  /Users/runner/work/1/s/MVVMToolkitSample/MainViewModel.cs(19,51): error CS0103: The name 'LastName' does not exist in the current context [/Users/runner/work/1/s/MVVMToolkitSample/MVVMToolkitSample.csproj]

    6 Warning(s)
    2 Error(s)


Defined in the MainViewModel.cs:

[ObservableProperty]
[NotifyPropertyChangedFor(nameof(FullName))]
private string? firstName;

[ObservableProperty]
[NotifyPropertyChangedFor(nameof(FullName))]
private string? lastName;

So there is no difference by using the same AppCenter logic. Only the reference version 7.1.2 => 8.0.0 is the only difference.

So the question is: A Problem of the AppCenter not dealing with the new source generators or a problem of version 8.0.0

Best

Marco

**Comment by marcoseraphin** [comment]
actually I have only used it in Xamarin Forms App projects but I do not see any dependencies only to this kind of project.

**Comment by marcoseraphin** [comment]
I have downgraded back to version 7.1.2, seems no solution for the compile errors with version 8.0.0

**Comment by Sergio0694** [comment]
Is this the package you're using exactly? https://www.nuget.org/packages/Microsoft.AppCenter
This seems to be available for multiple targets, can you repro the issue in a blank .NET console app?
We need to figure out whether this is related to Xamarin, so trying this out in a standalone project would help 🙂

**Comment by marcoseraphin** [comment]
Hi Sergio,

it was faster than expected, here the Repo just with the AppCenter NuGet Package and version 8.0.0 referenced.
https://github.com/marcoseraphin/ConsoleApp_AppCenterTest 

I did not tested it with AppCenter yet.

BUT: Not all my projects references the AppCenter NuGet packages. Will it fail also with any AppCenter reference.
My guess was that the code generation did not work in AppCenter Independent of the usage/reference of any AppCenter NuGet packages ?

Thanx

Marco

**Comment by stephenhauck** [comment]
I am experiencing this issue and raised it with MS ... it seems that Appcenter is not using Roslyn 4 and I get his error 

"/Users/runner/work/1/s/***/***.Android/***.Android.csproj" (PackageForAndroid target) (1) ->
"/Users/runner/work/1/s/***/***/***.csproj" (default target) (2:2) ->
(MVVMToolkitRemoveAnalyzersForRoslyn3 target) -> 
  /Users/runner/.nuget/packages/communitytoolkit.mvvm/8.0.0/buildTransitive/netstandard2.0/CommunityToolkit.Mvvm.targets(41,5): warning : The MVVM Toolkit source generators have been disabled on the current configuration, as they need Roslyn 4.x in order to work. The MVVM Toolkit will work just fine, but features relying on the source generators will not be available. [/Users/runner/work/1/s/***/***/***.csproj]


Additionally it started to complain that the navigation parameters in the view models were not there even thought they are marked [ObservableProperty] ....

Once I resolved that by taking away the annotation and adding a public getter and setter it then started to complain about every property that had an annotation ...

**Comment by stephenhauck** [comment]
I forgot to mention that MS recommend that I build locally or move to Azure build pipelines both of which are unacceptable to me ...

**Comment by Sergio0694** [comment]
> "it seems that Appcenter is not using Roslyn 4"

Ah, well that explains it then. All source generators in the MVVM Toolkit need Roslyn 4 to work, yeah. We're explicitly disabling them if that's not the case, as that is a required feature for them to work at all with the incremental generation pipeline 🙂

Closing this then, as it's definitely external and not related to an issue with the MVVM Toolkit itself.

I am sorry to hear this is causing difficulty for you though 🥲

**Comment by stephenhauck** [comment]
It would be great if you could get someone on the Appcenter team to fix this ... Roslyn 4 and C# 9 have been out a VERY LONG TIME  ...

**Comment by Sergio0694** [comment]
> "I forgot to mention that MS recommend that I build locally or move to Azure build pipelines both of which are unacceptable to me"

Just so we understand this better, could you explain why this is unacceptable for you? GitHub Actions and ADO are very well suited for doing builds, are widely used and with extensive documentation, and used by almost everyone. Are there any blockers in particular for you to migrate to either of those for your builds, or something else? 🙂

**Comment by marcoseraphin** [comment]
Just time to setup all projects wirh GitHub Actions or AzureDevOps and I am using AppCenter tracking and logging stuff...

But I think I have to because . Net MAUI will not be supported by AppCenter

**Comment by Sergio0694** [comment]
> "I am using AppCenter tracking and logging stuff"

I'm also using AppCenter in my apps for analytics, but that's an independent feature, no? As in, you can keep using AppCenter for tracking and logging just fine even if you're using a different pipeline to build and distribute your apps, right? 🙂

**Comment by stephenhauck** [comment]
I realize the toolkit is not responsible for the Appcenter build failures but ...
Microsoft is leaving us out to dry with Appcenter.
Appcenter should be the default build platform that works and is tested simply because I has great analytics and crashlytics to offer ...
