### ISSUE TITLE
ObservableValidator triggers warning SA1633 "The file header XML is invalid" when using StyleCop.Analyzers

### ISSUE THREAD

**Issue by yariker** [CommunityToolkit/dotnet#41]
## Describe the bug

If you have a class inheriting from `ObservableValidator` from `Microsoft.Toolkit.Mvvm.ComponentModel` namespace, it would trigger a source code generator producing a file without a header. If code analysis is enabled in the project, such a file will be the subject of analysis.

Although the generated class is annotated with `GeneratedCode` attribute, it does not solve the issue because this attribute does not exclude the whole file, thus triggering warnings such as SA1633. This is critical for projects enforcing code style rules during build.

- [x] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work: 7.0.2

## Steps to Reproduce

1. Create a WPF project (either .NET 5/6 or .NET Framework).
2. Add references to packages `StyleCop.Analyzers` and `Microsoft.Toolkit.Mvvm` (see exact versions below).
3. Add `stylecop.json` [configuration file](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/EnableConfiguration.md) to the project.
4. Add a class that inherits from `ObservableValidator`, such as `MainViewModel`.
5. Rebuild the project and observe the warning such as follows:

> <...>\Microsoft.Toolkit.Mvvm.SourceGenerators\Microsoft.Toolkit.Mvvm.SourceGenerators.ObservableValidatorValidateAllPropertiesGenerator\WpfAppCore.MainViewModel.cs(1,1,1,1): warning SA1633: The file header XML is invalid.

## Expected behavior

The generated file should either contain `// <auto-generated/>` at the top of the file, or has an extension `*.g.cs` to tell Roslyn analyzers to exclude the file completely.

## Environment

NuGet Package(s): Microsoft.Toolkit.Mvvm 7.1.1, StyleCop.Analyzers 1.1.118
Visual Studio version: 2019 (16.11.6)

**Comment by Sergio0694** [comment]
Whoops, missed this one when moving all issues to the new repo 😄
I've already fixed this in #31, though we might want to cherry pick that fix and port it over to the Windows Community Toolkit as well if we want to do a 7.1.2 hotfix release, this one seems like a good candidate to make the cut for it as well.

cc. @michael-hawker
