### ISSUE TITLE
Allow custom property attributes for [ObservableProperty]

### ISSUE THREAD

**Issue by Sergio0694** [CommunityToolkit/dotnet#413]
### Overview

Right now, it's not possible to specify property attributes when using `[ObservableProperty]`, which has been a pain point for some users, as it forces you to go back to manual properties in that case. There's been several asks for this in the past, see (#228, #217, #208). We could technically support this via the explicit `property:` target, which Roslyn ignores but doesn't block. That is:

```csharp
[ObservableProperty]
[property: JsonPropertyName("name")]
private string? name;
```

The generator would emit:

```csharp
[JsonPropertyName("name")]
public string? Name
{
    get => name;
    set => ...
}
```

This would effectively allow users to have perfect control over attributes on target properties.

> **Note**: Roslyn will currently emit a diagnostic in this case, ~~so users would have to suppress it or just ignore it. Just not the perfect tooling experience, but it would still solve the issue and be a valid solution for now with no language changes needed.~~ which we can automatically suppress with a dedicated diagnostic suppressor, so not a problem.

**Comment by Sergio0694** [comment]
@333fred I know you were doing some work to block uses of invalid attribute targets, was that restricted to not recognized targets (ie. CS0658), or would that include invalid targets (ie. CS0657) too? As in, could we rely on that not being an error?

**Comment by Sergio0694** [comment]
Additionally (cc. @chsienki) would there be a way for a generator to suppress CS0657 on that field on behalf of users? As in, a way for it to basically tell Roslyn that yes those are ignored, but the generator actually needs that info, so it shouldn't be a warning. Being able to suppress those CS0657 from the generator would make the UX much better for the end users 🙂

**Comment by chsienki** [comment]
@Sergio0694 The generator can't do that, but you can ship a diagnostic suppressor in the same assembly. They were basically invented for this purpose :) https://github.com/dotnet/roslyn/blob/32c1f2d2df534f9ae3679807ecdfdd0706e8da6d/docs/analyzers/DiagnosticSuppressorDesign.md

**Comment by Sergio0694** [comment]
Ooh that's awesome, thank you! I'll look into it, this seems very promising then 😄

**Comment by TruePluto** [comment]
”which Roslyn ignores but doesn't block.“ Does Mean “It's just a makeshift or an expedient”
thanks

**Comment by virzak** [comment]
Should this be available on RelayCommand?

```cs
[RelayCommand]
[property: Newtonsoft.Json.JsonIgnore]
private void DoWork() { }
```

When I try to serialize an object which contains this code, `DoWork` gets serialized and this is something I'd like to avoid.

**Comment by Sergio0694** [comment]
This is doable, though would need additional justification for the work. Could you open a dedicated proposal?
Thank you! 🙂

**Comment by Aurumaker72** [comment]
> Should this be available on RelayCommand?
> 
> ```cs
> [RelayCommand]
> [property: Newtonsoft.Json.JsonIgnore]
> private void DoWork() { }
> ```
> 
> When I try to serialize an object which contains this code, `DoWork` gets serialized and this is something I'd like to avoid.

While this is not related to the toolkit, I'd like to add that serializing ViewModels is usually a sign of some misstep.

Consider serializing the backing model, which is often a trivially serializable DTO or POCO, instead.
