### ISSUE TITLE
Appcenter build fails 

### ISSUE THREAD

**Issue by stephenhauck** [CommunityToolkit/dotnet#415]
### Describe the bug

I don't quite think this is a bug in the project but people need to know and if you know how to fix the Appcenter build with additional scrips and such it would be helpful.

I upgraded a project to C# 9 and added the toolkit, refit all my properties and commands with [ObservableProperty] and [RelayCommand] that was awesome.

I'm running VS 2022 locally and it runs fine in the emulator and simulator.

Unfortunately the Appcenter  build fails with the  following error (along with many others) that are related to properties not being available which I'm guessing are related to the fact that the source generators are not running ?

(MVVMToolkitRemoveAnalyzersForRoslyn3 target) -> 
  /Users/runner/.nuget/packages/communitytoolkit.mvvm/8.0.0/buildTransitive/netstandard2.0/CommunityToolkit.Mvvm.targets(41,5): warning : The MVVM Toolkit source generators have been disabled on the current configuration, as they need Roslyn 4.x in order to work. The MVVM Toolkit will work just fine, but features relying on the source generators will not be available. [/Users/runner/work/1/s/***/***/***.csproj]

### Reproducible in sample app?

- [ ] This bug can be reproduced in the sample app.

### Steps to reproduce

```text
I simply refactored an existing functional system to use the library, checked it in which triggers the build
```

### Expected behavior

I expected it to continue to build successfully as nothing changed but the toolkit and C# 9

### Windows Build Number

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] Other (specify)

### App minimum and target SDK version

- [ ] Windows 10, version 1809 (Build 17763)
- [ ] Windows 10, version 1903 (Build 18362)
- [ ] Windows 10, version 1909 (Build 18363)
- [ ] Windows 10, version 2004 (Build 19041)
- [ ] Other (specify)

### Additional context

I said I would not help below only because I have no idea why in 2022 Appcenter build process is not using Roslyn 4 or how to resolve it ... it should simply work.

### Help us help you

No.

**Comment by ArchieCoder** [comment]
I ran into the blocker this morning. I sent a message to App Center 🤞.

**Comment by stephenhauck** [comment]
Thanks but it won’t matter …
After 4 days and little help they told me to move to Azure build pipelines … yeah, no thanks .. I told them to bring AppCenter into this decade with Roslyn 4

**Comment by ArchieCoder** [comment]
wow so disappointed. Day after day, it confirms my theory that they will pull the plug soon.

**Comment by ArchieCoder** [comment]
There is hope 
![image](https://user-images.githubusercontent.com/1608424/189917534-dd71253d-a9b2-4b57-b9e2-6b6cb68150ef.png)

**Comment by stephenhauck** [comment]
I love your optimism but the fact that they haven't even added MAUI to the screen to setup Appcenter configuration is somewhat disturbing as well ... 

There seems to be no outright .. "Yes, Appcenter crashlytics is AWESOME with MAUI " ....
