### ISSUE TITLE
Proposal: Move messaging functionality to a separate NuGet package

### ISSUE THREAD

**Issue by johatuni** [CommunityToolkit/dotnet#421]
### Overview

As the messaging functionality is, in my opinion, a separate pattern from the MVVM pattern, it would make sense to move this into its own CommunityToolkit.Messaging package. That would make the potential usage of it broader. I have good experience from using the Caliburn.Micro.EventAggregator package in my backend projects. The CommunityToolkit messaging functionality does have features that the EventAggregator from Caliburn.Micro lacks. Using a "message broker" in backend server projects (web api's, ...) helps reducing dependencies between services, in my experience.

Some of the MVVM related message classes that currently lives under the 'Messages' folder could potentially be kept in the MVVM package, while the more generic messages (RequestMessage<T> and AsyncRequestMessage<T>) could live in the new messaging package. 

### API breakdown

using CommunityToolkit.Messaging;

class MyClass
{
   void SomeMethod()
   {
        WeakReferenceMessenger.Default.Send(new TestMessage());
   }
}

### Usage example

dotnet add package CommunityToolkit.Messaging

### Breaking change?

Yes

### Alternatives

It is possible to reference the CommunityToolkit.MVVM package in backend projects. Having a separate CommunityToolkit.Messaging package just makes things, from an architectural point of view, more "correct".

### Help us help you

No, just wanted to propose this

**Comment by mikechristiansenvae** [comment]
If the messaging functionality is moved to a different NuGet package, would `CommunityToolkit.MVVM` then reference `CommunityToolkit.Messaging` ?  i.e., if you reference MVVM, you get _both_?  

Or, would it truly be an optional package?

**Comment by johatuni** [comment]
Yes, the MVVM package should depend on the Messaging package. However, it could be that having it optional is an interesting thought. It would allow for using the MVVM package with, for example, the MediatR package. 
My motivation for this proposal is not linked to MVVM, as I primarily want to use the messaging functionality at the backend.

**Comment by zsolt3991** [comment]
I completely agree with the original author. The messaging functionality in the toolkit seems like is a great starting point for setting up a pub-sub communication outside the context of MVVM, could be useful to split it for use cases that do not need the MVVM framework itself. I was looking into creating a similar messenger for my needs since I did not want to pull the whole package in.

**Comment by Sergio0694** [comment]
This would be a breaking change, and not something we're interested in, at least for now. If you want the messaging functionality, I don't see that big of an issue just referencing CommunityToolkit.Mvvm, the package is very small anyway and fully trimmable. There isn't really much harm at all even if you're just using the messenger APIs.
