### ISSUE TITLE
NuGet link in README points to confusing results

### ISSUE THREAD

**Issue by MisinformedDNA** [CommunityToolkit/dotnet#422]
### Describe the bug

The link for the release branch says it is version 7.1.2. 

![image](https://user-images.githubusercontent.com/1784452/188888926-bf017697-3a9f-42a8-9e24-21bf0840b436.png)

Furthermore, it links to a [profile](https://www.nuget.org/profiles/Microsoft.Toolkit), which lists all the deprecated packages first.

![image](https://user-images.githubusercontent.com/1784452/188889284-09aea820-85b9-4ca7-8460-95d318d29ea3.png)

### Steps to reproduce

```text
1. Go to https://github.com/CommunityToolkit/dotnet
2. Click the "Recommended Package Version" for the production target.
```

### Expected behavior

Links to actual package(s)

### IDE and version

Other

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [ ] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by michael-hawker** [comment]
We updated the readme to use this:

```
[![NuGet](https://img.shields.io/nuget/v/Microsoft.Toolkit.svg)](https://www.nuget.org/profiles/Microsoft.Toolkit)
```

I think I though the shields.io was also looking at the profile, if we use this image instead:

https://img.shields.io/nuget/v/CommunityToolkit.Common.svg

![](https://img.shields.io/nuget/v/CommunityToolkit.Common.svg)

It'll at least reflect the proper version.

---

The profile it links to is for the whole community toolkit, so it sorts by downloads by default. I don't think there's a NuGet feature to filter that list.

**Comment by MisinformedDNA** [comment]
What about linking directly to the packages instead of the profile?

**Comment by michael-hawker** [comment]
@MisinformedDNA that's covered by #148 and the associated PR #384
