### ISSUE TITLE
Non Generic `Send` method on `WeakReferenceMessenger`

### ISSUE THREAD

**Issue by DominicMaas** [CommunityToolkit/dotnet#440]
### Overview

I was wondering about the possibility of adding a non generic version of the `WeakReferenceMessenger.Default.Send<T>` method?

My use case is a little unique, I'm currently piping messages that I receive from a named pipe through the MVVM messenger system (making it easy to listen to messages throughout the app where needed). Problem is, the deserialized messages are simply objects (obviously expanding to valid types during runtime), so I have to do something rather nasty like this (works though!): 

```csharp
var method = typeof(IMessengerExtensions).GetMethods().First(x => x.Name == nameof(IMessengerExtensions.Send) && x.GetParameters().Length == 2);
var genericMethod = method!.MakeGenericMethod(message.GetType());
genericMethod.Invoke(null, new object[] { WeakReferenceMessenger.Default, message });
```

If this is too messy, or causes problems with trimming, then feel free to close (I'm mainly raising this as it causes trim warnings in my code as is).

I have a feeling that usage of `GetType()` internally for this non-generic implementation will cause issues anyway in terms of trimming? 

### API breakdown

I believe this would have to be added to both `IMessengerExtensions` and `WeakReferenceMessenger`, as existing method, but not generic.

### Usage example

Instead of my example used above, I would simple call

```csharp
WeakReferenceMessenger.Default.Send(message);
```

### Breaking change?

No

### Alternatives

na

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment]
Unfortunately there's not really a way to do this without using reflection, as the API won't know what actual type has to be used at runtime. There's different ways you can work around this if you own the various message types though. For instance, an easy solution is to use double dispatch:

```csharp
// Define this interface
public interface IMessage
{
    void Send(IMessenger messenger);
}

// Implement it in all your message types, eg.
public class MyMessage : IMessage
{
    void IMessage.Send(IMessenger messenger)
    {
        messenger.Send(this); // Double dispatch, this will invoke Send<MyMessage>
    }
}

// Send them with polymorphism like so
foreach (IMessage message in GetSomeMessagesFromWherever())
{
    message.Send(WeakReferenceMessenger.Default);
}
```

Would this solve your issue? 🙂

Closing this as not planned in the meantime, as we can't add support for this directly.

**Comment by DominicMaas** [comment]
Thanks Sergio, works wonderfully! I was very much over complicating things... 😅
