### ISSUE TITLE
Investigate AppContext switches for opt-in/opt-out features

### ISSUE THREAD

**Issue by Sergio0694** [CommunityToolkit/dotnet#46]
This is a tracking issue about experimenting with `AppContext` switches to customize the MVVM Toolkit.

## Rationale

There are some proposed features (eg. #28) that cannot really be implemented in a transparent and pay-for-play with the current setup. They'd end up either requiring a separate type, or adding overhead for everyone. Similarly, some existing features, such as the `INotifyPropertyChanging` support in `ObservableObject` are not really needed by everyone, and it would be nice to have a way of disabling them. Obviously the interface cannot be removed at runtime, but it could just be not functional if desired.

## The idea

We could experiment with adding a bunch of `AppContext` switches (see [`AppContext.SetSwitch`](https://docs.microsoft.com/en-us/dotnet/api/system.appcontext.setswitch) and [`AppContext.TryGetSwitch`](https://docs.microsoft.com/en-us/dotnet/api/system.appcontext.trygetswitch)) with names that we would then document, that would enable users to manually opt-in and out of specific features. The default values would remain consistent with the behavior today, but this would enable more experienced users to further customize the behavior of the MVVM Toolkit to suit their needs. Those switches would be cached into `static readonly bool` fields, so that checking them would be virtually free on modern runtimes (eg. when using tiered JIT, which is the default on CoreCLR, such fields would just become constants and be inlined when the method is recompiled at runtime, so the conditional branch would just vanish completely).

## Feature items

- [ ] Dispatcher-away invoke for property changed/changing events
- [ ] Opt-out switch for `INotifyPropertyChanging`
- [ ] ..?

**Comment by michael-hawker** [comment]
For `INotifyPropertyChanging` - Is there a big advantage to checking the bool and not firing the event if there's no handlers registered?

Could this be enabled better with the Source Generator support by not inheriting from `ObservableObject` and just using the `INotifyPropertyChanged` attribute? Could the `ObservableObject` generator attribute have a property for this to change the generated version as well?

**Comment by Sergio0694** [comment]
> "Is there a big advantage to checking the bool and not firing the event if there's no handlers registered?"

Yes, calling `SetProperty` becomes about twice as fast and allocates half (as it's no longer also creating the `PropertyChangingEventArgs` object, which is spawned regardless of whether there are any handlers for the event).

Here's some numbers (benchmark is just doing `++` on an observable property that uses `SetProperty`):

|        Method |      Mean |     Error |    StdDev | Ratio | Code Size |  Gen 0 | Allocated |
|-------------- |----------:|----------:|----------:|------:|----------:|-------:|----------:|
|          Main | 11.010 ns | 0.2153 ns | 0.2014 ns |  1.00 |     151 B | 0.0111 |      48 B |
| **NoPropertyChanging** |  **5.894 ns** | 0.1401 ns | 0.1376 ns |  **0.54** |      97 B | 0.0056 |      **24 B** |

Additionally, since configuration values are cached in a `static readonly bool` fields, they can just be inlined and removed completely by the tier 1 JIT. Basically once tiered JIT kicks in, there will be no check at all: just the right branch will be selected and the rest of the code will just be removed entirely. So you'll either end up with exactly the same code as before, or the whole check and skipped call to `OnPropertyChanging` will be removed directly.

> "Could this be enabled better with the Source Generator support by not inheriting from `ObservableObject` and just using the `INotifyPropertyChanged` attribute?"

Yup, you could also do this by just using `[INotifyPropertyChanged]` if you want. The advantage of this solution though is that it lets users also just inherit from `ObservableObject`, and most importantly it means this feature also applies to cases where you're using `ObservableRecipient` and `ObservableValidator`, which just inherit from `ObservableObject`.

> "Could the `ObservableObject` generator attribute have a property for this to change the generated version as well?"

I don't think that'd be worth it. If you're going to use source generators, then if you only wanted `INotifyPropertyChanged` support you should just use `[INotifyPropertyChanged]` directly, since it's done explicitly for that purpose. If `[ObservableObject]` also had an option for this, then they would just become identical, and one of the two would be redundant.

**Comment by Sergio0694** [comment]
The switch for `INotifyPropertyChanging` has been added in #48, closing this. We can open separate issues to track potential future switches individually.
