### ISSUE TITLE
使用ObservableProperty特性标注的字段，其更改时无法在WPF控件上显现。 

### ISSUE THREAD

**Issue by wxysy** [CommunityToolkit/dotnet#474]
### Describe the bug

当我使用ObservableProperty特性标注一个字段myString时，该框架自动生成一个对应属性MyString。
将此属性绑定到WPF文本控件TextBox后，我修改字段myString的内容，TextBox控件内容不更新；但是如果我直接修改属性MyString，TextBox控件内容则会自动更新。

### Steps to reproduce

```text
1、环境：.Net 6， WPF框架。IDE：Visual Studio 2022。

2、语言：csharp
[ObservableObject]
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            this.DataContext = this;
        }

        [RelayCommand]//生成命令SayHelloCommand
        private void SayHello()
        {
            myString = "变化后";    
        }

        [ObservableProperty]
        private string myString = "初始值";
    }

<Window x:Class="ToolkitMVVM.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:ToolkitMVVM"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <Button x:Name="btn_Action" Command="{Binding Path=SayHelloCommand}" Content="Button" HorizontalAlignment="Left" Margin="49,331,0,0" VerticalAlignment="Top" Height="55" Width="171"/>
        <TextBox x:Name="tb_Show" HorizontalAlignment="Left" Margin="49,37,0,0" TextWrapping="Wrap" Text="{Binding NewString}" VerticalAlignment="Top" Width="273" Height="106" FontSize="18"/>
    </Grid>
</Window>
```

### Expected behavior

请修复此bug。

### IDE and version

VS 2022

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
This is by design. You have to set the value of the generated property in order for it to notify changes. If you change that command to set `MyString` instead of the field, that'll work correctly 🙂

**Comment by wxysy** [comment]
> This is by design. You have to set the value of the generated property in order for it to notify changes. If you change that command to set `MyString` instead of the field, that'll work correctly 🙂

Thank you for your help.
