### ISSUE TITLE
IMessenger generates incorrect code for projects targeting net462

### ISSUE THREAD

**Issue by jozefizso** [CommunityToolkit/dotnet#480]
### Describe the bug

Our project is targeting .NET Framework 4.6.2

We upgraded from `Microsoft.Toolkit.Mvvm` v7.1.2 to `CommunityToolkit.Mvvm` v8.0.0. As we use the messenger classes from the toolkit, source generators create new code for them using features from C# 8.0. As the project is using C# 7.3, the generated code is incompatible with the project.

```
D:\dev\Project1\CommunityToolkit.Mvvm.SourceGenerators\CommunityToolkit.Mvvm.SourceGenerators.IMessengerRegisterAllGenerator\Project1.Utils.Updater.AutomaticUpdatesChecker.g.cs(11,13,11,19): error CS8370: Feature 'static local functions' is not available in C# 7.3. Please use language version 8.0 or greater.
```

```cs
partial class __IMessengerExtensions
{
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.Obsolete("This method is not intended to be called directly by user code")]
    public static global::System.Action<global::CommunityToolkit.Mvvm.Messaging.IMessenger, object> CreateAllMessagesRegistrator(global::Project1.Utils.Updater.AutomaticUpdatesChecker _)
    {
        static void RegisterAll(global::CommunityToolkit.Mvvm.Messaging.IMessenger messenger, object obj)
        {
            var recipient = (global::Project1.Utils.Updater.AutomaticUpdatesChecker)obj;
            messenger.Register<global::Project1.Messages.InitializedMessage>(recipient);
        }

        return RegisterAll;
    }
}
```

### Regression

7.1.2

### Steps to reproduce

```text
1. Create project targeting .NET Framework 4.6.2
2. Use CommunityToolkit.Mvvm v8.0.0
3. Add call to `Messenger.Register<InitializedMessage>(this);`
4. Build the project
5. Project fails to build with message

error CS8370: Feature 'static local functions' is not available in C# 7.3. Please use language version 8.0 or greater.
```

### Expected behavior

Either no source code is generator for messenger for legacy projects or a compatible code is generated.

### IDE and version

VS 2022

### IDE version

17.3.6

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
Hey there! I think this has been fixed by https://github.com/CommunityToolkit/dotnet/pull/398. Could you get a preview package from our preview feed (https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-MainLatest/nuget/v3/index.json) and see if it does solve the issue for you? Thank you! 🙂

**Comment by jozefizso** [comment]
Thanks, I tried package `8.0.0-build.329` and it does work in our project now.
