### ISSUE TITLE
Pass `Atributes` to generated public property is not working

### ISSUE THREAD

**Issue by AndreasReitberger** [CommunityToolkit/dotnet#524]
### Describe the bug

I having a class, where some properties should not be serialized. For instance, the `Timer` property.
```cs
[ObservableProperty]
[field: JsonIgnore]
[field: XmlIgnore]
Timer _timer;
```

Before switching to this nuget, the code looked like.

```cs
[JsonIgnore, XmlIgnore]
Timer _timer;
[JsonIgnore, XmlIgnore]
public Timer Timer
{
    get => _timer;
    set
    {
        if (_timer == value) return;
        _timer = value;
        OnPropertyChanged();
    }
}
```

There, I just was able to set `[JsonIgnore, XmlIgnore]` to the public property as well.
How do I achieve this here?

### Steps to reproduce

```text
1. Take a property which fails the XML serialization (for instance Timer)
2. Try to pass the [XmlIgnore] attribute to the generated source code.
```

### Expected behavior

Public, generated proeprty should get the attribute passed.

### IDE and version

VS 2022 Preview

### IDE version

17.5.0 Preview 1.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
This is supported as part of https://github.com/CommunityToolkit/dotnet/issues/413. You'll need 8.1 Preview, and you'll need to use `property:` in the attribute list on the field (not `field:`) 🙂
