### ISSUE TITLE
Add analyzer to warn when [INotifyPropertyChanged] & co. are used when not needed

### ISSUE THREAD

**Issue by Sergio0694** [CommunityToolkit/dotnet#530]
### Overview

The `[INotifyPropertyChanged]` and `[ObservableObject]` are meant to support cases where inheriting isn't possible, but it seems this point is easy to spot for a lot of folks, who just use these attributes instead of the base types. We should consider adding an analyzer to flag those cases and emit a warning. Specifically, these cases should produce a warning:
- `[INotifyPropertyChanged]` on a type that doesn't have a base class.
- `[ObservableObject]` on a type that doesn't have a base class.

### Usage example

The following should produce a warning:

```csharp
[ObservableObject]
public partial class MyViewModel
{
}
```

**Comment by Kinematics** [comment]
The toolkit documentation pages (eg: https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/errors/mvvmtk0031) do not include the new errors 0032 and 0033. Not having a proper explanation of these errors is confusing.

**Comment by Sergio0694** [comment]
Just merged the docs PR, should go live in a minute. Thank you for the ping! 🙂
