### ISSUE TITLE
Allow to call a method / action / event on property change

### ISSUE THREAD

**Issue by AndreasReitberger** [CommunityToolkit/dotnet#534]
### Overview

I'm not sure if this is alredy possible, I just found something similar with a `Command`.

```cs
[ObservableProperty]
[NotifyMethodFor(nameof(MyFunction))]
string myStringProperty;

void MyFunction()
{
  // do stuff
}
```

or

```cs
[ObservableProperty]
[NotifyEventFor(nameof(SomethingChanged), new SomethingChangedEventArgs())]
string myStringProperty;

public event EventHandler<SomethingChangedEventArgs> SomethingChanged;
        protected virtual void OnSomethingChanged(SomethingChangedEventArgs e)
        {
            SomethingChanged?.Invoke(this, e);
        }
```

### API breakdown

[ObservableProperty]
[NotifyEventFor(nameof(SomethingChanged), new SomethingChangedEventArgs())]
string myStringProperty;

public event EventHandler<SomethingChangedEventArgs> SomethingChanged;
        protected virtual void OnSomethingChanged(SomethingChangedEventArgs e)
        {
            SomethingChanged?.Invoke(this, e);
        }

### Usage example

[ObservableProperty]
[NotifyEventFor(nameof(SomethingChanged), new SomethingChangedEventArgs())]
string myStringProperty;

public event EventHandler<SomethingChangedEventArgs> SomethingChanged;
        protected virtual void OnSomethingChanged(SomethingChangedEventArgs e)
        {
            SomethingChanged?.Invoke(this, e);
        }

### Breaking change?

I'm not sure

### Alternatives

None

### Help us help you

No, just wanted to propose this

**Comment by Sergio0694** [comment]
This is already possible by implementing the generated partial methods:

```csharp
[ObservableProperty]
[NotifyMethodFor(nameof(MyFunction))]
string myStringProperty;

partial void OnMyStringPropertyChanged(string value)
{
    // Do stuff (including calling other methods if needed)
}
```
