### ISSUE TITLE
Add partial support for net462

### ISSUE THREAD

**Issue by dittodhole** [CommunityToolkit/dotnet#542]
### Overview

To minimize the assembly output of net462 projects when using `CommunityToolkit.Diagnostics`, please add support for net462 in:

- CommunityToolkit.Diagnostics (needs `System.ValueTuple`)
- CommunityToolkit.Common (needs `System.Memory` and `System.ValueTuple`)

### API breakdown

N/A

### Usage example

N/A

### Breaking change?

No

### Alternatives

![image](https://user-images.githubusercontent.com/429216/208677889-fec80d69-60a4-4d21-9a72-526f1b748425.png)

Deal with additional assembly output

### Help us help you

No, just wanted to propose this

**Comment by teo-tsirpanis** [comment]
Why can't you update to .NET Framework 4.7.2+? It supports all supported OS versions 4.6.2 supports.

**Comment by Sergio0694** [comment]
Unfortunately this is not something we plan on supporting. Our lowest target is NS2.0, which recommends using at least .NET Framework 4.7.2 (see [here](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0)). We won't be adding .NET Framework specific targets to the .NET Community Toolkit 🥲

**Comment by dittodhole** [comment]
> Why can't you update to .NET Framework 4.7.2+? It supports all supported OS versions 4.6.2 supports.

Thanks for your input, but it is of absolutely no help 😞 Please let the reasons be a thing I have to worry about (One of them is that my company creates software in the industrial field, where one cannot strictly enforce wsus policies on offline [or even online] clients - only go for the absolut bare minimum [support-wise] to not break things. net472 is only covered by Windows Server 2019 onwards ootb - see https://learn.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies for reference).

> Our lowest target is NS2.0, which recommends using at least .NET Framework 4.7.2 (see [here](https://learn.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0)).

I see your point, thanks for clarifaction.

Nevertheless, absolut minimum (in terms of possibility) is net462 which is mostly explicitly covered by all the `System.*`- and `Microsoft.Extensions.*`-packages, so I thought that would be a good fit for this project either.
