### ISSUE TITLE
Make ObservableProperty Generated Code Properties Virtual?

### ISSUE THREAD

**Issue by hounddog22030** [CommunityToolkit/dotnet#543]
I have found myself in a situation where I would like to mock (Moq) some of the properties generated.  Without them being virtual, this is not possible.  Has this been taken into consideration as a possibility (to generate the properties as virtual)?

**Comment by Sergio0694** [comment]
This will be supported once partial properties are available. There are no plans to add this to the field annotations.

**Comment by hounddog22030** [comment]
What are partial properties?

**Comment by Sergio0694** [comment]
See the proposal here: https://github.com/dotnet/csharplang/issues/6420. Might possibly be available in C# 12 🙂

**Comment by Sergio0694** [comment]
Closing this, as it's superseded by #555.
