### ISSUE TITLE
MVVM Messenger | Remove Duplicates or Duplicate Detection

### ISSUE THREAD

**Issue by JawadJaber** [CommunityToolkit/dotnet#558]
### Discussed in https://github.com/CommunityToolkit/dotnet/discussions/471

<div type='discussions-op-text'>

<sup>Originally posted by **JawadJaber** October 20, 2022</sup>
I would like to know if the MVVM Messenger can be configured to detect duplicate messages and then perform action based on the last message. My scenario is that sometimes the same event is invoked several times and I want to reduce the overhead of the messenger up to the last message. I know that it might need to add timespan parameters so the messenger would wait for one second for example and then removes duplicated messages and send the last one?</div>

**Comment by Sergio0694** [comment]
Will reply in the discussion, closing this. Please don't open issues for something already in a discussion 🙂
