### ISSUE TITLE
The scan for inheriting ObservableObject should cover all partial classes.

### ISSUE THREAD

**Issue by Summpot** [CommunityToolkit/dotnet#559]
### Describe the bug

CommunityToolkit.Mvvm reports a diagnostic when inheritance from ObservableObject occurs on a partial class generated by another source generator:
"MVVMTK0019The field xxx cannot be used to generate an observable property, as its containing type doesn't inherit from ObservableObject, nor does it use [ObservableObject] or [INotifyPropertyChanged]"

### Steps to reproduce

Write a source generator that generates a partial class that inherits from ObservableObject, and CommunityToolkit.Mvvm will report diagnostics and prevent compilation from passing.

### Expected behavior

CommunityToolkit.Mvvm should recognize the inheritance of ObservableObject on another partial class.

### IDE and version

VS 2022 Preview

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.1.0-preview3

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by Sergio0694** [comment]
Hey there! The repro steps are not entirely clear to me, do you mean that if you have some _other_ source generator (say, from a different NuGet package), that lets you use, say, some `[AddObservableObjectBaseType]` attribute this way:

```csharp
[AddObservableObjectBaseType]
public partial class MyViewModel
{
    [ObservableProperty]
    private string? name;
}
```

That generator will then generate:

```csharp
public partial class MyViewModel : ObservableObject
{
}
```

Is that correct?

**Comment by Sergio0694** [comment]
In that case then there's no way to fix this. Source generators run concurrently and they can't see the output from other generators. There is no way we could know what some other source generator will be generating. The MVVM Toolkit generators are _already_ looking for all partial classes and inspecting them, the issue here is that those partial declarations just don't exist yet when the generator runs, as those are created concurrently by this other generator 🥲

**Comment by Sergio0694** [comment]
> "can Mvvm toolkit be referenced by another source generator as a class library, so that another source generator provides SyntaxProvider and takes over the process of source code generation?"

No, you can't have a generator that somehow "takes over" a different generator.
What you're asking for is fundamentally an unsupported scenario that's out of scope 🙂
I would recommend trying to just avoid having a different generator inject the base class here.
