### ISSUE TITLE
If using `[property: ...]` VS 2022 says `Using directive is unnecessary`

### ISSUE THREAD

**Issue by AndreasReitberger** [CommunityToolkit/dotnet#563]
### Describe the bug

The `ForeignKey` needs the using, however, VS states it doesn't. On cleanup, it will be removed, however the build still passes.
But on runtime it crashes.

```cs
using SQLiteNetExtensions.Attributes;

[ObservableProperty]
[property: ForeignKey(typeof(Supplier))]
public Guid supplierId;
```

### Expected behavior

The using should be recognized as necessary.

### Screenshots
![image](https://user-images.githubusercontent.com/2952443/212671672-fe7e6508-a550-4519-8258-05bee833a9e0.png)

### IDE and version

VS 2022

### IDE version

17.4.3

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.1.0-preview3

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
This feels like it'll need a new diagnostic analyzer to detect these cases, which might be a bit tricky.
The use case is valid though. I'll look into this for 8.2, thank you! 🙂
For now you'll likely just have to suppress that warning, unfortunately.

> "But on runtime it crashes."
Can you clarify what you mean? How does it crash _at runtime_? 🤔

**Comment by AndreasReitberger** [comment]
In this case, it throws an exception because the `ForeignKey` was not defined or the the SQLite database doesn't know about the object (because of the missing description of the `ForeingKey`. Same happens with NewtonSoft if using `JsonIgnore`.
So the same, if you just do not set the `ForeignKey`. Same happens with NewtonSoft if using `JsonIgnore`. The problem only appears if the needed using is removed, if it's there (even if saying unnecessary), it works.

Thanks for your prompt reply!

**Comment by Sergio0694** [comment]
Ah, I see, yeah the generator was just skipping the attribute entirely if not recognized. We might want to generate a diagnostic instead of silently skipping unrecognized attributes, right. That would avoid these kind of "surprise" runtime crashes 🙂

Interestingly enough, I can't repro the warning though:

![](https://user-images.githubusercontent.com/10199417/212674384-b0671906-d26d-4b94-a424-b1316fdb5231.png)

**Comment by Sergio0694** [comment]
I've opened a PR to at least add the diagnostic if the using is missing, which should help 🙂

**Comment by Sergio0694** [comment]
Tried again, cannot repro this anymore. Closing this for now, but feel free to update if anything changes 🙂
