### ISSUE TITLE
Missing notes on new 8.1.0 analyzers

### ISSUE THREAD

**Issue by bdovaz** [CommunityToolkit/dotnet#568]
### Describe the bug

@Sergio0694 If I go to this page and try to click on any of the new analyzers, the page does not exist:

https://github.com/CommunityToolkit/dotnet/blob/v8.1.0/src/CommunityToolkit.Mvvm.SourceGenerators/AnalyzerReleases.Shipped.md#release-81

MVVMTK0032, MVVMTK0033, MVVMTK0034 and MVVMTK0035

You can check here that you can only see up to 31:

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/errors/mvvmtk0031

### Steps to reproduce

```text
As I said above.
```

### Expected behavior

They should be documented.

### IDE and version

VS 2022

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [ ] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.1.0

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
This is expected, I just haven't had time to update docs yet 😅
Will see if I can get the done today.
