### ISSUE TITLE
MVVMTK0033 (or another analyzer) should issue a warning if you inherit from ObservableObject and you still have the attribute

### ISSUE THREAD

**Issue by bdovaz** [CommunityToolkit/dotnet#569]
### Overview

@Sergio0694 Trying to correct MVVMTK0033 (and possibly MVVVMTK0034, MVVMTK0035) I noticed this. That is, if you have this code:

```csharp
    [ObservableObject]
    public partial class MyViewModel
    {
    }
```

And I correct it to comply with MVVMTK0033:

```csharp
    [ObservableObject]
    public partial class MyViewModel : ObservableObject
    {
    }
```

Actually it should be:

```csharp
    public partial class MyViewModel : ObservableObject
    {
    }
```

I also think it affects MVVMTK0032 because if you inherit from `ObservableObject` there is no need for `[INotifyPropertyChanged]`.

### API breakdown

Noted above.

### Usage example

Noted above.

### Breaking change?

No

### Alternatives

None.

### Help us help you

No, just wanted to propose this

**Comment by bdovaz** [comment]
@Sergio0694 I just read the post:

https://devblogs.microsoft.com/dotnet/announcing-the-dotnet-community-toolkit-810/

But there is a typo, isn't there? What I mark in yellow should not be [ObservableObject]? Which in fact is just what I mention in this issue, isn't it?

![image](https://user-images.githubusercontent.com/950602/213376084-7ce918d6-d970-4940-8f1b-495044559dc6.png)

**Comment by Sergio0694** [comment]
Closing this as I'm not really seeing an issue and I can't repro. The `[ObservableObject]` generator is already checking that and emitting the diagnostic you mention, in case you already eg. inherit from `ObservableObject` or similar, like so:

![](https://user-images.githubusercontent.com/10199417/213896261-12954615-65d5-49c0-b824-c47aa9bca0db.png)
