### ISSUE TITLE
Editor Issues While Using `[ObservableProperty]`

### ISSUE THREAD

**Issue by atom0s** [CommunityToolkit/dotnet#57]
## Describe the bug

While making use of the new `[ObservableProperty]` source generator, and potentially the other new generators, accessing the injected property names (and potentially other injected code) causes the editor to show errors. 

As an example, here is a simple ViewModel that can reproduce the error:
```csharp
namespace Launcher.ViewModel;

using CommunityToolkit.Mvvm.ComponentModel;

public partial class AboutViewModel : ObservableObject
{
    public AboutViewModel()
    {
        this.Test1 = "Hello world.";
    }

    [ObservableProperty]
    private string _test1;
}
```

Visual Studio marks a few things here that may need to be fixed:

 - The constructor is marked with a warning saying:
```
CS8618	Non-nullable field '_test1' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.
```

_This warning will appear regardless if you access the fields using the attribute or not. Just having the ctor is enough for them to cause this warning._

 - The `set_` field access is marked as an error saying:
```
CS1061	'AboutViewModel' does not contain a definition for 'Test1' and no accessible extension method 'Test1' accepting a first argument of type 'AboutViewModel' could be found (are you missing a using directive or an assembly reference?)
```

- The field itself is marked as:
```
IDE0044: Make field readonly.
```

_This last one is kind of annoying since it puts the grey squares in the scrollbar of the editor for every single property that will make use of this source generator now._

To help visualize this, here is a screenshot of what my editor looks like using the above code:

![devenv_aGxkpLhk0N](https://user-images.githubusercontent.com/1422090/144931524-c159e542-3d66-4b75-9837-a01dfa456fd2.png)

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:

## Steps to Reproduce

- [x] Can this be reproduced in the Sample App? (Either in a sample as-is or with new XAML pasted in the editor.) If so, please provide custom XAML or steps to reproduce. If not, let us know why it can't be reproduced (e.g. more complex setup, environment, dependencies, etc...)

Steps to reproduce the behavior: (In a new project)

1. Open VS2022, create a new project of your type choosing. (In my case, I am using WPF)
2. Add a ViewModel folder and inside of it, add a new AboutViewModel class.
3. Add a using to `using CommunityToolkit.Mvvm.ComponentModel;`.
4. Change the class definition to `partial`.
5. Add a private string property using the `[ObservableProperty]` attribute as shown above in the example code. (Name it `_test1`)
6. Add a constructor. You should see the 2nd issue already now.
7. Attempt to access the known injected property name in this new constructor. (`this.Test1 = "Hello";`) You should see the first issue now.
8. You should also see the third issue already as well.

Steps to reproduce the behavior: (In the sample app)

1. Clone the sample app repository.
2. Open the Sample App in VS2022. (In my case, testing with the `MvvmSampleUwp.sln`)
3. Update the project dependencies to latest Mvvm community toolkit version. (From 7.0.3 to 7.1.2 in Nuget manager.)
4. Open the MvvmSample.Core > ViewModels > SamplePageViewModel.cs
5. Change the class type to `partial`.
6. Add a private string property using the `[ObservableProperty]` attribute as shown above in the example code. (Name it `_test1`)
7. You should now see the second and third problem already. The constructor will warn about the field and the field will suggest being marked readonly.
8. Attempt to access the known injected property name in this new constructor. (`this.Test1 = "Hello";`) You should see the first issue now.

## Expected behavior

Based on the examples given and shown in the blog post about these new generators, there should be no errors, warnings, or suggestions while using the `[ObservableProperty]` attribute.

## Screenshots

_See above, the picture fits better with the explanation above than being separated and posted here._

## Environment

NuGet Package(s): 
Package Version(s):
  - CommunityToolkit.Mvvm (7.1.2)
  - Microsoft.Extensions.DependencyInjection (6.0.0)

Windows 10 Build Number:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Insider Build ({build_number})
- [x] November 2021 Update (21H2)

App min and target version:

- [ ] Fall Creators Update (16299)
- [ ] April 2018 Update (17134)
- [ ] October 2018 Update (17763)
- [ ] May 2019 Update (18362)
- [ ] May 2020 Update (19041)
- [ ] Insider Build ({build_number})
- [x] November 2021 Update (21H2)

Device form factor:

- [x] Desktop
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Visual Studio version:

- [ ] 2017 (15.{minor_version})
- [ ] 2019 (16.{minor_version})
- [x] 2022 (17.0.2)

**Comment by Sergio0694** [comment]
I cannot repro this using the new incremental generators from #63 and VS2022 17.1 Preview 1.1:

![](https://user-images.githubusercontent.com/10199417/146591520-17eca6ad-4914-4aba-941d-93fa2e8573c9.png)

I think the issue you were seeing was a combination of using the old non incremental generators, and VS2019/VS2022-GA being a bit bugged as well in the IntelliSense area. As for that warning about the field being `null` initially, that's by design, so yeah you should either set it to an empty string, or just declare the field as nullable.
