### ISSUE TITLE
Microsoft.CSharp.Core.targets errors and source generator errors

### ISSUE THREAD

**Issue by RabbitAth** [CommunityToolkit/dotnet#573]
I for the first time installed CommunityToolKit.Mvvm Nuget version 8.1.0 to and existing project with some existing ViewModels. I have ended up with over 250 errors in Microsoft.CSharp.Core.targets.  I had attempted to create a new BaseViewModel to inherit from and a new ViewModel and build my project when the errors appeared.

Using Visual Studio version 17.3.4
Target framework for the project is net6.0 (this is a .Net MAUI Class Library I believe)
Visual Studio Project Properties -> Build -> Advanced has a language version of 10.0

I have also ended up with errors and warnings in the SourceGenerators such as:
MVVMTK0008: Unsupported C# language version (Per above I don't think this should be an issue)
MVVMTK0020: Invalid use of attributes dependent on [ObservableProperty]
MVVMTK0033: Inherit from Observable Object instead of using [INotifyPropertyChanged]
MVVMTK0033: Inherit from ObservableObject instead of using [ObservableObject]
MVVMTK0034: Direct field reference to [ObservableProperty] backing field

Do I have a version mismatch issue? Any help would be appreciated, thank you.

**Comment by RabbitAth** [comment]
Previously avoided updating VS as I believe I had issues with 17.4.0 or 17.4.3 and parts of MAUI so I rolled back.

Just now updated to VS 17.4.4 on a different machine.  Still seeing source generator errors and warnings MVVMTK0000 under CommunityTookit.Mvvm.SourceGenerators in net6.0, net6.0-windows, etc.  However I am able to build and run my MAUI app which references the library with the MVVM toolkit, so far no issue's with errors related to Microsoft.CSharp.Core.targets.  Not sure if the MVVMTK0000's are an issue.  

Is providing a repo still useful?  I was working on it but on the VS 17.3.4 machine.  Will likely update the version.

**Comment by Sergio0694** [comment]
Yes, if you could provide a minimal repro that would help 🙂
If you can make one in a plain .NET project with no MAUI or other dependencies, that's much better still.

**Comment by RabbitAth** [comment]
![image](https://user-images.githubusercontent.com/112127379/213777349-e512c08f-f29e-48bb-b8e3-ed0812613c56.png)

VS 17.3.4 - Errors from minimal git project (these errors do not exist in VS 17.4.4)

**Comment by RabbitAth** [comment]
![image](https://user-images.githubusercontent.com/112127379/213777670-9d7efc9e-fa2d-40d5-8d97-ba2578cbb17b.png)

Source generator errors that exist in both VS 17.3.4 and 17.4.4

**Comment by RabbitAth** [comment]
[Minimal Project Repository](https://github.com/RabbitAth/RA-CommunityToolKitTestV01)

**Comment by Sergio0694** [comment]
Those errors in 17.3.4 are expected, it's a bug in Roslyn that was fixed in 17.3.6. See #493. I'll try out the repro for the other ones, thank you! 🙂

**Comment by Sergio0694** [comment]
The repro builds just fine for me on VS 17.4.4 🤷
Just with a couple warnings for those nullable properties.

![](https://user-images.githubusercontent.com/10199417/213779553-da23f9d6-40aa-43f4-bdd5-88fdc96c6a5b.png)

**Comment by Sergio0694** [comment]
Closing for now, but feel free to update if you have more info or find another scenario that can repro 🙂

**Comment by RabbitAth** [comment]
Okay thank you! Please note that is a new project, that was created in 17.3.4 and then opened again and tested in 17.4.4.  Which could be the cause.  I do not see the same issue's in the sample MonkeyFinder project from James Montemagno using toolkit version 8.0.0 which was downloaded and run on VS 17.3.4.
