### ISSUE TITLE
ObservableProperty Fails Intelisense Linking, Sometimes

### ISSUE THREAD

**Issue by BinaryAssault** [CommunityToolkit/dotnet#574]
### Describe the bug

This typical occurs when I create some ObservableProperty and later on change the name of the field. It seems to break all intelisense linking and I get 'The name '<variable>' does not exist in the current context. 

VS 2022 64 But v17.5.0 Preview 3.0
.NET 7.0.2
CommunityToolkit.Mvvm v8.1.0

### Steps to reproduce

Replicating seems to occur more often in a separate class.
``````
public partial class SomeModel :ObservableObject
{
	[ObservableProperty]
	private bool _someBool;
	
	[ObservableProperty]
	private int _someInt;
}

// some other file

public class SomeViewModel :ObservableObject
{
	public SomeModel SomeModel {get;set;}
	
	public SomeViewModel()	
	{
		SomeModel.SomeBool = true;
	}
}
``````

Compile, run notice it works.

``````
change
	[ObservableProperty]
	private bool _someBool;
	
to
	
	[ObservableProperty]
	private bool _somethingElse;
``````

Notice intelisense now can no longer see SomethingElse or SomeInt inside of SomeViewModel. Everything compiles and works, but intelisense isn't happy and there are many errors in the error list

### Expected behavior

intelisense doesn't show errors for valid properties, no errors in the error list for valid properties

### Screenshots
<img width="607" alt="image" src="https://user-images.githubusercontent.com/19739224/213763051-cb36589b-7831-4e5b-8d84-8d12d63b976e.png">

### IDE and version

VS 2022, VS 2022 Preview

### IDE version

VS 2022 64 But v17.5.0 Preview 3.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.1.0

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
This is Roslyn and not caused by the MVVM Toolkit. Could you open an issue at https://github.com/dotnet/roslyn/issues?
You can also link this one from there once you do. Thank you! 🙂
