### ISSUE TITLE
ObservableProperty Intellisense not working in Blazor razor files

### ISSUE THREAD

**Issue by RonPeters** [CommunityToolkit/dotnet#576]
### Describe the bug

[ObservableProperty] works fine in classes that are defined in the Blazor project. But if the Blazor project consumes a DLL that contains a view model with an [ObservableProperty], that property will never show up in Intellisense in the razor file, even though it works fine in c# files in the Blazor project.

I've added default values to all non-nullable properties: https://github.com/CommunityToolkit/dotnet/issues/57
I've deleted .vs folder and restarted Visual Studio: https://github.com/dotnet/roslyn/issues/44093

Nothing works. I ended up giving up on the source generator and doing the properties the old fashioned way to get Intellisense.

### Steps to reproduce

```text
No Intellisense:

[ObservableProperty]
private string example = default!;

Succesful Intellisense:
private string example = default!;
public string Example
{
   get => example;
   set => SetProperty(ref example, value);
}
```

### Expected behavior

Intellisense should be available in razor files that consume the view model class, just like in c# files

### IDE and version

VS 2022

### IDE version

17.4.4

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.0/8.1.0

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment]
This is unfortunately not something that's up to the MVVM Toolkit, so there's nothing we can do about it from here 🥲
Please open an issue for this either in the Roslyn or Blazor repo, and feel free to link back to this one from there.
Thank you! 🙂
