### ISSUE TITLE
"Event to command" or “Event Binding”

### ISSUE THREAD

**Issue by xingzhenlu** [CommunityToolkit/dotnet#591]
### Overview

 I’m loving the MVVM Toolkit!<br>
Every time I write mvvm code, it is difficult to handle events. However, I know that dexpress use MarkupExtension  called ["DXEvent“](https://docs.devexpress.com/WPF/115778/mvvm-framework/dxbinding/dxevent) to deal with this problem, which makes the xaml code simple and easy to implement. Can we add this function to this library in the future?

There is  another library  called [MvvmEventBinding](https://www.nuget.org/packages/MvvmEventBinding/1.0.0) that also implements this function, but I hope "Community Toolkit library"  can also have this function! 

### API breakdown

``` csharp
public class EventBindingExtension : MarkupExtension
{
    private readonly string _commandName;

    public EventBindingExtension(string command)
    {
        _commandName = command;
    }

    public override object ProvideValue(IServiceProvider serviceProvider)
    {
        MethodInfo method = GetType().GetMethod("InvokeCommand", BindingFlags.Instance | BindingFlags.NonPublic);
        if (method != null && serviceProvider.GetService(typeof(IProvideValueTarget)) is IProvideValueTarget provideValueTarget)
        {
            object targetProperty = provideValueTarget.TargetProperty;
            if (targetProperty is EventInfo)
            {
                Type eventHandlerType = (targetProperty as EventInfo).EventHandlerType;
                return method.CreateDelegate(eventHandlerType, this);
            }
            if (targetProperty is MethodInfo)
            {
                ParameterInfo[] parameters = (targetProperty as MethodInfo).GetParameters();
                if (parameters.Length >= 1)
                {
                    Type parameterType = parameters[1].ParameterType;
                    return method.CreateDelegate(parameterType, this);
                }
            }
        }
        throw new InvalidOperationException("The EventBinding markup extension is valid only in the context of events.");
    }

    private void InvokeCommand(object sender, EventArgs args)
    {
        if (!string.IsNullOrEmpty(_commandName) && sender is FrameworkElement frameworkElement)
        {
            object dataContext = frameworkElement.DataContext;
            if (dataContext != null)
            {
                PropertyInfo property = dataContext.GetType().GetProperty(_commandName);
                if (property != null && property.GetValue(dataContext) is ICommand command && command.CanExecute(args))
                {
                    command.Execute(args);
                }
            }
        }
    }
}
```

### Usage example

``` xaml
<Button Click="{mvvm:EventBinding ButtonClickCommand}">Click me!</Button>
<TextBlock MouseMove="{mvvm:EventBinding TextMoveCommand}">Some text</TextBlock>
<ListView SelectionChanged="{mvvm:EventBinding ListSelectionChangedCommand}" ItemsSource="{Binding Items}" />
```

### Breaking change?

Yes

### Alternatives

["DXEvent“](https://docs.devexpress.com/WPF/115778/mvvm-framework/dxbinding/dxevent) 
[MvvmEventBinding](https://www.nuget.org/packages/MvvmEventBinding/1.0.0) 

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by Sergio0694** [comment]
This is not planned, as it would require a direct dependency on a specific UI framework, whereas the MVVM Toolkit is by design platform agnostic. You're welcome to pick any library that provides events to commands to enable this scenario. For instance, you can try [XAML Behaviors](https://github.com/microsoft/XamlBehaviors), which targets WPF, UWP and WinUI 3) and is officially supported 🙂
