### ISSUE TITLE
Add RelayCommand that keeps track of Parameters and other proerties that change to update the CanExecute state

### ISSUE THREAD

**Issue by sensslen** [CommunityToolkit/dotnet#593]
### Overview

The current implementation of RelayCommand requires calling `NotifyCanExecuteChanged()` whenever anything changes that affects the CanExecute state of the Command. This proposal is defived from [this](http://northhorizon.net/2012/better-commands-in-wpf/) Blog post and requests something similar to [this](https://github.com/danielmoore/WpfIgniter#expression-command).

This allows to use the command to automatically track the CanExecute state without the need for the developer to call `NotifyCanExecuteChanged()`.

### API breakdown

```csharp
var command = new AutoTrackingRelayCommand(DoStuff, CanExecuteExpression);

private void DoStuff()
{
    // do stuff
}

private Expression<Func<bool>> CanExecuteExpression = () => true;
```

### Usage example

```csharp
[AutoTrackingRelayCommand(CanExecuteExpression)]
private void DoStuff()
{
    // do stuff
}

private Expression<Func<bool>> CanExecuteExpression = () => true;
```

### Breaking change?

No

### Alternatives

https://github.com/danielmoore/WpfIgniter#expression-command implements this - however this does not provide source generators and also requires additinal dependencies

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment]
Thank you for the proposal!
This is not something we plan on adding, at least not in the proposed shape, as the solution you referred to is not linker nor AOT friendly, and also adds a substantial amount of overhead. One of the core principles of the MVVM Toolkit is being fast and also fully trimmable and AOT safe, and using an `Expression<>` and reflection doesn't really go well with this 🥲

On a separate note, the proposed use case example:

```csharp
[AutoTrackingRelayCommand(CanExecuteExpression)]
private void DoStuff()
{
    // do stuff
}

private Expression<Func<bool>> CanExecuteExpression = () => true;
```

Is not valid C# syntax. You cannot pass a property to an attribute argument.

**Comment by sensslen** [comment]
Do you have any suggestions o how to fight patterns like this?
```csharp
public IRelayCommand<string> DoStuffCommand { get; set; }

public string SomeInfo
{
    get => (string)GetValue(SomeInfoProperty);
    set => SetValue(SomeInfoProperty, value);
}

public static readonly DependencyProperty SomeInfoProperty = DependencyProperty.Register(nameof(SomeInfo), typeof(string), typeof(ThisClass), new PropertyMetadata( SomeInfoPropertyChanged));

private static void NewPlaylistNamePropertyChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
{
    (d as ThisClass)?.DoStuffCommand?.NotifyCanExecuteChanged();
}
```

**Comment by Sergio0694** [comment]
That code seems fine, you do need a property changed callback to notify the command in this case. I guess the real question though is: why do you have a command and a dependency property in the same file in the first place? The only scenario where I can imagine this being a thing is for a public templated control or custom control, which seems a very niche scenario anyway (and in that case you'd already have all the boilerplate for the dependency properties anyway).
