### ISSUE TITLE
Ambiguous reference when using source generator

### ISSUE THREAD

**Issue by yangbocheng** [CommunityToolkit/dotnet#596]
### Describe the bug

how to solve this problem?
it seems has generated same properties

![image](https://user-images.githubusercontent.com/32633109/216949682-d2244855-d73d-40a8-98ff-eee2f0d907fa.png)

![image](https://user-images.githubusercontent.com/32633109/216949831-2b8225dc-6472-414c-b482-329fff4a5c42.png)

```csharp
public partial class AllNoteViewModel : ObservableObject
{
    public AllNoteViewModel()
    {

        Notes = new ObservableCollection<NoteModel>();
        Notes.Add(new NoteModel
        {
            Text = "test1",
            Date = DateTime.Now.AddDays(1).ToString()
        });
        Notes.Add(new NoteModel
        {
            Text = "test2",
            Date = DateTime.Now.AddDays(2).ToString()
        });
    }

    public ObservableCollection<NoteModel> Notes { get; set; }


    [ObservableProperty]
    private string more;

    
}
```

```csharp
public partial class NoteModel : ObservableObject
{
    [ObservableProperty]
    private string text;

    [ObservableProperty]
    private string date;

}
```

### Steps to reproduce

```text
above all
```

### Expected behavior

above all

### IDE and version

VS 2022 Preview

### IDE version

17.5.0 Preview 5.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.1.0

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by pijnappel** [comment]
Can confirm. This is really annoying. This happens in my .NET MAUI project when targeting Windows and Android.
The project builds successfully but the ViewModels are plastered with IntelliSense 'Ambiguous reference'  Errors 'Ambiguous reference'.

**Comment by ckrutsinger** [comment]
I have seen this issue pop up from time to time. I have been able to clear it by closing and restarting VS.

**Comment by Sergio0694** [comment]
This seems weird and potentially related to Roslyn. @yangbocheng do you repro in a blank .NET project? What is your setup, is that a multi-targeted project using some framework (eg. MAUI), or something else? I cannot repro in a blank .NET 6 project.

**Comment by yangbocheng** [comment]
This mistake happens too often。that's  a  maui，which install packages :communitytoolkit mvvm and maui,
i have no way to offer an repo to show those mistakes, because, when reopen VS , or just a random minutes, those mistakes may or not may disappear

But it comes up a lot，just write some codes , write some properties,  and complier, and debug and then continue .
maybe then it must occurs

**Comment by KyawHtetSS** [comment]
![image](https://github.com/CommunityToolkit/dotnet/assets/33857909/bb9fdf8c-6ca9-414d-a95e-07e7e272f2d1)

In my case, It won't show after opening. But red wavy lines started to show when I edited or added new Observable Property to existing class. 

The Condition is I have ViewModelBase class, 

public class ViewModelBase : ObservableRecipient
{

}

public class ShellViewModel : ViewModelBase
{
[ObservableProperty] InformationMessage lastMessage;
}

Yes, it won't show all the time. Only show when I add new [ObservableProperty] to ShellViewModel and Saved, the wavy lines started to occour. 
Sometime, only some Property show red wavy lines and others are ok. 
Sometime, all red wavy lines disappear and all normal. 
Even if Wavy lines are shown, I can build and run successfully.

it is really wired.
