### ISSUE TITLE
Allow custom field and property attributes for [RelayCommand]

### ISSUE THREAD

**Issue by virzak** [CommunityToolkit/dotnet#599]
### Overview

When trying to serialize an object that contains a `[RelayCommand]` the command property gets serialized by default, which could be undesirable.

We should be able to apply a custom property. to avoid serialization

### Usage example

```cs
[RelayCommand]
[property: Newtonsoft.Json.JsonIgnore]
private void DoWork() { }
```

### Breaking change?

No

### Alternatives

The alternative is to pass options during serialization.

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by TruePluto** [comment]
I think so  but should be ?

```
[RelayCommand]
[field: Newtonsoft.Json.JsonIgnore]
private void DoWork() { }
```
PS：How to colorize these code？

**Comment by laolarou726** [comment]
Maybe also add the support for [ObservableProperty]? Some times it's really important to ignore those observable fields.

**Comment by Sergio0694** [comment]
@laolarou726 `[ObservableProperty]` has supported custom attributes since 8.1 already 🙂
See https://devblogs.microsoft.com/dotnet/announcing-the-dotnet-community-toolkit-810/.

**Comment by laolarou726** [comment]
> @laolarou726 `[ObservableProperty]` has supported custom attributes since 8.1 already 🙂 See https://devblogs.microsoft.com/dotnet/announcing-the-dotnet-community-toolkit-810/.

My bad, sorry about that
