### ISSUE TITLE
OnChanged and OnChanged not accessible on inherit classes

### ISSUE THREAD

**Issue by CesGan** [CommunityToolkit/dotnet#629]
### Describe the bug

Methods OnChanged and OnChanging are not accessible on inherited classes.

```csharp
public class Class1 : ViewModelBase
{
    public Class1()
    {
        Name = "Foo";
    }

    partial void OnNameChanged(string value) // -> CS0759	No defining declaration found for implementing declaration of partial method 'Class1.OnNameChanged(string)'

    {
        throw new NotImplementedException();
    }

    partial void OnNameChanging(string value) // -> CS0759	No defining declaration found for implementing declaration of partial method 'Class1.OnNameChanging(string)'

    {
        throw new NotImplementedException();
    }
}

public abstract partial class ViewModelBase : ObservableObject
{
    [ObservableProperty]
    private string name;

    partial void OnNameChanged(string value) // -> Works
    {
        throw new NotImplementedException();
    }

    partial void OnNameChanging(string value) // -> Works
    {
        throw new NotImplementedException();
    }
}
```

### Expected behavior

Methods should be available.

### IDE and version

VS 2022

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.1.0

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
This is by design, partial methods with no accessibility modifier are effectively private. These can't be made protected because that would force you to always implement them, otherwise the code would not compile. If you absolutely need derived class to be able to inject logic, you can add a `protected virtual` method for that, and call it from those two private methods.
