### ISSUE TITLE
[ObservableProperty] Does it support Interface Property Implementation

### ISSUE THREAD

**Issue by cgp1976** [CommunityToolkit/dotnet#649]
### Describe the bug

```cs
public interface MyInterface 
{
    public List<object> Items { get; set;}
}

public partial class MyViewModel: MyInterface 
{
     [ObservableProperty] // ---<  over here visual studio throw error CS0535
     private List<object> _item=null;
}
```

### Steps to reproduce

try the code with visual studio
it will generate compile error with code CS0535

### IDE and version

VS 2022 Preview

### IDE version

Microsoft Visual Studio Professional 2022 (ARM 64-bit) - Preview Version 17.6.0 Preview 2.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

CommunityToolkit.Mvvm 8.1.0

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
This is the expected behavior, your code just has a bug. The interface member is called "Items", but the field in the class is called "_item" (without the final "s"), so the generated property will be "Item" and not "Items" 😄
