### ISSUE TITLE
A combination of Cast and Slice leads to AccessViolationException

### ISSUE THREAD

**Issue by mahalex** [CommunityToolkit/dotnet#674]
### Describe the bug

The following code throws `System.AccessViolationException`:
```csharp
            int height = 720;
            int width = 1280;
            byte[] storage = new byte[width * height * sizeof(int)];
            Memory2D<int> data = storage
                .AsMemory()
                .Cast<byte, int>()
                .AsMemory2D(height: height, width: width);
            Memory2D<int> slice = data.Slice(
                row: height / 2,
                column: 0,
                height: height / 2,
                width: width);
            int total = 0;
            foreach (int v in slice.Span)
            {
                total += v;
            }
```

### Steps to reproduce

```text
Create a project targeting net7.0, paste the above code into the `Main` method, run it.
```

### Expected behavior

The code is supposed to calculate a sum of all values in the slice (in this case, 0).

### Screenshots

![image](https://user-images.githubusercontent.com/19844519/234864326-64a19b75-f4e5-4d99-9100-431efefde4e0.png)

### IDE and version

VS 2022

### IDE version

17.4.4

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [X] CommunityToolkit.HighPerformance
- [ ] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.2.0

### Additional context

The problem disappears when there's no `Cast()` (so, we are summing over a `Span` of bytes). It also disappears when there's no `Slice()` (so, we are summing over `data` instead of `slice`).

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
Good catch!! Thank you 😄

**Comment by ChristophLindemann** [comment]
@Sergio0694 do you have some ETA of when this will be released? I can see you added it to `8.2.1`, but I could not find a planned/estimated release date for that?

It's just so I can decide if I should implement a workaround for this, or if I can wait for `8.2.1`.

**Comment by Sergio0694** [comment]
I don't have an exact ETA just yet, but tentatively I'd say probably around the first half of June or so?
Can you use a nightly package from main in the meantime? The feed is this one:
https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-MainLatest/nuget/v3/index.json

**Comment by ChristophLindemann** [comment]
I guess, I could use one of the nightly builds for now.

I will use `8.2.1-build.2`

Thanks
