### ISSUE TITLE
 .netframework project

### ISSUE THREAD

**Issue by AmeerMansour** [CommunityToolkit/dotnet#715]
### Describe the bug

i am trying to use it for a .netframework project but it seems it doesn't add anaylzers. 

![image](https://github.com/CommunityToolkit/dotnet/assets/47938924/8065608c-5ca3-41ef-bd66-4360c90d6445)

### Steps to reproduce

1.Create wpf project ( .Net framework)
2.Add community toolkit

### Expected behavior

Analyzers should be automatically added.

### IDE and version

VS 2022

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.0.2

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment]
Hey there! We added a new analyzer for this scenario, could you try using our latest preview and checking with that?

Add our preview feed:

```
https://pkgs.dev.azure.com/dotnet/CommunityToolkit/_packaging/CommunityToolkit-MainLatest/nuget/v3/index.json
```

And then install the lates MVVM Toolkit 8.2.1 preview build you see there. Thank you! 🙂

**Comment by AmeerMansour** [comment]
Still not working ... 
I believe there is another issue. 
to use it in  .net frameworks projects:
I had to add "**<LangVersion>latest</LangVersion>**"  or "**<LangVersion>9.0</LangVersion>**" to my project then **_manually_** add the analyzer

**Comment by AmeerMansour** [comment]
Also code fixer analyzer is not being added to any .net framework project .

**Comment by Sergio0694** [comment]
So, the analyzers not working are by design, as you're using `packages.config`, which is not supported.
**But**, with 8.2.1 you should be seeing a warning about this. Are you not seeing it?
You should see this warning:

https://github.com/CommunityToolkit/dotnet/blob/d6eb5ccd83bbf162f1cd6bf170f8f540e9f60d47/src/CommunityToolkit.Mvvm/CommunityToolkit.Mvvm.targets#L143-L146

**Comment by Sergio0694** [comment]
You **do** have the warning, you can see it in the first line:

![](https://github.com/CommunityToolkit/dotnet/assets/10199417/a3c2f734-b136-42ca-98ce-16c09ed1c849)

Very weird that it's not showing in the final result. Let me ask the Roslyn team about this 🙂

Either way - `packages.config` is not supported. You need to switch to `<PackageReference>` to use the generators.

**Comment by AmeerMansour** [comment]
that will be a very big and complicated issue to convert my existing project to use PackageReference 
some other nuget will fail and will crash my project.

**Comment by Sergio0694** [comment]
I'm afraid your alternative is just to not use the generators for now then 🥲
To clarify: this is not a limitation with the MVVM Toolkit. The C# compiler (Roslyn) just doesn't support source generators at all for projects using `packages.config`, so there's nothing we can do from our end to make our generators work there unfortunately.
