### ISSUE TITLE
Implement IncrementalLoadingCollection from IAsyncEnumerable

### ISSUE THREAD

**Issue by Licantrop0** [CommunityToolkit/dotnet#717]
### Overview

To implement an IncrementalLoadingCollection, you need:

1. [IIncrementalSource](https://github.com/CommunityToolkit/dotnet/blob/main/src/CommunityToolkit.Common/IncrementalLoadingCollection/IIncrementalSource.cs) from the dotnet repo, `CommunityToolkit.Common` namespace
2. [IncrementalLoadingCollection](https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/main/Microsoft.Toolkit.Uwp/IncrementalLoadingCollection/IncrementalLoadingCollection.cs) from the WindowsCommunityToolkit repo, `Microsoft.Toolkit.Uwp` namespace.

The API design is quite dated and requires creating a source class implementing `IIncrementalSource<TItem>`, and creating `IncrementalLoadingCollection<TSource, TItem>`.  

IIncrementalSource requires to implement a method returning `Task<IEnumerable<TItem>>` that is modernly expressed with `IAsyncEnumerable<TItem>`.

`IAsyncEnumerable<TItem>` allows cycling over the collection in a fully asynchronous way and it's the perfect fit for a modern IncrementalLoadingCollection. I called this new type `AsyncLoadingCollection`

### API breakdown

```csharp
using System.Collections.ObjectModel;
using Microsoft.UI.Xaml.Data;
using Windows.Foundation;

namespace MsGraphSamples.WinUI.Helpers;

public class AsyncLoadingCollection<T> : ObservableCollection<T>, ISupportIncrementalLoading
{
    private readonly uint _itemsPerPage;
    private IAsyncEnumerator<T>? _asyncEnumerator;
    private readonly SemaphoreSlim _mutex = new(1, 1);

    public bool HasMoreItems => _asyncEnumerator != null;

    public AsyncLoadingCollection(IAsyncEnumerable<T> source, uint itemsPerPage = 25)
    {
        ArgumentNullException.ThrowIfNull(nameof(source));

        _asyncEnumerator = source.GetAsyncEnumerator();
        _itemsPerPage = itemsPerPage;
    }

    public IAsyncOperation<LoadMoreItemsResult> LoadMoreItemsAsync(uint count = default) =>
        LoadMoreItemsAsync(count == default ? _itemsPerPage : count, new CancellationToken(false))
        .AsAsyncOperation();

    private async Task<LoadMoreItemsResult> LoadMoreItemsAsync(uint count, CancellationToken cancellationToken)
    {
        await _mutex.WaitAsync();

        if (cancellationToken.IsCancellationRequested || !HasMoreItems)
        {
            return new LoadMoreItemsResult(0);
        }

        uint itemsLoaded = 0;
        var itemsToLoad = Math.Min(_itemsPerPage, count);

        try
        {
            while (itemsLoaded < itemsToLoad)
            {
                if (await _asyncEnumerator!.MoveNextAsync())
                {
                    Add(_asyncEnumerator.Current);
                    itemsLoaded++;
                }
                else
                {
                    // Dispose the enumerator when we're done
                    await _asyncEnumerator.DisposeAsync();
                    _asyncEnumerator = null;
                    break;
                }

                if (cancellationToken.IsCancellationRequested)
                {
                    break;
                }
            }
        }
        catch (OperationCanceledException)
        {
            // The operation has been canceled using the Cancellation Token.
        }
        catch (Exception)
        {
            throw;
        }
        finally
        {
            _mutex.Release();
        }

        return new LoadMoreItemsResult(itemsLoaded);
    }
}
```

### Usage example

```csharp

public static async IAsyncEnumerable<string> GetSampleData()
{
    for (var i = 0; i < 100; i++)
    {
        await Task.Delay(i * 10);
        yield return $"string {i}";
    }
}

var myAsyncCollection = new AsyncLoadingCollection<string>(GetSampleData());

// this is needed for the initial load (viewControls like DataGrid don't call it automatically after DataContext change)
await MyAsyncCollection.LoadMoreItemsAsync();
```

Then you can bind myAsyncCollection to a DataGrid as ItemsSource

### Breaking change?

No

### Alternatives

After few days of research, I couldn't find any other implementation of an IncrementalLoadingCollection using IAsyncEnumerable.

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment]
Hey there, thank you for the feature proposal! Unfortunately this is out of scope for the .NET Community Toolkit and just could not be added to it at all, as the proposed implementation has a hard dependency on several WinRT and WinUI 3 APIs (`ISupportIncrementalLoading`, `LoadMoreItemsResult`, `IAsyncOperation<T>`), which are just not available from purely .NET projects at all. We'd need a dependency on WinAppSDK and WinUI 3 to access those APIs, and that's unfortunately not something we can do in the .NET Community Toolkit, as being completely framework-agnostic is one of its core principles. This API seems best suited for a separate package outside of the .NET Community Toolkit. Perhaps the [Windows Community Toolkit](https://github.com/CommunityToolkit/WindowsCommunityToolkit) might be a good fit for a proposal like this? 🙂
