### ISSUE TITLE
Observable property attribute with negative enum values gives cast error

### ISSUE THREAD

**Issue by n-coelho-cerinnov** [CommunityToolkit/dotnet#731]
### Describe the bug

After updating my project that as an observable property with a negative enum attribute to version 8.2.1, I still have an error when I try to use the enum. As a workaround I've been using a literal value to suppress the error.
Before, in version 8.2.0, the source generators stopped working. In version 8.2.1 it gives the errors:

- To cast a negative value, you must enclose the value in parentheses.
- 'NegativeEnum' is a type, which is not valid in the given context.

This bug can be easily reproduced with the code below.

### Steps to reproduce

This bug occurred when I tested in .NET 7 in a WPF project with both Visual Studio 17.6.4 and 17.7.0 Preview 2.0 and the latest CommunityToolkit.Mvvm 8.2.1. It probably would happen with other versions.
Using the following code the bug can be reproduced:
```csharp
using CommunityToolkit.Mvvm.ComponentModel;
using System.ComponentModel;

namespace MvvmBug;
public partial class MainViewModel : ObservableObject
{
    [ObservableProperty]
    private bool _test1;

    [ObservableProperty]
    [property: DefaultValue(PositiveEnum.Something)]
    private PositiveEnum _test2;

    [ObservableProperty]
    [property: DefaultValue(NegativeEnum.Problem)]
    private NegativeEnum _test3;

    [ObservableProperty]
    private int _test4;

    public MainViewModel()
    {
        Test1 = true;
        Test2 = PositiveEnum.Else;
    }
}

public enum PositiveEnum
{
    Something = 0,
    Else = 1
}

public enum NegativeEnum
{
    Problem = -1,
    OK = 0
}
```

Changing the default value for _test3 to NegativeEnum.OK will allow the code to compile without errors, changing back to NegativeEnum.Problem and the errors described above occur.
Also note that if using the NegativeEnum.Problem, removing the 'property:' before the DefaultValueAttribute doesn't seem to have the problem. It only occurs for attributes passed to the property generated.

### Expected behavior

An enum with a negative value in a property attribute shouldn't give a cast error.

### IDE and version

VS 2022, VS 2022 Preview

### IDE version

17.6.4, 17.7.0 Preview 2.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.2.1

### Additional context

This is a continuation of the problem reported in issue #681.

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
Oh, good catch! Mmh this is weird that the unit tests didn't spot the error 🤔

I have these test attributes that clearly are using the wrong syntax (missing parentheses):

https://github.com/CommunityToolkit/dotnet/blob/e071ed22b379f904820475db827be3ad04d3e96e/tests/CommunityToolkit.Mvvm.SourceGenerators.UnitTests/Test_SourceGeneratorsCodegen.cs#L1352-L1355

But then the test runner below isn't producing any diagnostics for it (it's missing those CS0075 errors):

https://github.com/CommunityToolkit/dotnet/blob/e071ed22b379f904820475db827be3ad04d3e96e/tests/CommunityToolkit.Mvvm.SourceGenerators.UnitTests/Test_SourceGeneratorsCodegen.cs#L2412-L2416

@Youssef1313 any ideas why the generator driver might not be reporting all compiler errors here by any chance? 😅

**Comment by Youssef1313** [comment]
@Sergio0694 I think you should be getting the diagnostics from `outputCompilation`
