### ISSUE TITLE
MissingMethodException with netstandard2.0 target

### ISSUE THREAD

**Issue by jzebedee** [CommunityToolkit/dotnet#74]
### Describe the bug

When a `netstandard2.0` library with a dependency on `Microsoft.Toolkit.HighPerformance` uses certain extension methods such as `StreamExtensions.Write(Stream,ReadOnlySpan<Byte>)`, it can lead to unexpected runtime failures with a `System.MissingMethodException` when run on a target that has `SPAN_RUNTIME_SUPPORT`.

Example: Class library multitargets `net6.0` and `netstandard2.0`:
```csharp
using Microsoft.Toolkit.HighPerformance;

//problem call:
Span<byte> header;
Stream output;
output.Write(header);
```

This call will compile successfully, with the `net6.0` target using the native `Stream.Write` overload and the `netstandard2.0` target using the WCT extension.

However, when this library is run on a platform that has `SPAN_RUNTIME_SUPPORT` defined, e.g., `netcoreapp3.1` or `net5.0`, it will fail at runtime with the following exception:
```
System.MissingMethodException : Method not found: 'Void Microsoft.Toolkit.HighPerformance.StreamExtensions.Write(System.IO.Stream, System.ReadOnlySpan`1<Byte>)
```

This appears to be due to the preprocessor directive that only generates the `StreamExtensions.Write(Stream,ReadOnlySpan<Byte>)` when `SPAN_RUNTIME_SUPPORT` is false.

https://github.com/CommunityToolkit/WindowsCommunityToolkit/blob/da6d7d3f6ca9914dbe86d7d394e9a4abef25c9b6/Microsoft.Toolkit.HighPerformance/Extensions/StreamExtensions.cs#L22

### Reproducible in sample app?

- [X] This bug can be reproduced in the sample app.

### Steps to reproduce

```text
1. In a `netstandard2.0` class library, use a WCT extension method that is dependent on the `SPAN_RUNTIME_SUPPORT` directive
2. Run the class library on a pre-`net6.0` target that includes `SPAN_RUNTIME_SUPPORT`
3. Observe `MissingMethodException`
```

### Expected behavior

Runtime light-up instead of silent failure: forward calls to the underlying `Stream.Write` implementation when `SPAN_RUNTIME_SUPPORT` is present.

### Nuget packages

* `Microsoft.Toolkit.HighPerformance` version 7.1.2

### Help us help you

Yes, I'd like to be assigned to work on this item.

**Comment by Sergio0694** [comment]
Good catch! I've assigned this to you as you mentioned you'd like to help 😊

**Comment by tsuckow** [comment]
I suspect this is an issue with how .net resolves dependencies.

Based on this repro
https://github.com/tsuckow/NetStandard21MissingMethodRepro

It appears that if a .net6 application depends on a .netstandard2.0 library that in turn has a dependency on a multi-targeted library that has differences from .netstandard2.0 to .netstandard2.1+ (IAsyncEnumerable in the case of Alethic.Kademlia) then the application will pull in the 2.1 version of the nested dependency even though it is incompatible with the .netstandard2.0 library. It wont even result in a compiler error, just runtime!

![image](https://user-images.githubusercontent.com/262439/147682476-1f9d2335-ee92-4077-8716-07e53e75723a.png)

**Comment by Sergio0694** [comment]
Yeah that is the expected behavior, NuGet package resolution will always pull the best match for referenced packages, including transitive dependencies. This is why adding new APIs in more recent targets is fine, but removing them is a binary breaking change, like in this case. This one just slipped under our radar and we missed it 😄

**Comment by jzebedee** [comment]
I've created a simple repro binary, added it to the StreamExtensions test case, and verified that forwarding these APIs to the `stream.Write` implementation fixes the `MissingMethodException`:

https://github.com/jzebedee/dotnet/tree/fix_spanruntimesupport_missingmethodexception

**Comment by jzebedee** [comment]
Some questions to get this PR-ready:

- Where should I put the test binary? (`.Aliased`)
- Do we need to verify this for all APIs that were behind `SPAN_RUNTIME_SUPPORT` / `NETSTANDARD2_1_OR_GREATER` checks? I only spotted this with the `StreamExtensions`.
- Should the replacement APIs be copy-pasted from the existing ones, with all comments? Should they do anything other than forward to the underlying API when running on a supported platform?

**Comment by Sergio0694** [comment]
> "Where should I put the test binary? (.Aliased)"

I don't think adding a test project just for this is necessary. Just add the polyfills for those methods as well 👍

> "Do we need to verify this for all APIs that were behind SPAN_RUNTIME_SUPPORT / NETSTANDARD2_1_OR_GREATER checks?"

Possibly, though I don't think there's many.
There's a case in `SpinLockExtensions` we might also want to fix, and one in `Ref<T>`, though that type is experimental so I don't think we necessarily have to fix that too. I'd just remove that API entirely (in a separate PR).

> "Should the replacement APIs be copy-pasted from the existing ones, with all comments? Should they do anything other than forward to the underlying API when running on a supported platform?"

They should just directly proxy to the new APIs in the BCL.

**Comment by Sergio0694** [comment]
Hey @jzebedee, are you still interested in taking this one? 🙂
