### ISSUE TITLE
[BUG] RelayCommand with parameter for menuItem / contextAction on windows

### ISSUE THREAD

**Issue by SamuelJames101** [CommunityToolkit/dotnet#766]
### Describe the bug

I have created a ListView.
Created context actions.
If a menu item in the context action points to a [RelayCommand] which takes a parameter then the list view items don't show.

Take away the parameter and it works.

Repo : https://github.com/SamuelJames101/comtoolkitIssueMaui

### Steps to reproduce

```text
1. Create a ListView
2. Populate the list
3. Add ContextActions
4. For one of the menu items point to a RelayCommand that requires a parameter.
```

### Expected behavior

A ListView item pointer to a RelayCommand should show with or without a paramater.

### Screenshots

![Screenshot 2023-10-02 at 10 26 27](https://github.com/CommunityToolkit/Maui/assets/44027336/d3296b8c-238d-4de3-a51d-c0a3ffa5d2c9)

### IDE and version

VS 2022 Preview

### IDE version

17.8.0 Preview 1.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.2.1

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
There isn't really anything that looks wrong in that viewmodel, and I'm not familiar with the MAUI syntax at all. It's not clear at all that there's any problem with the MVVM Toolkit here, unless proven otherwise. This should be in the MAUI repo 🙂

I will close this, but feel free to share a minimal repro and I can reopen this. Until then, this seems more likely to either be some bug in the XAML code there, or some bug in MAUI. That viewmodel just seems completely fine to me.

**Comment by SamuelJames101** [comment]
If I bind to a normal Microsoft.maui.controls.command it works. It also isn't just me : https://stackoverflow.com/questions/76681900/binding-contextactions-menuitem-with-communitytoolkit-mvvm-in-maui

**Comment by Sergio0694** [comment]
Can you reproduce the same issue if you manually declare the command? Ie. not using `[RelayCommand]`, but rather defining a command property yourself and having it return the appropriate `RelayCommand` instance. Does that work? 🤔

**Comment by SamuelJames101** [comment]
This results in the exact same result as the screen shot

```
    public MainPageViewModel()
    {
        this.MyNormalCommand = new RelayCommand<string>(this.MyMenuItemMethodParameter);
    }

    public RelayCommand<string> MyNormalCommand { get; set; }
```
