### ISSUE TITLE
OnPropertyChanged cannot rise the exception

### ISSUE THREAD

**Issue by ali50m** [CommunityToolkit/dotnet#781]
### Describe the bug

I tried to raise exception in the partial OnPropertyChanged method, but the exception cannot be caught in "Start without debugging" mode. This issue during I report a similar issue to fody/PropertyChanged(https://github.com/Fody/PropertyChanged/issues/993). However, I found this issue also happen to "CommunityToolkit.Mvvm".

### Steps to reproduce

repo: 
https://github.com/ali50m/FodyOnChangedMethodIssue/tree/toolkit

VM Code:

```csharp
internal partial class MainViewModel : ObservableObject
{
    [ObservableProperty]
    private int _input;

    [ObservableProperty]
    private string _output = "0";

    partial void OnInputChanged(int value)
    {
        if (Random.Shared.Next(10) > 5)
        {
            throw new InvalidOperationException();
        }
        Output = $"{value}";
    }
}
```

View code:
```xml
    <Window.DataContext>
        <fodyOnChangedMethodIssue:MainViewModel />
    </Window.DataContext>
    <StackPanel>
        <TextBox Text="{Binding Input, UpdateSourceTrigger=PropertyChanged}" />
        <TextBlock Text="{Binding Output}" />
    </StackPanel>
```

### Expected behavior

Exception can be thrown or caught. Or it is a potential weakness for the application.

### Screenshots
![screenshots](https://github.com/ali50m/FodyOnChangedMethodIssue/assets/9393831/8b574b19-55c3-4af8-9ebb-48e7c673cdd2)

### IDE and version

VS 2022 Preview

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [ ] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

CommunityToolkit.Mvvm v8.2.2

### Help us help you

No, just wanted to report this

**Comment by JochenMader** [comment]
Hi there

As mentioned in your [Fody issue](https://github.com/Fody/PropertyChanged/issues/993#issuecomment-1784155626) the Exception is eaten by the Binding. So this seems to me as expected behavior.
The Exception can be handled with the [DispatcherUnhandledException Event](https://learn.microsoft.com/en-us/dotnet/api/system.windows.application.dispatcherunhandledexception?view=windowsdesktop-7.0). See also here: [Handling exceptions in WPF](https://wpf-tutorial.com/wpf-application/handling-exceptions/)

best regards

**Comment by JochenMader** [comment]
@ali50m 
I told you something wrong. With the DispatcherUnhandledException event you can catch **unhandled** exceptions in the application. But exceptions, that occur in the wpf binding, are allready handled. But there is also a solution for this. I found this one:
[How can I turn binding errors into runtime exceptions?](https://stackoverflow.com/questions/4225867/how-can-i-turn-binding-errors-into-runtime-exceptions)
