### ISSUE TITLE
Executing RelayCommand throws System.MethodAccessException: Attempt by method

### ISSUE THREAD

**Issue by Symbai** [CommunityToolkit/dotnet#804]
### Describe the bug

I'm trying to figure out how to use a simple command which canexecute depends on a bool property. Unfortunately the sample application is heavily outdated as there are like 3 different ways of how to setup a command. And all of them are missing the canexecute step.

This is the exception I receive:
```
Unhandled exception. System.MethodAccessException: Attempt by method 'CompiledAvaloniaXaml.XamlIlTrampolines.xxx:xxx.ViewModels.MainWindowViewModel+LoginCommand_0!CommandExecuteTrampoline(System.Object, System.Object)' to access method 'xxx.ViewModels.MainWindowViewModel.LoginCommand()' failed.
   at CompiledAvaloniaXaml.XamlIlTrampolines.xxxx:xxx.ViewModels.MainWindowViewModel+LoginCommand_0!CommandExecuteTrampoline(Object, Object)
```

Anyway please see code below. Any help is appreciated

### Steps to reproduce

```text
.NET 7
Avalonia

#
[ObservableProperty]
bool isNotLoggingIn = true;

[RelayCommand(CanExecute = nameof(IsNotLoggingIn))]
private async Task LoginCommand()
{
	IsNotLoggingIn = false;
	await Task.Delay(5000);
	IsNotLoggingIn = true;
}
```

### Expected behavior

When I press the button the button should get disabled and after 5 seconds get enabled. But pressing the button throws the exception above.

### IDE and version

VS 2022 Preview

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.2.2

### Help us help you

No, just wanted to report this

**Comment by passion729** [comment]
Try to make the `LoginCommand()` method to `public`, it worked for me.

**Comment by chuongmep** [comment]
> Try to make the `LoginCommand()` method to `public`, it worked for me.

This give me resolve the issue too, thank you !
