### ISSUE TITLE
       [RelayCommand] attribute causes 	CS0260	类型“MainViewModel”的声明上缺少 partial 修饰符；存在此类型的其他分部声明	

### ISSUE THREAD

**Issue by tangmanger** [CommunityToolkit/dotnet#819]
### Describe the bug

When using [ReplayCommand] to mark a method in MainViewModel, there is a cs0260 error prompt when compiling 

### Steps to reproduce

```text
platform:.net 6
    [RelayCommand]
    public void Loaded()
    {

    }
```

### Expected behavior

Normal compilation passed

### Screenshots

![QQ截图20240105225312](https://github.com/CommunityToolkit/dotnet/assets/19483519/197318aa-ffbc-4868-b8f7-76f057c43df9)

### IDE and version

VS 2022

### IDE version

17.8.3

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.2.1

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by Sergio0694** [comment]
This is not a bug, it's by design. The error message is telling you what the issue is. You forgot to add `partial` to your class 🙂
Just make `MainViewModel` a `partial class` and this will work fine.
