### ISSUE TITLE
Fast unboxing of Box<T> value without unnecessary type checking

### ISSUE THREAD

**Issue by AlexRadch** [CommunityToolkit/dotnet#822]
### Overview

Box<T> uses a slower unboxing process, making sure that the instance can be converted to type T. However, since the instance creation guarantees that the correct type of value is enclosed, we can make the unboxing methods quicker by eliminating the unnecessary type checking.

### API breakdown

```csharp
public sealed class Box<T>
    where T : struct
{
+    internal readonly T value; // used for fast unboxing

    public static implicit operator T(Box<T> box)
        => box.value; // Fast unboxing without type checking
}

public static class BoxExtensions
{
    public static ref T GetReference<T>(this Box<T> box) where T : struct
        => ref Unsafe.AsRef(box.value); // Fast unboxing without type checking
}
```

### Usage example

The same as before but faster.

### Breaking change?

No

### Alternatives

I don't know.

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by Sergio0694** [comment]
Closing this, as the proposed functionality would be explicitly relying on undefined behavior, hence not being safe. We do not want to introduce any APIs in the .NET Community Toolkit that is not safe and with well defined behavior, and we're removing all existing occurrences of APIs not respecting that (`Box<T>` is mostly the only case left). Thank you!
