### ISSUE TITLE
[Feature] `Enumerable.None` (aka !Any)

### ISSUE THREAD

**Issue by maxkoshevoi** [CommunityToolkit/dotnet#83]
What do you think about adding `None` LINQ method to complement `Any`?

Main reason is that I see good amount of code that checks for empty collections like this. Which is not very readable.
```cs
if (!someLongCollectionName.Any())
```

As for other benefits. Third condition reads much better:
```cs
!arr.Any(i => i == 5)
arr.All(i => i != 5)
arr.None(i => i == 5)
```

This question was already raised multiple times for main SDK, and got rejected there: https://github.com/dotnet/runtime/issues/27661, https://github.com/dotnet/runtime/discussions/54743
But for Toolkit it makes even more sense.

**Comment by MisinformedDNA** [comment]
[MoreLinq](https://github.com/morelinq/MoreLINQ/issues/203) was opposed to it as well since a) [Linq.Extras](https://github.com/thomaslevesque/Linq.Extras/blob/master/src/Linq.Extras/None.cs) already has an implementation and b) users can easily create this extension method on their own.

**Comment by Sergio0694** [comment]
I don't think we should add this, for the same reasons Stephen mentioned when he rejected the proposal in the runtime. I'm not a fan of having one-liners that just proxy to an existing method like this, except for very specific cases. Not to mention:

```csharp
if (!someLongCollectionName.Any())
```

This example doesn't look rigth in the first place and definitely looks like something you shouldn't use anyway.
If that collection has a fixed count, you should access that. If it doesn't, then this is extremely inefficient and potentially bad.

**Comment by MisinformedDNA** [comment]
I agree with not implementing this, but I disagree about the example looking wrong.

If the collection is fixed, `Any` is more expressive than comparing against `Count`. If not, `Any` is more efficient than `Count`, because `Any` only needs to look for the first instance, not all of them.
