### ISSUE TITLE
Set PropertyChanged methods protected

### ISSUE THREAD

**Issue by Pantheas** [CommunityToolkit/dotnet#836]
### Overview

It would be nice if the following methods could get a `protected` modifier instead of `private` so these methods can be accessed from derived classes aswell.
I have scenarios in which I define common properties tagged with `[ObservableProperty]` in a base class. However, if I want to react on changes from a derived class I currently have to implement a wrapping method just to modify the accessibility.

```csharp
partial void On[PropertyName]Changing(global::[PropertyType] value);
partial void On[PropertyName]Changing(global::[PropertyType] oldValue, global::[PropertyType] newValue);
partial void On[PropertyName]Changed(global::[PropertyType] value);
partial void On[PropertyName]Changed(global::[PropertyType] oldValue, global::[PropertyType] newValue)
```
### API breakdown

```csharp
protected partial void On[PropertyName]Changing(global::[PropertyType] value);
protected partial void On[PropertyName]Changing(global::[PropertyType] oldValue, global::[PropertyType] newValue);
protected partial void On[PropertyName]Changed(global::[PropertyType] value);
protected partial void On[PropertyName]Changed(global::[PropertyType] oldValue, global::[PropertyType] newValue);
```

### Usage example

```csharp
public partial abstract class ViewModelBase :
    ObservableObject
{
    [ObservableProperty]
    private bool isInitialized = false;
}

public partial class SomeDerivedViewModel :
    ViewModelBase
{
    protected partial void OnIsInitializedChanged(
        bool value)
    {
        // do something that should happen when this property value changed...
    }
}
```

### Breaking change?

No

### Alternatives

```csharp
public partial abstract class ViewModelBase :
    ObservableObject
{
    [ObservableProperty]
    private bool isInitialized = false;

    partial void OnIsInitializedChanged(
        bool value)
    {
        HandleIsInitializedChanged(
            value);
    }

    protected virtual void HandleIsInitializedChanged(
        bool value)
    {
    }

}

public partial class SomeDerivedViewModel :
    ViewModelBase
{
    protected override void HandleIsInitializedChanged(
        bool value)
    {
        // do something that should happen when this property value changed...
    }
}
```

### Help us help you

Yes, but only if others can assist
I have never worked with source generators so far.
However, I'm interesting in it and I am up to contribute a solution with some assistance.

**Comment by weitzhandler** [comment]
I find this to be very compelling.
Please enable customization of the `ObservableProperty`, by adding some properties to it, to control accessibility modifiers of its methods, as well as making it virtual, to enable inheriting classes to override and intercept the changing/ed calls.

**Comment by Sergio0694** [comment]
This is not doable, as adding an accessibility modifier to a partial method without implementation makes it required to implement it. Right now, the point is that you only implement the ones you need (which is also why there's multiple overloads that are generated). If we added `protected`, you'd be forced to always implement all those 4 methods for each single property you have, even if you don't actually need them at all.
