### ISSUE TITLE
Add Custom Attribute Support for Properties Auto-Generated by [ObservableProperty]

### ISSUE THREAD

**Issue by Lwc-LiuWenCheng** [CommunityToolkit/dotnet#854]
### Describe the problem

I propose adding support for custom attributes on properties auto-generated by the [ObservableProperty] in the .NET Community Toolkit. Currently, properties auto-generated using [ObservableProperty] do not support attaching additional attributes directly, limiting their application in scenarios like data validation or UI mapping.

### Describe the solution

When using [ObservableProperty], there should be a way to attach additional attributes to the generated properties, rather than manually writing out the full properties.
In many cases, we need to attach specific attributes to properties of a data model for data validation, serialization control, or specific UI behaviors. For instance, we might want to use [DataAnnotations] attributes for validating data models, or custom attributes to control how columns are displayed.

### Help us help you

None

**Comment by JonAdamsFromNC** [comment]
In my experience, doing the following has worked:
[property:Required]

Inspecting the generated code, the property inherits the attribute.

**Comment by rrickgauer** [comment]
You can do that here: 

https://learn.microsoft.com/en-us/dotnet/communitytoolkit/mvvm/generators/observableproperty#adding-custom-attributes

**Comment by Sergio0694** [comment]
Closing this, as it's already supported 🙂
