### ISSUE TITLE
ObservableProperty attribute with specific accessor

### ISSUE THREAD

**Issue by AignerGames** [CommunityToolkit/dotnet#860]
### Overview

Currently the generated property will have public getter and setter. 
It would be nice to be able to control the accessor type (internal, private, etc) with the attribute. 

Sometimes I want public getter but only internal setter, then I can't use the attribute and have to write the code myself again. 

### API breakdown

ObservableProperty(AccessorType setterAcccesorType = AccessorType.Public)

### Usage example

[ObservableProperty(setterAcccesorType: AccessorType.Private)]
private string? name;

### Breaking change?

No

### Alternatives

Manually add a property with public getter which returns a manually declared private field and manually handled the property changed events inside the private setter

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment]
Duplicate of #291.
Superseded by #555.
