### ISSUE TITLE
Allow generating observable properties with private setters

### ISSUE THREAD

**Issue by mikernet** [CommunityToolkit/dotnet#896]
### Overview

Would be nice if you could generate observable properties with private setters. Many observable properties should only be privately settable.

### API breakdown

Add the following property to `ObservablePropertyAttribute`:

```cs
public bool PrivateSetter { get; set; }
```

### Usage example

```cs
public partial class MyViewModel : ObservableObject
{
    [ObservableProperty(PrivateSetter = true)]
    private bool _isLoaded;

    public async Task LoadAsync()
    {
        Data = await ...;
        IsLoaded = true;
    }
}
```

### Breaking change?

No

### Alternatives

None

### Help us help you

No, just wanted to propose this

**Comment by Sergio0694** [comment]
Duplicate of #291.
Superseded by #555.
