### ISSUE TITLE
Generic RelayCommandAttribute's?

### ISSUE THREAD

**Issue by Shadowblitz16** [CommunityToolkit/dotnet#904]
### Overview

I need to pass parameters to the relay command
```
    [RelayCommand<KeyEventArgs>]
    private void CanvasKeyDown(object sender, KeyEventArgs args)
    {
        if (args.Source is ZoomBorder panAndZoom)
        {
            if (args.Key == Key.Up) panAndZoom.PanDelta(0, -16);
            if (args.Key == Key.Down) panAndZoom.PanDelta(0, +16);
            if (args.Key == Key.Left) panAndZoom.PanDelta(-16, 0);
            if (args.Key == Key.Right) panAndZoom.PanDelta(+16, 0);
        }
    }
```

### API breakdown

The api would be similar to Action and Func

### Usage example

```cs
    [RelayCommand<KeyEventArgs>]
    private void CanvasKeyDown(object sender, KeyEventArgs args)
    {
        if (args.Source is ZoomBorder panAndZoom)
        {
            if (args.Key == Key.Up) panAndZoom.PanDelta(0, -16);
            if (args.Key == Key.Down) panAndZoom.PanDelta(0, +16);
            if (args.Key == Key.Left) panAndZoom.PanDelta(-16, 0);
            if (args.Key == Key.Right) panAndZoom.PanDelta(+16, 0);
        }
    }
```

### Breaking change?

I'm not sure

### Alternatives

Reactive ui

### Additional context

I am binding it to Avalonia's PanAndZoom's ZoomBorder's MouseDown event

### Help us help you

No, just wanted to propose this

**Comment by Sergio0694** [comment]
If you do:

```csharp
[RelayCommand]
private void CanvasKeyDown(KeyEventArgs args)
{
}
```

The generator will already create a generic command with `KeyEventArgs` as input. Is that not sufficient in your scenario?

**Comment by Shadowblitz16** [comment]
Hmm still getting errors, maybe it's a problem with out it's used...
```xml
...
<pz:ZoomBorder KeyDown="{Binding CanvasKeyDownCommand}" ...
```

Is this not correct in a mvvm application?

**Comment by Sergio0694** [comment]
Yeah that's not valid, you cannot bind an event to a command. I'm not familiar with Avalonia, but does that control not have a `Command` property? Alternatively, you might use something like an attached property or a XAML behavior to dynamically bind that command to the control and have it invoke the command whenever the event is raised, and pass the arts accordingly 🙂

Closing this as it's unrelated from the generator itself.
