### ISSUE TITLE
Option to enable `required` on a property generated by `ObservableProperty`

### ISSUE THREAD

**Issue by JochemPalmsens** [CommunityToolkit/dotnet#913]
### Overview

Currently there is no option to add the `required` keyword to the property generated by the `ObservableProperty`. This is unwanted, because `required` is there for a reason: in many cases it's not correct for a property to ever be null[able] (The whole nullable/init/require stuff is really usefull in creating a safe application, so it would be weird not to support it).

So I suggest an option to enable `required` on the generated property is added.

### API breakdown

```csharp
[AttributeUsage(AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
public sealed class ObservablePropertyAttribute : Attribute
{
    public bool IsRequired { get; set; }
}
```

### Usage example

```csharp
public sealed partial class MyType : ObservableObject
{
    [ObservableProperty(IsRequired = true]
    private string name;
}
```

### Breaking change?

No

### Alternatives

Alternatively? Maybe a separate attribute `RequiredObservablePropertyAttribute`?

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment]
Closing this, superseded by #555.

**Comment by JochemPalmsens** [comment]
Ah, and now see it's a dupe of #679
thx
