### ISSUE TITLE
Mvvm 8.3.0: Wrong windows runtime?

### ISSUE THREAD

**Issue by marco-skizza** [CommunityToolkit/dotnet#928]
### Describe the bug

Hi

When including...

```xml
<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.0" />
```

...in a sample .NET MAUI 8 project, when building for windows I get the following warnings:

```
warning MSB3277: Found conflicts between different versions of "WinRT.Runtime" that could not be resolved.
warning MSB3277: There was a conflict between "WinRT.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" and "WinRT.Runtime, Version=2.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709".
```

It seems that this NuGet uses the windows runtime `net8.0-windows10.0.17763`.

Is this correct?
Because .NET MAUI 8 projects use `net8.0-windows10.0.19041.0`:

```xml
<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>
```

But maybe there's even another reason for this build warnings.
Besides, with version `8.2.2` of the NuGet everything was ok...

See also: https://github.com/CommunityToolkit/Maui/issues/2162

### Regression

8.2.2

### Steps to reproduce

```text
1. Build the project from the repo for windows
```

### Expected behavior

No build warnings.

### IDE and version

VS 2022

### IDE version

17.11.2

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.3.0

### Help us help you

No, just wanted to report this

**Comment by marco-skizza** [comment]
Thanks! I think I'll wait then for the new SDK to come out... 😅

**Comment by Balkoth** [comment]
> Duplicate of #923, the workaround is in [#923 (comment)](https://github.com/CommunityToolkit/dotnet/issues/923#issuecomment-2314444048) 🙂
> 
> The issue is you're using a .NET SDK that's not been updated yet with the new Windows SDK projections.

The issue is you are using something that seems not the be available to the public. Why break this for all users of this library and not wait until the tools are finally around? Theres almost a year between 8.2.2 and 8.3.0 and you feel the need to release now?
