### ISSUE TITLE
canExecute AsyncRelayCommand

### ISSUE THREAD

**Issue by Scharps** [CommunityToolkit/dotnet#93]
Hello,

When using an AsyncRelayCommand, how can I get the canExecute function to be checked immediately after the command is fired so that the command cannot be fired again until the command has finished executing?

Thanks!

**Comment by Sergio0694** [comment]
This is supported out of the box with the new `allowConcurrentExecutions` parameter (https://github.com/CommunityToolkit/dotnet/pull/30).
Set that to `false` when creating a command, and concurrent operations will be skipped.
The `CanExecute` logic will also reflect this 🙂
