### ISSUE TITLE
Source Generators do not work at all in Visual Studio 2019

### ISSUE THREAD

**Issue by RB275** [CommunityToolkit/dotnet#945]
### Describe the bug

The Source Generators do not work at all in VS2019, while they work properly in VS2022. 

### Steps to reproduce

```text
1 ) Create a project that target should be compatible with the generators (my target is net472 for this project I'm working on)
2) Add in some properties and methods, mark with appropriate attributes, such as [RelayCommmand]
3) Attempt to compile in vs2022 - this works fine
4) Attempt to compile in vs2019 - Fails because nothing is generated.
```

### Expected behavior

The attributes will trigger the generation of relevant properties.
- Note that SOME source generators have notes that you must target .net5 or newer to trigger them, but they work for all targets as long as .net5 is targeted as well. This had no effect on the result in this scenario.

### Screenshots

VS 2019 : 
![image](https://github.com/user-attachments/assets/03ab1a00-01d0-444e-82c8-ee22cf67d39e)

### IDE and version

VS 2019

### IDE version

Version 16.11.35

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.2.2

### Help us help you

Yes, but only if others can assist

**Comment by RB275** [comment]
Minimum Reproducible:

CSProj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net5.0</TargetFrameworks>
      <LangVersion>9</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
  </ItemGroup>

</Project>
```


Class.cs

```cs
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using System;

namespace VS2019SourceGeneratorTest
{
    public partial class Class1 : ObservableObject
    {
        [NotifyCanExecuteChangedFor(nameof(DoSomethingCommand))]
        [ObservableProperty]
        private bool _isAllowed;

        [RelayCommand(CanExecute =nameof(IsAllowed))]
        private void DoSomething() { }
    }
}
```

**Comment by Sergio0694** [comment]
This is expected, the generators require Roslyn 4.x, which is included in VS2022 only.

Are you not getting a warning in the output about this? You should be seeing one.
Let me know if it's not showing up!

**Comment by RB275** [comment]
This is unfortunate, but the warning does appear. 
After poking through the repo and seeing about implementing it myself, i can see why it wasn't planned. The use of the incremental generator isn't available for Roslyn311, and would effectively require duplicating the code for each attribute to rewrite it using the 'ISourceGenerator' interface instead of the 'IncrementalGenerator'. (but also, because multiple attributes exist it would basically be a major rewrite from what I can tell, since all attributes would have to be checked for)
I was hoping that it was something achievable since VS2019 is supported until 2029, but oh well.
