### ISSUE TITLE
Unable to update & build also with 8.3.1 (as like as removed 8.3.0)

### ISSUE THREAD

**Issue by LucaCris** [CommunityToolkit/dotnet#950]
### Describe the bug

This update:

![immagine](https://github.com/user-attachments/assets/5cd394d6-a422-4f45-b79d-8a7b5579d3d6)

cannot executed seamlessly.

See additional content for some warns/errors issued.

### Regression

Upto 8.2.2

### Steps to reproduce

```text
Perform standard nuget upgrade, as usual.
```

### Expected behavior

Update-Build-Happy

### IDE and version

VS 2022

### IDE version

17.11.3

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [X] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.2.2

### Additional context

\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277: Found conflicts between different versions of "WinRT.Runtime" that could not be resolved.
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277: There was a conflict between "WinRT.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" and "WinRT.Runtime, Version=2.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709".
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:     "WinRT.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" was chosen because it was primary and "WinRT.Runtime, Version=2.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" was not.
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:     References which depend on "WinRT.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" [C:\Users\Luca\.nuget\packages\microsoft.windows.sdk.net.ref\10.0.22621.34\lib\net6.0\WinRT.Runtime.dll].
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         C:\Users\Luca\.nuget\packages\microsoft.windows.sdk.net.ref\10.0.22621.34\lib\net6.0\WinRT.Runtime.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\Luca\.nuget\packages\microsoft.windows.sdk.net.ref\10.0.22621.34\lib\net6.0\WinRT.Runtime.dll".
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windows.sdk.net.ref\10.0.22621.34\lib/net6.0/WinRT.Runtime.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:     References which depend on or have been unified to "WinRT.Runtime, Version=2.1.0.0, Culture=neutral, PublicKeyToken=99ea127f02d97709" [].
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         C:\Users\Luca\.nuget\packages\communitytoolkit.mvvm\8.3.1\lib\net8.0-windows10.0.17763\CommunityToolkit.Mvvm.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\Luca\.nuget\packages\communitytoolkit.mvvm\8.3.1\lib\net8.0-windows10.0.17763\CommunityToolkit.Mvvm.dll".
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\communitytoolkit.mvvm\8.3.1\lib\net8.0-windows10.0.17763\CommunityToolkit.Mvvm.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             D:\Src\XLB\EagleDesigner\EagleDesigner\EagleCore\bin\Debug\net8.0\EagleCore.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.InteractiveExperiences.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.InteractiveExperiences.Projection.dll".
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.InteractiveExperiences.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.WinUI.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.WinUI.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.WinUI.dll".
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.WinUI.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppLifecycle.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppLifecycle.Projection.dll".
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppLifecycle.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Builder.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Builder.Projection.dll".
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Builder.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Projection.dll".
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.AppNotifications.Builder.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.dll".
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.DynamicDependency.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Management.Deployment.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.Resources.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.Resources.Projection.dll".
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.Resources.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.WinUI.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll".
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Management.Deployment.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Management.Deployment.Projection.dll".
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Management.Deployment.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.PushNotifications.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.PushNotifications.Projection.dll".
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.PushNotifications.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Security.AccessControl.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Security.AccessControl.Projection.dll".
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Security.AccessControl.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.System.Power.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.System.Power.Projection.dll".
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.System.Power.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.System.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.System.Projection.dll".
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.System.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:         C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Widgets.Projection.dll
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:           Project file item includes which caused reference "C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Widgets.Projection.dll".
\amd64\Microsoft.Common.CurrentVersion.targets(2412,5): warning MSB3277:             C:\Users\Luca\.nuget\packages\microsoft.windowsappsdk\1.5.240802000\lib\net6.0-windows10.0.18362.0\Microsoft.Windows.Widgets.Projection.dll
\.nuget\packages\communitytoolkit.mvvm\8.3.1\buildTransitive\CommunityToolkit.Mvvm.WindowsSdk.targets(70,5): error MVVMTKCFG0003: This version of the MVVM Toolkit requires 'Microsoft.Windows.SDK.NET.Ref' version '10.0.22621.38' or later. Please update to .NET SDK 8.0.109, 8.0.305 or 8.0.402 (or later). Alternatively, use a temporary 'Microsoft.Windows.SDK.NET.Ref' reference, which can be done by setting the 'WindowsSdkPackageVersion' property in your .csproj file. For your project configuration, it is recommended to set the package version to '10.0.22621.41'.

### Help us help you

No, just wanted to report this

**Comment by Sergio0694** [comment]
This is by design and not a bug. You can see the reason in the text you pasted:
> "This version of the MVVM Toolkit requires 'Microsoft.Windows.SDK.NET.Ref' version '10.0.22621.38' or later. Please update to .NET SDK 8.0.109, 8.0.305 or 8.0.402 (or later). Alternatively, use a temporary 'Microsoft.Windows.SDK.NET.Ref' reference, which can be done by setting the 'WindowsSdkPackageVersion' property in your .csproj file. For your project configuration, it is recommended to set the package version to '10.0.22621.41'."

Just do that to fix the issue 🙂
Let me know if you still hit this after following those instructions!
