### ISSUE TITLE
SetProperty doesn't raise PropertyChanged or ErrorsChanged when validation is OK

### ISSUE THREAD

**Issue by W4lm4s** [CommunityToolkit/dotnet#965]
### Describe the bug

Good afternoon,

The SetProperty<T> Isn't working as expected when error are cleared.
[https://github.com/CommunityToolkit/dotnet/blob/ba45963ed87527fac02b07855b24b90329bc9dd0/src/CommunityToolkit.Mvvm/ComponentModel/ObservableValidator.cs#L4](url)

Expected behavior can be seen in TrySetProperty => TryValidateProperty method, which raise an PropertyChanged and a ErrorsChanged event when error are cleared once the validation is OK.

About SetProperty, when the property transition from an error state to a non-error state, nothing is raised (nor errorchanged, nor propertychanged)

### Regression

I check history of the file, it seems to have always been

### Steps to reproduce

.NET 8 / MAUI / CommunityToolkit.Mvvm: Version="8.2.2"

Create a new project;
Create a class inheriting ObservableValidator (Name it TestEventProperty).
Add a string property (Name it MyString) and set it with `SetProperty(ref field, newValue, validate, propertyName)`
Add a required attribute on the property
Add delegate on PropertyChanged and ErrorsChanged with Debug.WriteLine instruction.

Create a new TestEventProperty() and set the required property to null.
Then Change its value to a valid string (like "AAA").

Notice the delegate not being invoked.

Example class : 
 public class TestEventProperty : ObservableValidator
 {
    private string? myString;
    [Required]
    public string? MyString
    {
        get => myString;
        set => SetProperty(ref myString, value, true);
    }
}

### Expected behavior

Same event behavior as for TrySetProperty<T>concerning error change and property event change

When transitionning from "HasErrors => true", to "HasErrors => false"
`OnPropertyChanged `should be raise if the ObservableValidator doesn't have error anymore.

The following line should be executed if it doesn't exists error for the concerned property and the concerned property had error previously => (isValid && hasErrors)
`ErrorsChanged?.Invoke(this, new DataErrorsChangedEventArgs(propertyName));`

Code example in `private bool TryValidateProperty(object? value, string propertyName, out IReadOnlyCollection<ValidationResult> errors)`

### IDE and version

VS 2022

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [x] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.2.2

### Additional context

Workaround : 

In a class inheriting ObservableValidator
```
        protected bool Set<T>([NotNullIfNotNull(nameof(newValue))] ref T field, T newValue, bool validate = true, [CallerMemberName] string propertyName = null!)
        {
            var hadError = GetErrors(propertyName).Any();
            var changed = SetProperty(ref field, newValue, validate, propertyName);

            //The ObservableWithErrors lack notification when there is no longer any error
            if (hadError && !GetErrors(propertyName).Any()) 
                OnPropertyChanged(nameof(HasErrors));

            return changed;
        }
```

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment]
This seems expected, there's no errors initially because the default value for the property is `null`, so when you set it to `null` nothing happens. You should run `ValidateAllProperties()` after constructing the model, if you want default values to report errors after creation.

**Comment by W4lm4s** [comment]
HI,

But my point is, I'm not setting it to null.
After the value change from null to "AAA" nothing happen, at this point, the value is not longer null and validation should trigger as for the TrySetProperty, I think.

**Comment by Sergio0694** [comment]
> "After the value change from null to "AAA" nothing happens"

I'm saying that _there was no error at first_. Yes the property was `null`, but you never asked the viewmodel to actually validate properties. Meaning there was no logged error, which is why when you set the property to a valid value, no event was raised. If you try validating the property after construction, then you will see the error being present, and the event being raised after setting the property.

**Comment by W4lm4s** [comment]
In the scenario described, an error had be already registered, becase HasError is set to true (due to null value).
Then setting a valid value (here a non-null string) the HasErrorsremains 'true', when it is expected to transition to 'false'.
And should raise a propertychanged event with the property name 'HasErrors'

I might be terribly bad at explaining, that why I'm refering to the TrySetProperty method which is behaving the expected way.

But in order : 
1 - error occured : haserrors == true
2 - not error anymore because string set to "aaa" haserrors == false and do not raise propertychanged or errorchanged
However the haserrors property changed

This part seems odd to me.
