### ISSUE TITLE
CS9257: "Both partial property declarations must be required or neither may be required" on a required partial property with [ObservableProperty]

### ISSUE THREAD

**Issue by nalka0** [CommunityToolkit/dotnet#969]
### Describe the bug

On main, the below code generates `public partial string Foo ...` which yields this error: 
> CS9257: "Both partial property declarations must be required or neither may be required" 

It should generate `public required partial string Foo ...` instead.

```cs
public partial class Test : ObservableObject
{
    [ObservableProperty]
    public required partial string Foo { get; set; }
}
```

### Steps to reproduce

1. Run `dotnet pack src/CommunityToolkit.Mvvm/CommunityToolkit.Mvvm.csproj` (on the current main)
2. Create a WPF App (.NET 8)
3. Install the package generated by step 1
4. Add `<LangVersion>preview</LangVersion>` to the .csproj
5. Create a class as follows:
```cs
using CommunityToolkit.Mvvm.ComponentModel;

namespace WpfApp1;

public partial class Test : ObservableObject
{
    [ObservableProperty]
    public required partial string X { get; set; }
}
```

### Expected behavior

```cs
public partial class Test : ObservableObject
{
    [ObservableProperty]
    public required partial string Foo { get; set; }
}
```

Generates `public required partial string Foo ...` instead of `public partial string Foo ...`

### IDE and version

VS 2022

### IDE version

17.11.5

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [x] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

main (8.4.0-build.11)

### Help us help you

Yes, but only if others can assist

**Comment by fraluderin** [comment]
I think you have replaced the expected behavior with the actual one. 

Given the following code:

```
public partial class Test : ObservableObject
{
    public required partial string? Foo { get; set; }
}
```

The expected generated code is:

```
public partial class Test
{
    private string? _foo;
    public required partial string? Foo
    {
        get => _foo;
        set => _foo = value;
    }
}
```
If the source generator "generates `public required partial string Foo` ... instead of `public partial string Foo` ...", that's the correct behaviour.

Or am I missing something?

**Comment by nalka0** [comment]
@fraluderin

> Or am I missing something?

I don't see where I'd have replaced the expected with the actual one, the sentence you seem to quote from me ("generates `public required partial string Foo ...` instead of `public partial string Foo ...`") is under "Expected behaviour" and I expect it to generate with required instead of without, which the quoted sentence says?

**Comment by fraluderin** [comment]
Apologies, I was from mobile and I did not ready correctly your comment. Sorry for that, I'm going to hide my previous comment since it's not applicable.

**Comment by Sergio0694** [comment]
Good point, yeah I still need to add support for required properties, since it wasn't an existing scenario before 🙂

**Comment by nalka0** [comment]
> Good point, yeah I still need to add support for required properties, since it wasn't an existing scenario before 🙂

@Sergio0694 Alright, since I picked "Yes, but only if others can assist" for **Help us help you**, does it mean I should just leave that issue for you? Or should I try to send a PR on this? (feel free to delete that once you reply to keep the issue clean)

**Comment by Sergio0694** [comment]
I've already fixed this in a branch and was about to open a PR, no worries! Thank you though! 🙂

> "Yes, but only if others can assist"

Yes but only if others can assist basically means "I'm willing to contribute this fix if needed". In this case I was just already doing a follow up with some other fixes here and there, so that was not necessary. It doesn't necessarily indicate you _have_ to contribute the fix yourself. I do appreciate it though! This reminds me I should create some "up for grabs" tag to mark items as welcoming contributions.

**Comment by nalka0** [comment]
> Yes but only if others can assist basically means "I'm willing to contribute this fix if needed". In this case I was just already doing a follow up with some other fixes here and there, so that was not necessary.

Alright I see, I was seeing it more like "I'm willing to try fixing it but am not sure I'll be able to do it completely on my own"
