### ISSUE TITLE
ConfigureAwait(true) in AsyncRelayCommand task

### ISSUE THREAD

**Issue by erikthysell** [CommunityToolkit/dotnet#97]
I wonder if it is possible to somehow use `.ConfigureAwait(true)` when firing a `AsyncRelayCommand ` so as to have property changes bubbeling up to view.. something like the following:

```
    public class MyViewModel:ObservableObject
    {
        private string _viewStatus = "";
        
        public IAsyncRelayCommand MyCommand { get; set; }
        public string ViewStatus { get => _viewStatus; set => SetProperty(ref _viewStatus,value); }
        private const bool _shouldConfigureAwaitTrue = true;
        
        public MyViewModel()
        {
            MyCommand = new AsyncRelayCommand(MyTask, CanExcecute, _shouldConfigureAwaitTrue);
        }

        private bool CanExcecute() => !MyCommand.IsRunning;

        private async Task MyTask()
        {
            for (int i = 0; i < 100; i++)
            {
                ViewStatus = "Now " + i + "%";
                await Task.Delay(100);
            }
        }
    }
```

I am bit unsure of what the best way is to bubble changes to view is from a task like this so any clues or advice this is most welcome.

**Comment by Arlodotexe** [comment]
@erikthysell If I understand correctly, you're having trouble updating `ViewStatus` because `MyTask` isn't executing on the UI thread?

@Sergio0694 Can correct me if I'm wrong, but AsyncRelayCommand doesn't do any dispatching, and keeps the default `Task.ConfigureAwait(true)` behavior, so as long as you're invoking the command from the UI thread, the task should also be on the UI thread.

**Comment by Sergio0694** [comment]
That is correct, I'm not sure I understand the issue here.
If you invoke the command on the UI thread (which would be the case if the command is eg. bound to a button), then everything there will keep running on the UI thread as well.

**Comment by michael-hawker** [comment]
I guess this is slightly different from our current doc/sample [here](https://docs.microsoft.com/en-us/windows/communitytoolkit/mvvm/asyncrelaycommand) where this is about progress reporting during the task execution. We should at least track this as a good sample request, even if everything is working as expected.

**Comment by erikthysell** [comment]
Sorry, the issue was mine, somehow the change wasn't bubbled up

**Comment by Sergio0694** [comment]
No worries, glad it's resolved! 🙂
