### ISSUE TITLE
MVVMTK0042's code fix provider replaces required fields with non-required properties

### ISSUE THREAD

**Issue by nalka0** [CommunityToolkit/dotnet#971]
### Describe the bug

On main, the below code triggers MVVMTK0042. Then if you use the "Use a partial property" suggestion, the replacing partial property isn't required while the field was.

```cs
partial class Test : ObservableObject
{
    [ObservableProperty] // MVVMTK0042 here
    internal required string foo; // Applying MVVMTK0042's suggestion makes it public partial string Foo { get; set; }, removing required
}
```

### Steps to reproduce

1. Run `dotnet pack src/CommunityToolkit.Mvvm/CommunityToolkit.Mvvm.csproj` (on the current main)
2. Create a WPF App (.NET 8)
3. Install the package generated by step 1
4. Add `<LangVersion>preview</LangVersion>` to the .csproj
5. Create a class as follows:
```cs
using CommunityToolkit.Mvvm.ComponentModel;

namespace WpfApp1;

partial class Test : ObservableObject
{
    [ObservableProperty]
    internal required string foo;
}
```
6. Apply the suggestion to fix MVVMTK0042 that happens on the above [ObservableProperty]

### Expected behavior

After applying the suggestion, `internal required string foo;` becomes `public required partial string Foo { get; set; }` instead of `public partial string Foo { get; set; }`

### IDE and version

VS 2022 Preview

### IDE version

17.12.0 Preview 4.0

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [x] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

8.4.0-build.15

### Help us help you

Yes, but only if others can assist

**Comment by Sergio0694** [comment]
I forgot that fields could also be required 😅
