### ISSUE TITLE
Multiple concurrent calls are possible even when the flag to allow concurrent calls is set to false

### ISSUE THREAD

**Issue by al3xmeister** [CommunityToolkit/dotnet#977]
### Describe the bug

The Execute method inside the AsyncRelayCommand class does not inherently prevent multiple concurrent calls, instead it focuses on changing the ChangeCanExecute and disable the ui executing the command. If however the ui is left enabled and the ChangeCanExecute is not made use of, firing multiple commands, in quick succession, is definitely possible. The same will happen if the command is called programmatically in quick succession. The only tested way to prevent this behaviour is to, when the  AllowConcurrentExecutions is set to false, lock the execution for the duration of its run, by setting a flag to true when execution starts and resetting it when execution completes.

### Steps to reproduce

1. Run the sample MAUI app in the community toolkit project
2. Execute a bound command to a button click that is not making use of the ChangeCanExecute in quick succession. Explicitly set the [AsyncRelayCommand(AllowConcurrentExecutions=false)] attribute 
3. Notice the command executes concurrently.

### Expected behavior

If the AllowConcurrentExecutions is set to false then the same command should not ever execute the logic concurrently.

### IDE and version

VS 2022

### Nuget packages

- [ ] CommunityToolkit.Common
- [ ] CommunityToolkit.Diagnostics
- [ ] CommunityToolkit.HighPerformance
- [x] CommunityToolkit.Mvvm (aka MVVM Toolkit)

### Nuget package version(s)

9.0.1

### Help us help you

Yes, I'd like to be assigned to work on this item

**Comment by Sergio0694** [comment]
> "Execute a bound command to a button click that is not making use of the ChangeCanExecute in quick succession"

That is not a supported scenario. You should never invoke a command when `CanExecute` returns false.
