### ISSUE TITLE
[Feature] Snipppets for MVVM toolkit

### ISSUE THREAD

**Issue by erikthysell** [CommunityToolkit/dotnet#98]
### Describe the problem

In order to minimize repetitivity, snippets similar to propfull

### Describe the solution

I would love snippets similar to[ Prism Template Pack](https://prismlibrary.com/docs/getting-started/productivity-tools.html)

### Alternatives

using Prism Template Pack (just for `propp` which I guess would work, cmd would not since PRISM has the DelegateCommand instead of RelayCommand.)

**Comment by shaggygi** [comment]
Wouldn't want to hold back a feature due to future work, but I noticed there are efforts to modernize Snippet related.  Might review this first.

https://github.com/dotnet/roslyn/issues/56541

**Comment by MisinformedDNA** [comment]
With source generators, this now seems unnecessary. Close?

**Comment by erikthysell** [comment]
@MisinformedDNA  I do not know much about source generators but from what I read here: [https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview)
I cannot see how that would make it as nice/easy as a snippet...

**Comment by erikthysell** [comment]
@MisinformedDNA  I do not know much about source generators but from what I read here: [https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview](https://learn.microsoft.com/en-us/dotnet/csharp/roslyn-sdk/source-generators-overview)
I cannot see how that would make it as nice/easy as a snippet...

**Comment by MisinformedDNA** [comment]
@erikthysell Yeah, I'm not entirely sure what I meant either. lol Maybe it was in reference to the reduction of the amount of code needed due to the source generators included in the toolkit such as `[ObservableProperty]` and `[RelayCommand]` which reduce the amount of code to a standard field or method with an attribute. So, a snippet could still be useful, but not as useful as before (pre 8.0).

**Comment by Sergio0694** [comment]
Closing this, as we don't plan on adding snippets for the MVVM Toolkit. As has been mentioned already, we provide source generators to help removing boilerplate and verbosity 🙂
