### ISSUE TITLE
Optionally generate backing field for [ObservableProperty] partial property

### ISSUE THREAD

**Issue by whiskhub** [CommunityToolkit/dotnet#993]
### Overview

[ObservableProperty] on partial properties is a much nicer way of declaring observable properties, than with the previous field approach.

However, one use case is seemingly no longer possible with the new approach: setting the backing field directly, to avoid raising a property changed event or calling any logic within the setter/On...Changed methods.

Say, you initialize the property in the constructor with a value read from disk. This would now call the On...Changed method, which would in return save the value again to disk, causing an unnecessary performance impact:

```csharp
internal partial class MainViewModel : ObservableObject
{
    public MainViewModel()
    {
        MyPartialProperty = ReadFromDisk();
    }

    [ObservableProperty]
    public partial string MyPartialProperty { get; set; }

    partial void OnMyPartialPropertyChanged(string oldValue, string newValue)
    {
        // do some expensive operation...
        WriteToDisk(newValue);
    }
}
```

Therefore it would be nice to optionally generate a backing field for the property, to allow for more granular control over the property. A different use case outside of the constructor would be properties that change each other, where a circular/infinite loop must be avoided.

### API breakdown

Some way to mark an observable property to generate a backing field, for example using a `[ObservablePropertyField]` attribute. The API and naming is preliminary and just to give an idea of the feature request.

```csharp
[ObservableProperty]
[ObservablePropertyField]
public partial string MyPartialProperty { get; set; }
```

### Usage example

```csharp
internal partial class MainViewModel : ObservableObject
{
    public MainViewModel()
    {
        myPartialProperty = ReadFromDisk(); // WriteToDisk() shall not be executed
    }

    [ObservableProperty]
    [ObservablePropertyField]
    public partial string MyPartialProperty { get; set; }

    partial void OnMyPartialPropertyChanged(string oldValue, string newValue)
    {
        // do some expensive operation...
        WriteToDisk(newValue);
    }
}
```

### Breaking change?

No

### Alternatives

1. Keep using the existing ObservableProperty on fields approach - has other disadvantages
2. Fallback to hand written code and manually create the backing field, property and change methods

### Help us help you

No, just wanted to propose this

**Comment by Sergio0694** [comment]
> "Say, you initialize the property in the constructor with a value read from disk. This would now call the On...Changed method"

No, it would not. Setting the property in the constructor will assign the backing field directly 🙂

Additionally, having an explicit field would break a lot of other functionality as well. For instance, you would no longer be able to have a property initializer. Nullability annotations would no longer work as well. Automatic attributes forwarding would not work either.

**Comment by whiskhub** [comment]
> No, it would not. Setting the property in the constructor will assign the backing field directly 🙂

Maybe I did something wrong, but I debugged it step-by-step and the partial method was called. Using the package 8.4.0-preview2.

**Comment by Sergio0694** [comment]
Mh, interesting. I'll need to try this. Double checking: you don't see the method called if you use a property initializer, right?

**Comment by whiskhub** [comment]
Correct, this will not call the method:

```csharp
[ObservableProperty]
public partial string MyPartialProperty { get; set; } = "abc";
```

Unfortunately this would only suffice for initializing with constant values, not something dynamically injected (e.g. database).

**Comment by Sergio0694** [comment]
@rikkigibson just double checking, is this intentional that setting a property using `field` from the constructor will always invoke the setter, instead of writing to the field directly like with a property initializer? I can imagine users being confused by this difference 🤔

**Comment by RikkiGibson** [comment]
Yes this is the design. IIRC, there were some issues around struct definite assignment that pushed us in this direction. Maybe we can discuss offline this coming week?

**Comment by whiskhub** [comment]
Any new insights?

**Comment by whiskhub** [comment]
If this isn't getting "fixed" language-side, could something like this be added as a workaround?

* `ObservableObject` has a field `protected bool _isDirectFieldAccessEnabled;`
* Auto-generated properties add a check `if (_isDirectFieldAccessEnabled) { field = value; return; }`
* In the constructor (or whenever direct field access is desired) you can set `_isDirectFieldAccessEnabled = true/false`.

That's just the basic idea. It could be optimized to reduce performance impact and improve usability:
* Create a new attribute `AllowsDirectFieldAccessAttribute` for properties so the `_isDirectFieldAccessEnabled` check is only generated when necessary
* Create a `IDisposable` wrapper for setting and resetting `_isDirectFieldAccessEnabled` (e.g. `using var fieldAccess = EnableDirectFieldAccess();`
* `_isDirectFieldAccessEnabled` is only generated if at least one `AllowsDirectFieldAccessAttribute` is used in the class.

Again, only the basic idea. IMO, this should at least work for the constructor. Otherwise, at least I personally would have to keep using partial fields for almost everything.
